### ISSUE TITLE
Custom email verification: securing the API

### ISSUE THREAD

**Issue by onovotny** [azure-ad-b2c/samples#1]
In the custom email verification sample, it uses a POST to a rest API from the client-side javascript to send an email.

This seems ripe for abuse if left unsecured. How do you recommend this be secured, otherwise, should it be a server-side call?

/cc @yoelhor

**Comment by jasjeetsuri** [comment]
You could combine with the Captcha sample also in the repo.

**Comment by yoelhor** [comment]
A note is added to the [sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-email-verifcation). Closing this issue
