### ISSUE TITLE
Add missing css styles in Template.html in sign-in-with-email sample

### ISSUE THREAD

**Issue by sven5** [azure-ad-b2c/samples#102]
Hi,

There is an html issue when sending custom individual emails as described in [this sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-email).

The example html template [Template.html](https://github.com/azure-ad-b2c/samples/blob/master/policies/sign-in-with-email/source-code/AADB2C.SignInWithEmail/Template.html) is missing some required styling otherwise the html looks distorted in Outlook.

this style is missing in the head:
```
    <!-- Template B O365 -->
    <style>
        table td {
            border-collapse: collapse;
            margin: 0;
            padding: 0;
        }
    </style>
```

I took this excerpt from the default email sent from Azure AD B2C.

**Comment by JasSuri** [comment]
Added.
