### ISSUE TITLE
Terms of Service Errors from Active Session

### ISSUE THREAD

**Issue by dave22000** [azure-ad-b2c/samples#103]
This is in reference to the Terms of Service policy: [https://github.com/azure-ad-b2c/samples/tree/master/policies/terms-of-service](https://github.com/azure-ad-b2c/samples/tree/master/policies/terms-of-service) 

When already signed in from an active session, and having already accepted the Terms of Use, attempting to run the custom policy again (or a separate but similar Custom Policy) results in being presented with the Terms of Use Checkbox. This checkbox should not show up, since the TOU has already been accepted. Additionally, checking the box does not allow you through to complete the sign-in. Only unchecking the box results in a successful sign-in.

This behavior can be seen by going to signup, creating an account, and accepting the TOU, [https://daveb2csandbox.b2clogin.com/DaveB2CSandbox.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_TermsOfService1&client_id=39dbe352-603c-431b-87ed-20f75e9e5476&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login](https://daveb2csandbox.b2clogin.com/DaveB2CSandbox.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_TermsOfService1&client_id=39dbe352-603c-431b-87ed-20f75e9e5476&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login)

Then, without logging out, go to the same link without the login prompt: [https://daveb2csandbox.b2clogin.com/DaveB2CSandbox.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_TermsOfService1&client_id=39dbe352-603c-431b-87ed-20f75e9e5476&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token](https://daveb2csandbox.b2clogin.com/DaveB2CSandbox.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_TermsOfService1&client_id=39dbe352-603c-431b-87ed-20f75e9e5476&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token)
You will bypass the username/password step and go straight to the TOU page, which you should not see, and you cannot get past unless you uncheck the box.

If you go to an incognito tab, so no active session, you will enter U/P and bypass the TOU page, as expected.

I have used the local accounts sample policy + the terms of use sample policy, only updating ids and tenant name, so no custom work.

![image](https://user-images.githubusercontent.com/38772694/90441565-c7d06780-e09e-11ea-9429-d0187b9be272.png)

**Comment by JasSuri** [comment]
Updated old sample in favour of new sample.

https://github.com/azure-ad-b2c/samples/blob/master/policies/sign-in-sign-up-versioned-tou
