### ISSUE TITLE
All the properties getting reset with edit-mfa-phone-number

### ISSUE THREAD

**Issue by sogetidev1** [azure-ad-b2c/samples#107]
Hi,
When I try the policy to edit mfa phone number using custom policy - "edit-mfa-phone-number", it edits the phone number just fine but resets the email and alternate email to blank string

**Comment by sogetidev1** [comment]
@JasSuri do I need to provide more details around the issue?

**Comment by JasSuri** [comment]
I think you are referencing some details from the portal. I need to figure out what those are on the raw attribute level (via graph api) and then try to reproduce this scenario. Not quite sure why this would be happening. 

I presume you have a username based sign up?

**Comment by sogetidev1** [comment]
Yes, mine is username based sign up

**Comment by sogetidev1** [comment]
@jasjeetsuri  The attribute for phone is strongAuthenticationPhoneNumber and for email it is strongAuthenticationEmailAddress

**Comment by JasSuri** [comment]
Although they look blank in the portal, is your password reset flow actually broken?

**Comment by AyushSingh1996** [comment]
Hi @JasSuri , i worked with @sogetidev1  on the issue above.
We are not using the password reset flow here. Using the sample, we implemented the edit mfa phone policy which takes input from user, verifies the phone, and then persists the stongAuthenticatinPhoneNumber claim.

However, while doing so, the email used for verification in SSPR ie strongAuthenticatonEmail is set to blank.
Similar behaviour when trying to edit the strongAuthenticatonEmail property via custom policy.

**Comment by asingh-swapa** [comment]
> 
> 
> Although they look blank in the portal, is your password reset flow actually broken?

Hi @JasSuri, I worked with @sogetidev1  on the issue mentioned above.
Yes, the password reset flow (_Password reset (Standard)_) breaks after editing the strongAuthenticationPhoneNumber, since strongAuthenticationEmailAddress is set to blank. It throws error "An account could not be found for the provided user ID."

Similar behavior after we edit the strongAuthenticationEmailAddress; strongAuthenticationPhoneNumberis set to blank. Upon running sign-in flow with MFA enabled, the user is prompted to enter a new phone number.

**Comment by JasSuri** [comment]
Got it, i will check this out, and find a fix.

**Comment by JasSuri** [comment]
I suspected the same as when adjusting signInNames, which we fixed the same way as per this SO post, to write both simultaneously:
https://stackoverflow.com/questions/63667066/persisting-strongauthenticationemailaddress-resets-strongauthenticationphonenum
