### ISSUE TITLE
force-password-reset-first-logon extensionProperties graphquery

### ISSUE THREAD

**Issue by andrewwiebe** [azure-ad-b2c/samples#109]
On the readme for force-password-reset-first-logon is states. 

"After you create the first account, you can run following Graph query, to make sure the extension attribute is created: https://graph.windows.net/myorganization/applications/00000000-0000-0000-0000-000000000000/extensionProperties. Replace the 00000000-0000-0000-0000-000000000000 with your application object Id. the result of this query should look like"

I am unable to get this query to work. Which application object ID am I supposed to use in that call? The exetnsions app? The identityexperienceframwork app? The proxyexperience app?

Thanks

**Comment by JasSuri** [comment]
Refers to the application registration referenced in the AAD-Common technical profile. This must be configured to allow the policy to read/write extension attributes.

**Comment by andrewwiebe** [comment]
So there are two issues. I am assuming the link in the readme is old as when I use it I get the following.

`{
    "odata.error": {
        "code": "Request_DataContractVersionMissing",
        "message": {
            "lang": "en",
            "value": "The specified api-version is invalid. The value must exactly match a supported version."
        }
    }
}`

It looks like there have been updates to the api to require a version. However when I try the following endpoint:

[https://graph.microsoft.com/v1.0/applications/<b2c-extensions-app_clientID>/extensionProperties](https://graph.microsoft.com/v1.0/applications/c3a79a35-ee3c-44a5-8208-596ea11ebb92/extensionProperties)

I get the following response.

`{
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '<b2c-extensions-app_clientID>' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2020-08-28T13:28:36",
      "request-id": "cf0254f8-515c-4728-a374-9a32f92fbdb8"
    }
  }
}`

**Comment by andrewwiebe** [comment]
I think just figured this out. You need to use the objectID, I was using the clientID. I missed read that in the readme.

However the link in the readme still needs to be updated to the following.

[https://graph.microsoft.com/v1.0/applications/<b2c-extensions-app_OBJECTID>/extensionProperties](https://graph.microsoft.com/v1.0/applications/<b2c-extensions-app_OBJECTID>/extensionProperties)

**Comment by JasSuri** [comment]
This also works, but I'll move to MS Graph API before closing this.
`https://graph.windows.net/myorganization/applications/<b2c-extensions-app_objectid>/extensionProperties?api-version=1.6`

I believe the readme assumed use of the Graph Explorer web app, which auto appends the version number ;)

**Comment by JasSuri** [comment]
Updated.
