### ISSUE TITLE
Improvement: Identity X Framework: Unified sign-in sign-up wrong tab-index for 'forgot your password' link.

### ISSUE THREAD

**Issue by MichielCornilleESC** [azure-ad-b2c/samples#110]
This is the UI for the sign-in  (sign/in sign up has the same problem)
Fields are organised:
- email address
- password
- forgot your password
![image](https://user-images.githubusercontent.com/46707408/91533778-c4e03d00-e910-11ea-96f5-72b253a528f3.png)

However, Tabbing trough the form jumps from email address to forgot your password, then to password.
We have multiple customers affected and complaining that this is an accessibility issue.

Looking at the generated HTML for the API div, we can see this is most likely because the forgot password link is weirdly located above the label (and later positioned below the input with CSS)

_We did not customize this CSS, it is wrong by default_

```<div class="entry-item">
            <div class="password-label">
              <label for="password">Password</label>
              <a id="forgotPassword" href="<customername>.onmicrosoft.com/B2C_1_SignIn/api/CombinedSigninAndSignup/forgotPassword?csrf_token=...&amp;p=B2C_1_SignIn">Forgot your password?</a>
            </div>
            <div class="error itemLevel" aria-hidden="true" style="display: none;">
              <p role="alert"></p>
            </div>
            <input type="password" id="password" name="Password" placeholder="Password" aria-label="Password">
          </div>
```

Suggestion would be to either add correct tabindex, or generate correct HTML In a new version of the layout.
Thanks in advance!

**Comment by JasSuri** [comment]
Seems to be a recent update that may have caused this. For now you can use some JS to adjust the tabindex.

**Comment by MichielCornilleESC** [comment]
Thanks for pointing me to a workaround. I'd like to see this fixed properly. Is there anywhere I can contribute to the templates?

**Comment by JasSuri** [comment]
This will be something we need to fix internally. You can raise a support ticket to get a more official process going.

**Comment by Eulinky** [comment]
Hasn't been fixed as of today... really annoying!

**Comment by murphyslaw** [comment]
The reported issue still exists. We are using the following Typescript, to fix the order.

```Typescript
function reorderForgotPasswordLink(): void {
  const forgotPasswordLink = document.querySelector<HTMLLinkElement>('#forgotPassword');

  if (!forgotPasswordLink) return;

  forgotPasswordLink.closest('.entry-item')?.appendChild(forgotPasswordLink);
}
```

It would be great, if this could be fixed.
