### ISSUE TITLE
First name / last name cannot be extracted from Apple Account

### ISSUE THREAD

**Issue by wattsdeveloper** [azure-ad-b2c/samples#111]
I am following everything according to docs to configure Apple provider on our custom policies:
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple

And as documented there, I cannot retrieve first name / last name from Apple and set that onto AD B2C claims, due to non-standard way they return that. Is there any way to make this work? Docs mention you can do that afterwards via some other API, maybe someone already made that and could provide an example?

**Comment by JasSuri** [comment]
See this https://github.com/azure-ad-b2c/samples/issues/104#issuecomment-679997649

**Comment by tdemanincor-pa** [comment]
Apple is rejecting our app because of this issue. Apparently, they are no longer allowing us to collect the first and last name after using Apple sign up cause it is redundant and against their new policy. Is this being addressed with Azure?

**Comment by JasSuri** [comment]
We are working on proper integration with AppleId, this is high up on our list, but I dont have an ETA to share as right now.

**Comment by wattsdeveloper** [comment]
Facing same issue. Apple rejected our app from store due to us trying to collect first/last names manually. Fix for this needed real bad, will miss info of many users until this is fixed.

**Comment by vistpp** [comment]
Facing same issue. Apple rejected app from store due to us trying to collect first/last names manually. Fix needed real bad, until then we will just lose user information, since AD B2C doesn't expose any way to access that token response.. :(

**Comment by JasSuri** [comment]
I am following up on getting this fix released.

**Comment by vistpp** [comment]
@JasSuri, that is great news, any estimate when this can be expected to be released?

**Comment by maQus123** [comment]
@JasSuri We're also working on B2C-SignInWithApple. Any news on this? :)

**Comment by JasSuri** [comment]
Hopefully next week we can share more.

**Comment by maQus123** [comment]
@JasSuri Any news? Thanks for info :)

**Comment by JasSuri** [comment]
Please try this

```xml
<TechnicalProfile Id="Apple-OIDC">
          <DisplayName>Apple</DisplayName>
          <Protocol Name="OpenIdConnect" />
          <Metadata>
            <Item Key="ProviderName">apple</Item>
            <Item Key="authorization_endpoint">https://appleid.apple.com/auth/authorize</Item>
            <Item Key="AccessTokenEndpoint">https://appleid.apple.com/auth/token</Item>
            <Item Key="JWKS">https://appleid.apple.com/auth/keys</Item>
            <Item Key="issuer">https://appleid.apple.com</Item>
            <Item Key="scope">name email openid</Item>
            <Item Key="HttpBinding">POST</Item>
            <Item Key="response_types">code</Item>
            <Item Key="external_user_identity_claim_id">sub</Item>
            <Item Key="response_mode">form_post</Item>
            <Item Key="ReadBodyClaimsOnIdpRedirect">user.name.firstName user.name.lastName user.email</Item>
          </Metadata>
          <InputClaims />
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="userId" PartnerClaimType="sub" />
            <OutputClaim ClaimTypeReferenceId="identityProvider" DefaultValue="https://appleid.apple.com" AlwaysUseDefaultValue="true" />
            <OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="socialIdpAuthentication" AlwaysUseDefaultValue="true" />
            <OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="user.name.firstName" />
            <OutputClaim ClaimTypeReferenceId="surname" PartnerClaimType="user.name.lastName" />
            <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="user.email" />
          </OutputClaims>
          <OutputClaimsTransformations>
            <OutputClaimsTransformation ReferenceId="CreateRandomUPNUserName" />
            <OutputClaimsTransformation ReferenceId="CreateUserPrincipalName" />
            <OutputClaimsTransformation ReferenceId="CreateAlternativeSecurityId" />
            <OutputClaimsTransformation ReferenceId="CreateObjectIdentityForSocialIdps" />
            <OutputClaimsTransformation ReferenceId="AddToObjectIdentityCollection" />
            <OutputClaimsTransformation ReferenceId="CreateSubjectClaimFromAlternativeSecurityId" />
          </OutputClaimsTransformations>
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-SocialLogin" />
        </TechnicalProfile>
```

**Comment by Norrch2** [comment]
Hi @JasSuri this is what we use and it works. However, our concern is that this isn't documented and therefore could be pulled and break our application whenever a new solution has been developed.

**Comment by JasSuri** [comment]
It should get documented in a month or so.

**Comment by Norrch2** [comment]
Everyone following this issue should also note that the names claims will only be passed through the first time the user authenticates your application. If the user has a pre-established relationship, Apple will not send you the names claims.
