### ISSUE TITLE
What is maximum limit for the User name(email) at signup?

### ISSUE THREAD

**Issue by Webrusterkk** [azure-ad-b2c/samples#112]
Maximum limit that is accepting is 100characters (including @) 

Is there any maximum limit for the email at signup?

**Comment by cljung** [comment]
@Webrusterkk - do you mean that what length in the email field that the UX accept so that you do not enter >100 chars there and then get rejected while trying to persist it?

**Comment by Webrusterkk** [comment]
Is there any limit for adding the email?

**Comment by JasSuri** [comment]
By signInType, the following limits apply:
username: 64 char
emailAddress: 100 char
custom: 100 char
