### ISSUE TITLE
Azure AD B2C Company Branding Sign-in page text rendering as raw HTML

### ISSUE THREAD

**Issue by frankkilcommins** [azure-ad-b2c/samples#113]
It seems that the Company Branding > Sign-in page text capability is broken within B2C. All content is being converted and rendered as _raw_ HTML. Not sure on exact time frame of issue occurring but seems to be since end of August approx.

Example: setting "company text testing" as the sign-in page text within the Company Branding section results in **\<p\>company text testing\</p\>** being rendered in the UI

<img width="622" alt="Company Text Specified" src="https://user-images.githubusercontent.com/15875424/92948140-d832f280-f450-11ea-861f-5d1571e46b41.png">
<img width="499" alt="Company Text Rendered" src="https://user-images.githubusercontent.com/15875424/92948143-d8cb8900-f450-11ea-9e1c-11bd4924714d.png">

**Comment by JasSuri** [comment]
Please raise a support ticket via the Azure Portal for this (it’s already being looked into), it’s not related to the custom policies themselves in this repo.
