### ISSUE TITLE
Email invite custom policy, exception when running the flow.

### ISSUE THREAD

**Issue by lizetpenamsft** [azure-ad-b2c/samples#114]
Hi all,
We are developing a custom policy based on the example for the [email invitation custom policy](https://github.com/azure-ad-b2c/samples/tree/master/policies/invite) . In our case, we created the digital certificate to sign the id_token_hint as indicated in the example and stored this certificate in AKV. We created an Azure Function, as opposed to the asp.net core app shown on the example. The Azure Function reads the digital cert from AKV using an MSI, and generates the token and the URL to be sent via email to the invited user.
We see the URL and token generation go through fine, the token can be deserialized using https://jwt.ms and the policy doesn't show errors when we upload it to our B2C tenant.
However, when the end user accesses the link to run the policy/flow, instead of the signup form we get the following:
**_AADB2C: An exception has occurred. Correlation ID: 3c36ef2e-f8ce-431c-95fb-6cb359ab64cb Timestamp: 2020-09-15 19:27:45Z_**
As our temporary reply URL we configured https://jwt.ms

Here's the code for our [Azure Function](https://custompolicysa.blob.core.windows.net/b2cfiles/index.js)
The [response](https://custompolicysa.blob.core.windows.net/b2cfiles/Response.json)
The modified [invite custom policy](https://custompolicysa.blob.core.windows.net/b2cfiles/SignUpInvitation.xml).

Our question is, how can we get more information to determine the root cause of the exception in B2C?
The expected result is to see the signup form, however on the jwt.ms that we configured as reply URL we're only seeing the exception above.

Thank you.

**Comment by JasSuri** [comment]
The key with id 'client_secret' not found for technical profile: 'IdTokenHint_ExtractClaims', tenant: 'gsgsdev.onmicrosoft.com', policy: 'B2C_1A_signup_invitation'

```xml
<Metadata>
<!-- Sample action required: replace with your endpoint location  -->
<!--  <Item Key="METADATA">https://your-app.azurewebsites.net/.well-known/openid-configuration</Item>  -->
<!--  <Item Key="IdTokenAudience">your_optional_audience_override</Item>  -->
<Item Key="issuer">https://myissuer.com</Item>
</Metadata>
```

You didn't provide the metadata endpoint for B2C to validate the tokens signature.

**Comment by lizetpenamsft** [comment]
Hi @JasSuri 
It isn't clear to me how to generate the metadata endpoint to include the certificate uploaded to the Policy Keys. Is the metadata endpoint URL:
https://tenant.b2clogin.com/tenant.onmicrosoft.com/<policy-name>/v2.0/.well-known/openid-configuration

When we upload the certificate to the TLS/SSL settings for our Azure Function, we have no way to host or generate this metadata document to include this cert... so the only endpoint we can think of is the endpoint above generated by B2C for the invitation policy. Is that the endpoint we need to include in the metadata element?

Thanks in advance.

**Comment by JasSuri** [comment]
Follow this
https://github.com/azure-ad-b2c/samples/tree/master/policies/invite#using-b2c-to-generate-the-metadata-endpoints

**Comment by lizetpenamsft** [comment]
I followed the steps from the guide and still get the same error.

1.	I downloaded the Certificate which was generated on AKV as .cer file. Thumbprint - 31ACCDD6398C48DDF730BF99B9E29C57FF4D354A 

2.	Uploaded the .cer file to Policy Keys under the name of KeyVaultCert as container name.
![certificate](https://user-images.githubusercontent.com/49248114/93528076-6864b200-f8ff-11ea-9585-8cc84f29b1db.jpg) 

3.	Then I changed the Base Policy for the JWTIssuer Technical Profile.
![JWTIssuerTP](https://user-images.githubusercontent.com/49248114/93528088-6b5fa280-f8ff-11ea-9dcd-9e67d644ed95.jpg)
 

4.	Finally I uploaded all the policies to B2C Identity Experience Framework.

Here is the screenshot generated metadata endpoint - https://tenant.b2clogin.com/tenant.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_signup_invitation
![RunFlowScreen](https://user-images.githubusercontent.com/49248114/93528138-7b778200-f8ff-11ea-87db-8009c5acf1e3.jpg)

I also changed the metadata code in SignUpInvitation.xml but we still got the same error on JWT app.
![metedatacode](https://user-images.githubusercontent.com/49248114/93528147-816d6300-f8ff-11ea-85d2-0a5308c55291.jpg)

We still get the same error.

**Comment by lizetpenamsft** [comment]
One additional question, since we are completing all the steps sby the guide provided. The Azure Function is using nodeJS and the default algorithm when creating the id_token_hint to generate the token signature, is HS256, not RS256, could this be an issue for B2C to fail evaluating the token digital signature?

**Comment by JasSuri** [comment]
HS256 is representative of a symmetric key signing operation, therefore the metadata, using an asymmetric cert, wouldn't make sense. You need to sign the token using RSA256 with the same Cert you put into B2C policy keys.

If you cannot do this, see this sample for symmetric key signing.
https://github.com/azure-ad-b2c/id_token_hint

**Comment by lizetpenamsft** [comment]
@JasSuri 
Understood, I'm explicitly using the RS256 algorithm in the JS code that generates the id_token_hint and signs this JWT. The NodeJS code we are using on our Azure Function defaulted the token signing algorithm to HS256, which caused several token signature validation errors.

Now, we do have a question on the well-known OIDC/OAUTH2 metadata endpoint as we progress completing the email invitation policy customization.

On the Azure Portal, the B2C metadata endpoint has two different URI formats shown on the UI for a given custom policy:

  https://tenant.b2clogin.com/tenant.onmicrosoft.com/<policy-name>/v2.0/.well-known/openid-configuration
and
    https://tenant.b2clogin.com/tenant.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=policy_name  

You can find the first URI under App Registrations -> Endpoints on the Overview Panel of the B2C tenant in question.
The second URI format is on the blade for the specific custom policy under Identity Experience Framework.

**_Does the metadata xml element under the Technical Profile Id_Token_Hint_ExtractClaims need to follow a specific URI format, query string vs uri segment?_**

Thank you!
-Lizet

**Comment by JasSuri** [comment]
Better to use the one which uses the policy id param in the URL.

**Comment by lizetpenamsft** [comment]
why?
