### ISSUE TITLE
user authentication fails with error "invalid username and password". 

### ISSUE THREAD

**Issue by syedmustafashah** [azure-ad-b2c/samples#115]
Hi,
We are developing a portal with ADB2C based authentication. 
**SIGNUP**
We are using the invitation-based sign in process where admin can enter the details of new users (sign up) within our website and an email is sent to user's email address with an invitation link. Clicking this link takes the user to create password screen and after successful password creation, user details are written in AD B2C user store and user can login later. 
**SIGNIN**
We have used the standard out of the box sign in policy (user flow) for user login using email address. 
Now we need to enable MFA (with Authenticator App) in our application. 
I was able to follow steps mentioned articles below 
•	https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp
•	 https://medium.com/@snkaushi_9371/enable-totp-based-multi-factor-authentication-in-azure-ad-b2c-84e967d76aa4 
and setup a proper signup flow with Authenticator App. 

**Update Custom Signup flow to register Authenticator App**
I was able to customize our current signup policy to introduce a step to register Authenticator App, after creating a password. The signup flow works fine. 
The problem is that when we try to use the sign in policy from 
TrustFrameworkBase.xml 
SignUpOrSignin.xml

The new created user is unable to signin even if we use correct credentials. The login screen gives an error of “Invalid username and password.” When the credentials are correct. 
If we give wrong password, it gives a proper message that “invalid password” but when we try with correct credentials, it gives invalid username and password error. 

Another interesting point is that when we use the standard sign in custom policy (user flow), it authenticates the same user successfully and lets the user enter the website. 
Can you please help me in diagnosing the problem here?
Problem: Invalid Username and Password

[B2C_1A_TOTP_signin.txt](https://github.com/azure-ad-b2c/samples/files/5263972/B2C_1A_TOTP_signin.txt)
[B2C_1A_TOTP_TrustFrameworkExtensions (2).txt](https://github.com/azure-ad-b2c/samples/files/5263974/B2C_1A_TOTP_TrustFrameworkExtensions.2.txt)
[B2C_1A_TOTP_TrustFrameworkBase.txt](https://github.com/azure-ad-b2c/samples/files/5263975/B2C_1A_TOTP_TrustFrameworkBase.txt)

**Comment by JasSuri** [comment]
This is usually because login-noninteractive is not setup properly.

**Comment by syedmustafashah** [comment]
@JasSuri  - could you please elaborate it a little more. What should I check to validate the login-noninteractive ?

**Comment by JasSuri** [comment]
Refollow this
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=applications#register-identity-experience-framework-applications

and:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=applications#add-application-ids-to-the-custom-policy

**Comment by anandlingaraj** [comment]
[base.txt](https://github.com/azure-ad-b2c/samples/files/5656598/base.txt)
[Extention.txt](https://github.com/azure-ad-b2c/samples/files/5656599/Extention.txt)
[SignUpOrSignin.txt](https://github.com/azure-ad-b2c/samples/files/5656600/SignUpOrSignin.txt)

Is there anything wrong in the templates for custom ??.  Followed the same docs
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=applications#add-application-ids-to-the-custom-policy
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started?tabs=applications#register-identity-experience-framework-applications

Is there an issue with ProxyIdentityExperienceFramework & IdentityExperienceFramework to be swapped under login-NonInteractive ? tried all options and exhausted importing or recreating policies and keys. Nothing works. Case under progress. Support team wasnt able to fix it too and how can this be closed ?

**Comment by JasSuri** [comment]
Your proxyIef app and Ief app config is incorrect.

Delete those two application registrations and use my tool instead https://aka.ms/iefsetup to automate the article.
