### ISSUE TITLE
Can't use B2E Optinal Claims with B2C 

### ISSUE THREAD

**Issue by WSGomes11** [azure-ad-b2c/samples#123]
Hi folks!

Hi Harsh!

We are trying to work with B2E optional claims … we followed this [doc ](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims)and [this](https://docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-1.0) to create the extension Claim at B2E, than populate it with some value… and enable it on Token Conf/Manifest. We also setup de XML with the PartnerClaimType but we can’t receive the Claim from B2E. Do you have some tip or idea why we cant receive the claim? 

Defaults claims works fine, but optional… we spent at least 2 days with tons of tests… =( 

Extension Claim
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#applications('XXX9f805-40cb-41af-80ae-c63201919XXX')/extensionProperties",
    "value": [
        {
            "id": "XXX707f9-8cdb-4cfa-996e-59da8512fXXX",
            "deletedDateTime": null,
            "appDisplayName": "",
            "name": "extension_XXXb714c01374c3e89a7c700bbd0eXXX_perfil",
            "dataType": "String",
            "isSyncedFromOnPremises": false,
            "targetObjects": ["User"]
        }
    ]
}

Populated claim from and User
{                  "extension_XXXb714c01374c3e89a7c700bbd0eXXX_perfil": "tempinfo",
}

B2E App Manifest
"saml2Token": [
                                               {
                                                               "name": "extension_XXXb714c01374c3e89a7c700bbd0eXXX_perfil",
                                                               "source": "user",
                                                               "essential": false,
                                                               "additionalProperties": []
                                               }
                               ]

OpenId ClaimProvider
            <OutputClaim ClaimTypeReferenceId="extension_perfil" PartnerClaimType="extension_XXXb714c01374c3e89a7c700bbd0eXXX_perfil" />
Obs.: we also tried “extension_perfil” and “extn.perfil”

**Comment by JasSuri** [comment]
Since this is not an issue with a specific policy on this repo, and there is a stackoverflow post, I will close this off to keep comms in the correct place.
https://stackoverflow.com/questions/64249327/how-i-retrieve-a-extensionproperty-on-b2c

**Comment by renidantass** [comment]
Hi, Jas, can you review the post in Stackoverflow again?
