### ISSUE TITLE
Question - Reset Password - Alternative using Mobile Phone

### ISSUE THREAD

**Issue by danielquest** [azure-ad-b2c/samples#124]
Hi Guys,

I am trying to implement a scenario where the user is unable to receive the code to reset the password by email.

In that case my idea is to send the code to a mobile number that was collected in the signup flow, so the user is able to complete the password reset.

Any tips how to implement it or have you been through this scenario?

That is a similar flow that google uses to reset password (please find the attached image).

![Alternative to reset password](https://user-images.githubusercontent.com/52450944/95445465-f78d4480-0956-11eb-9c4d-2b0125d730dc.png)

**Comment by JasSuri** [comment]
I added a sample for it [here](https://github.com/azure-ad-b2c/samples/tree/master/policies/pwd-reset-via-email-or-phone).

**Comment by danielquest** [comment]
Hi @JasSuri 

Brilliant, I got the idea!!!

Could you please share the TrustFrameworkExtensions and TrustFrameworkBase that you are using?


I have read the notes:

"This sample policy is based on SocialAndLocalAccounts starter pack. All changes are marked with Sample: comment inside the policy XML files. Make the necessary changes in the Sample action required sections."


Yet I does not seem to work with SocialAndLocalAccounts starter pack it looks like it miss the <TechnicalProfile Id="SM-MFA">
and the first step where you type the email is requiring email verification.

**Comment by JasSuri** [comment]
The starter pack is deployed as part of getting started with custom policies
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started


git clone https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack

**Comment by danielquest** [comment]
It did cut off a bit. It was missing <TechnicalProfile Id="SM-MFA"> and the first step (LocalAccountDiscoveryUsingEmailAddress) is asking for email verification. Maybe I should use the https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/SocialAndLocalAccountsWithMfa as base.

**Comment by JasSuri** [comment]
Yes youll need to use SocialAndLocalAccountsWithMfa as the base file here, ill update that.

**Comment by danielquest** [comment]
Just to let you know. I does work fine using the SocialAndLocalAccountsWithMfa. The only modification that I did was modify the LocalAccountDiscoveryUsingEmailAddress in the SocialAndLocalAccountsWithMfa to remove the email validation: <Item Key="EnforceEmailVerification">false</Item>

**Comment by JasSuri** [comment]
Removed email verification disabled flat, and updated readme to reference SocialAndLocalAccountsWithMfa. Thanks for the feedback.

**Comment by cyrilmatthew26** [comment]
@JasSuri The policy still forces me to verify the email address (using send OTP) entered first before moving on to the page where I can select the radio button. 
The email validation is still enabled. Is it possible to replace that with something like checking account exists already like mentioned here? --> https://github.com/azure-ad-b2c/samples/tree/master/policies/pwd-reset-email-exists/policy
