### ISSUE TITLE
UI permissions as custom user attributes/claims

### ISSUE THREAD

**Issue by patolax** [azure-ad-b2c/samples#125]
I am using MSAL on angular for authentication with Azure B2C and sign-in flow to login.

I was able to add a couple of custom user attributes and embed them in the token. Now I want to implement UI permissions on the app. (say I want to give read permissions to a view but hide edit/delete buttons on that view based on permissions).

Is this possible to implement such claims (e.g. my_view_read: boolean, my_view_edit: boolean) on B2C? Do I have to embed them as user attributes to include in the token?

How can this be done, in the case of this sample application?

**Comment by JasSuri** [comment]
You need to call an external system via REST API to fetch authorization information and insert into into the token:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-rest-api-claims-exchange
