### ISSUE TITLE
Outdated jQuery in use: xss vulnerability

### ISSUE THREAD

**Issue by JohnPaulHarold** [azure-ad-b2c/samples#127]
This recently got flagged on a pen test.

Some of the pages served by ADB2C use jQuery 1.1.0.

Others use 3.4.1, which has been found to contain a XSS vulnerability.
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

Latest jQuery is 3.5.1.

Can someone update this to a supported and or newer jQuery version.

**Comment by JasSuri** [comment]
Not really the right place for this. You can open up product feedback at Microsoft Uservoice.

The samples on this repo use a mix of page layouts with/without JS contracts depending on whether the sample itself needed custom JS.

Without a page contract, the AAD B2C service uses Jquery 1.1.0.

With a page contract, the AAD B2C service uses JQuery 3.4.1.

A page contract is used as to not break your JS code that takes dependency on the service delivered JS. A new page contract version is released to address issues like this.
