### ISSUE TITLE
For mfa-email-or-phone custom policy how to configure MFA Session to skip MFA Prompt for Every sign in?

### ISSUE THREAD

**Issue by anomepani** [azure-ad-b2c/samples#131]
For [mfa-email-or-phone](https://github.com/azure-ad-b2c/samples/tree/master/policies/mfa-email-or-phone) custom policy how to configure MFA Session to skip MFA Prompt for Every sign in?

When I am testing Policy on Azure AD B2C Portal it will always prompt MFA dialog for both Email and Phone method,
How can we configure and Test MFA Session?

Thanks in advance for any suggestion

**Comment by JasSuri** [comment]
Did you remove the query parameter from the portal link? &prompt=login

**Comment by anomepani** [comment]
Thank you @JasSuri I have removed the portal link? `&prompt=login` param and it will not prompting login and MFA again If I have configured MFA using Phone number but if I have configured MFA using email then it is prompting to verify again with code.

Do we need to configure separately for Email-based MFA?

**Comment by JasSuri** [comment]
Ok that’ll be a bug, I’ll look into it

**Comment by anomepani** [comment]
@JasSuri , Thank you very much for your prompt reply.

**Comment by JasSuri** [comment]
I am not able to reproduce this issue in Angular App using Implicit flow. Both sign in with an account protected by email OTP or account protected with SMS is working to get tokens silently.

**Comment by anomepani** [comment]
Is it possible to share your policy/policies which you have tested?
So that I can review and configure policy accordingly and implement it in my tenant.
A troubleshooting configuration issue with B2C is very difficult.

Thanks for reply

**Comment by JasSuri** [comment]
[MFA_phone_or_email_Extensions.zip](https://github.com/azure-ad-b2c/samples/files/5603579/MFA_phone_or_email_Extensions.zip)
