### ISSUE TITLE
B2C relying-party-rbac Sample error Can not read user groups

### ISSUE THREAD

**Issue by dozunu** [azure-ad-b2c/samples#132]
Hi
I am trying to get the B2C relying-party-rbac Sample up and running in a Web app service in Azure.
Policies are updated according to my B2C tenant, sample code also with the B2C tenant, B2C app id and secret.
Using a console app sample, I can get the groups of a user.
Using the sample here running as a Web app in Azure, I cant get it run. I get in the SignIn flow the error coming from the code
 Can not read user groups

Any help please would be appreciated.

Thanks and best regards
Dumitru

**Comment by JasSuri** [comment]
Did you try setting a breakpoint in this method and determining where the exception gets thrown?

https://github.com/azure-ad-b2c/samples/blob/master/policies/relying-party-rbac/source-code/AADB2C.RBAC.Sample/AADB2C.RBAC.Sample/Controllers/IdentityController.cs#L63


It’s a catch-app exception so you need to debug it.

**Comment by dozunu** [comment]
Hi, I have added more information in the catch so I see following

 'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...) Parameter name: authority at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.DetectAuthorityType(String authority) at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.Init(String authority, Boolean validateAuthority) at AADB2C.RBAC.Sample.AzureADGraphClient..ctor(String tenant, String clientId, String clientSecret) in C:\Users\de2afa\Downloads\B2c Samples\AADB2C.RBAC.Sample\AADB2C.RBAC.Sample\AzureADGraphClient.cs:line 33 at AADB2C.RBAC.Sample.Controllers.IdentityController.<IsMemberOf>d__2.MoveNext() in C:\Users\de2afa\Downloads\B2c Samples\AADB2C.RBAC.Sample\AADB2C.RBAC.Sample\Controllers\IdentityController.cs:line 65

https://github.com/azure-ad-b2c/samples/blob/af3288e585ecd7101c3f6eb6c26c09b5b1bde2eb/policies/relying-party-rbac/source-code/AADB2C.RBAC.Sample/AADB2C.RBAC.Sample/Controllers/IdentityController.cs#L65 

can you pls provide the correct format / sample for this one?
 this.authContext = new AuthenticationContext(aadInstance + this.Tenant); 
It seems here is the problem.

Moreover, the app is registred in Azure B2C, which Graph API permission should it have?

Thanks and best regards
Dumitru

**Comment by JasSuri** [comment]
You can find Azure AD Authorities here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#authority

The permissions for Azure AD Graph API in the Azure Portal should be the ability to read Groups (Directory.Read.All)
The API reference for Azure AD Graph is here:
https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations#GetUsersMemberships

The Microsoft Graph API has superseded the AAD Graph API. You should look at MS Graph API samples to reimplement this code segment.
https://docs.microsoft.com/en-us/graph/api/group-checkmembergroups?view=graph-rest-1.0&tabs=http
Code sample:
https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp
