### ISSUE TITLE
Password ageing validation not working

### ISSUE THREAD

**Issue by sandipNGA** [azure-ad-b2c/samples#133]
Hello,

The password ageing validation is not working as expected. Here I am attaching my policy file of my Lab System. Would apricate if you could review and point me what might be going wrong.

<TrustFrameworkPolicy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06" PolicySchemaVersion="0.3.0.0" TenantId="hreudevadb2c.onmicrosoft.com" PolicyId="B2C_1A_TrustFrameworkExtensions" PublicPolicyUri="http://hreudevadb2c.onmicrosoft.com/B2C_1A_TrustFrameworkExtensions" TenantObjectId="2e099f2a-d6d8-4d0c-9e35-6cbffc5abc75">
  <BasePolicy>
    <TenantId>hreudevadb2c.onmicrosoft.com</TenantId>
    <PolicyId>B2C_1A_TrustFrameworkBase</PolicyId>
  </BasePolicy>
  <BuildingBlocks>
    <ClaimsSchema>
      
      
      <ClaimType Id="currentDateTime">
        <DisplayName>Current date and time</DisplayName>
        <DataType>dateTime</DataType>
        <UserHelpText>Current date and time</UserHelpText>
      </ClaimType>
      
      <ClaimType Id="extension_passwordResetOn">
        <DisplayName>Password reset on</DisplayName>
        <DataType>dateTime</DataType>
        <UserHelpText>The last time user reset the password</UserHelpText>
      </ClaimType>
      
      <ClaimType Id="isPasswordResetOnGreaterThanNow">
        <DisplayName>Indicates whether password reset is required</DisplayName>
        <DataType>boolean</DataType>
      </ClaimType>
      
      <ClaimType Id="isPasswordResetOnPresent">
        <DisplayName>Is password reset on presented</DisplayName>
        <DataType>boolean</DataType>
      </ClaimType>
      
      <ClaimType Id="skipPasswordReset">
        <DisplayName>Skip password reset</DisplayName>
        <DataType>boolean</DataType>
      </ClaimType>
	  
	   <ClaimType Id="oldPassword">
        <DisplayName>Old Password</DisplayName>
        <DataType>string</DataType>
		<UserInputType>Password</UserInputType>
      </ClaimType>
      <ClaimType Id="newPassword">
        <DisplayName>New Password`</DisplayName>
        <DataType>string</DataType>
		<UserInputType>Password</UserInputType>
      </ClaimType>
      <ClaimType Id="reenterPassword">
        <DisplayName>Reenter Password</DisplayName>
        <DataType>string</DataType>
		<UserInputType>Password</UserInputType>
      </ClaimType>
      
      <ClaimType Id="EventType">
        <DisplayName>Event type</DisplayName>
        <DataType>string</DataType>
      </ClaimType>
      <ClaimType Id="EventTimestamp">
        <DisplayName>Event timestamp</DisplayName>
        <DataType>string</DataType>
      </ClaimType>
      <ClaimType Id="PolicyId">
        <DisplayName>Policy Id</DisplayName>
        <DataType>string</DataType>
      </ClaimType>
      <ClaimType Id="Culture">
        <DisplayName>Culture ID</DisplayName>
        <DataType>string</DataType>
      </ClaimType>
      <ClaimType Id="CorrelationId">
        <DisplayName>Correlation Id</DisplayName>
        <DataType>string</DataType>
      </ClaimType>
      <ClaimType Id="federatedUser">
        <DisplayName>Federated user</DisplayName>
        <DataType>boolean</DataType>
      </ClaimType>
      <ClaimType Id="parsedDomain">
        <DisplayName>Domain name</DisplayName>
        <DataType>string</DataType>
        <UserHelpText>The domain portion of the email address.</UserHelpText>
      </ClaimType>
      <ClaimType Id="userInLocalDirectory">
        <DisplayName>userInLocalDirectory</DisplayName>
        <DataType>boolean</DataType>
      </ClaimType>
      <ClaimType Id="ClientId">
        <DisplayName>ClientId</DisplayName>
        <DataType>string</DataType>
        <UserHelpText>The client_id query string parameter</UserHelpText>
      </ClaimType>
      
      <ClaimType Id="email">
        <DisplayName>email</DisplayName>
        <DataType>string</DataType>
        <UserHelpText>User's email</UserHelpText>
      </ClaimType>
      <ClaimType Id="identityProvider">
        <DisplayName>identityProvider</DisplayName>
        <DataType>string</DataType>
        <UserHelpText>Identity provider</UserHelpText>
      </ClaimType>
      <ClaimType Id="displayName">
        <DisplayName>displayName</DisplayName>
        <DataType>string</DataType>
        <UserHelpText>User's full name</UserHelpText>
        
      </ClaimType>
	  
	  <ClaimType Id="SamePassword">
		<DisplayName>samePassword</DisplayName>
		<DataType>boolean</DataType>
		<UserHelpText/>
	  </ClaimType>
    </ClaimsSchema>
    <ClaimsTransformations>
      
      <ClaimsTransformation Id="SetPasswordResetOn" TransformationMethod="GetCurrentDateTime">
        <OutputClaims>
          <OutputClaim ClaimTypeReferenceId="extension_passwordResetOn" TransformationClaimType="currentDateTime" />
        </OutputClaims>
      </ClaimsTransformation>
      
      <ClaimsTransformation Id="SetCurrentDateTime" TransformationMethod="GetCurrentDateTime">
        <OutputClaims>
          <OutputClaim ClaimTypeReferenceId="currentDateTime" TransformationClaimType="currentDateTime" />
        </OutputClaims>
      </ClaimsTransformation>
      
      <ClaimsTransformation Id="ComparePasswordResetOnWithCurrentDateTime" TransformationMethod="DateTimeComparison">
        <InputClaims>
          <InputClaim ClaimTypeReferenceId="currentDateTime" TransformationClaimType="firstDateTime" />
          <InputClaim ClaimTypeReferenceId="extension_passwordResetOn" TransformationClaimType="secondDateTime" />
        </InputClaims>
        <InputParameters>
          
          <InputParameter Id="operator" DataType="string" Value="earlier than" />
          
          <InputParameter Id="timeSpanInSeconds" DataType="int" Value="-80" />
		   
        </InputParameters>
        <OutputClaims>
          <OutputClaim ClaimTypeReferenceId="isPasswordResetOnGreaterThanNow" TransformationClaimType="result" />
        </OutputClaims>
      </ClaimsTransformation>
      
      <ClaimsTransformation Id="CheckIfPasswordResetOnPresent" TransformationMethod="DoesClaimExist">
        <InputClaims>
          <InputClaim ClaimTypeReferenceId="extension_passwordResetOn" TransformationClaimType="inputClaim" />
        </InputClaims>
        <OutputClaims>
          <OutputClaim ClaimTypeReferenceId="isPasswordResetOnPresent" TransformationClaimType="outputClaim" />
        </OutputClaims>
      </ClaimsTransformation>
      
      <ClaimsTransformation Id="CheckWhetherPasswordResetCanBeSkipped" TransformationMethod="AndClaims">
        <InputClaims>
          <InputClaim ClaimTypeReferenceId="isPasswordResetOnGreaterThanNow" TransformationClaimType="inputClaim1" />
          <InputClaim ClaimTypeReferenceId="isPasswordResetOnPresent" TransformationClaimType="inputClaim2" />
        </InputClaims>
        <OutputClaims>
          <OutputClaim ClaimTypeReferenceId="skipPasswordReset" TransformationClaimType="outputClaim" />
        </OutputClaims>
      </ClaimsTransformation>
	  
		<ClaimsTransformation Id="CheckPasswordEquivalence" TransformationMethod="StringContains">
		 <InputClaims>
			<InputClaim ClaimTypeReferenceId="oldPassword" TransformationClaimType="inputClaim1" />
			<InputClaim ClaimTypeReferenceId="newPassword" TransformationClaimType="inputClaim2" />
		</InputClaims>
		<InputParameters>
			<InputParameter Id="operator" DataType="string" Value="EQUAL" />
			<InputParameter Id="ignoreCase" DataType="string" Value="true" />
		</InputParameters>
		<OutputClaims>
			<OutputClaim ClaimTypeReferenceId="SamePassword" TransformationClaimType="outputClaim" />
		</OutputClaims>
	  </ClaimsTransformation>
	  
	  <ClaimsTransformation Id="AssertSamePasswordIsFalse" TransformationMethod="AssertBooleanClaimIsEqualToValue">
		<InputClaims>
			<InputClaim ClaimTypeReferenceId="SamePassword" TransformationClaimType="inputClaim" />
		</InputClaims>
		<InputParameters>
			<InputParameter Id="valueToCompareTo" DataType="boolean" Value="false" />
		</InputParameters>
	   </ClaimsTransformation>	
    </ClaimsTransformations>
    <ContentDefinitions>
      <ContentDefinition Id="api.error">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:globalexception:1.1.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Error page</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.idpselections">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:idpselection:1.0.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Idp selection page</Item>
          <Item Key="language.intro">Sign in</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.idpselections.signup">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:idpselection:1.0.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Idp selection page</Item>
          <Item Key="language.intro">Sign up</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.signuporsignin">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/unified.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/unified.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:unifiedssp:1.0.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Signin</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.selfasserted">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:selfasserted:1.1.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Collect information from user page</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.selfasserted.profileupdate">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:selfasserted:1.1.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Collect information from user page</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.localaccountsignup">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:selfasserted:1.1.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Sign up</Item>
        </Metadata>
      </ContentDefinition>
      <ContentDefinition Id="api.localaccountpasswordreset">
        <LoadUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</LoadUri>
        <RecoveryUri>https://dweuaadb2c01st.blob.core.windows.net/-aad-b2c/-ui.html</RecoveryUri>
        <DataUri>urn:com:microsoft:aad:b2c:elements:selfasserted:1.1.0</DataUri>
        <Metadata>
          <Item Key="DisplayName">Reset password</Item>
        </Metadata>
      </ContentDefinition>
    </ContentDefinitions>
  </BuildingBlocks>
  <ClaimsProviders>
    <ClaimsProvider>
      <DisplayName>Facebook</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="Facebook-OAUTH">
          <Metadata>
            <Item Key="client_id">facebook_clientid</Item>
            <Item Key="scope">email public_profile</Item>
            <Item Key="ClaimsEndpoint">https://graph.facebook.com/me?fields=id,first_name,last_name,name,email</Item>
          </Metadata>
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
    <ClaimsProvider>
      <DisplayName>Local Account SignIn</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="login-NonInteractive">
          <Metadata>
            <Item Key="client_id">ec31660d-70a2-4f67-907c-a8928c5f8dcb</Item>
            <Item Key="IdTokenAudience">bf6b99a0-dc20-4ed9-a9e1-2204455575e1</Item>
          </Metadata>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="client_id" DefaultValue="ec31660d-70a2-4f67-907c-a8928c5f8dcb" />
            <InputClaim ClaimTypeReferenceId="resource_id" PartnerClaimType="resource" DefaultValue="bf6b99a0-dc20-4ed9-a9e1-2204455575e1" />
          </InputClaims>
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
    <ClaimsProvider>
      <DisplayName>Token Issuer</DisplayName>
      <TechnicalProfiles>
        
        <TechnicalProfile Id="Saml2AssertionIssuer">
          <DisplayName>Token Issuer</DisplayName>
          <Protocol Name="None" />
          <OutputTokenFormat>SAML2</OutputTokenFormat>
          <Metadata>
            
            
            <Item Key="IssuerUri">https://hreudevadb2c.b2clogin.com/hreudevadb2c.onmicrosoft.com/B2C_1A_signup_signin_dev_saml</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="MetadataSigning" StorageReferenceId="B2C_1A_DevB2CSigningCert" />
            <Key Id="SamlAssertionSigning" StorageReferenceId="B2C_1A_DevB2CSigningCert" />
            <Key Id="SamlMessageSigning" StorageReferenceId="B2C_1A_DevB2CSigningCert" />
          </CryptographicKeys>
          <InputClaims />
          <OutputClaims />
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-Saml-sp" />
        </TechnicalProfile>
        
        <TechnicalProfile Id="SM-Saml-sp">
          <DisplayName>Session Management Provider</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.SSO.SamlSSOSessionProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
    <ClaimsProvider>
      <DisplayName>Application Insights</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="AppInsights-Common">
          <DisplayName>Application Insights</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.Insights.AzureApplicationInsightsProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
            
            <Item Key="InstrumentationKey">5e472923-25b1-476f-85c4-f9e1a410a1ed</Item>
            <Item Key="DeveloperMode">false</Item>
            <Item Key="DisableTelemetry ">false</Item>
          </Metadata>
          <InputClaims>
            
            <InputClaim ClaimTypeReferenceId="EventTimestamp" PartnerClaimType="{property:EventTimestamp}" DefaultValue="{Context:DateTimeInUtc}" />
            <InputClaim ClaimTypeReferenceId="PolicyId" PartnerClaimType="{property:Policy}" DefaultValue="{Policy:PolicyId}" />
            <InputClaim ClaimTypeReferenceId="CorrelationId" PartnerClaimType="{property:CorrelationId}" DefaultValue="{Context:CorrelationId}" />
            
            <InputClaim ClaimTypeReferenceId="ClientId" PartnerClaimType="{property:ClientId}" DefaultValue="{OIDC:ClientId}" />
            
            <InputClaim ClaimTypeReferenceId="email" PartnerClaimType="{property:Email}" DefaultValue="NotExists" />
            <InputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="{property:UserName}" />
            <InputClaim ClaimTypeReferenceId="identityProvider" PartnerClaimType="{property:IdentityProvider}" />
          </InputClaims>
        </TechnicalProfile>
        <TechnicalProfile Id="AppInsights-SignInRequest">
          <InputClaims>
            
            <InputClaim ClaimTypeReferenceId="EventType" PartnerClaimType="eventName" DefaultValue="SignInRequest" />
          </InputClaims>
          <IncludeTechnicalProfile ReferenceId="AppInsights-Common" />
        </TechnicalProfile>
        <TechnicalProfile Id="AppInsights-UserSignUp">
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="EventType" PartnerClaimType="eventName" DefaultValue="UserSignUp" />
          </InputClaims>
          <IncludeTechnicalProfile ReferenceId="AppInsights-Common" />
        </TechnicalProfile>
        <TechnicalProfile Id="AppInsights-SignInComplete">
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="EventType" PartnerClaimType="eventName" DefaultValue="SignInComplete" />
            <InputClaim ClaimTypeReferenceId="federatedUser" PartnerClaimType="{property:FederatedUser}" DefaultValue="false" />
            <InputClaim ClaimTypeReferenceId="parsedDomain" PartnerClaimType="{property:FederationPartner}" DefaultValue="Not Applicable" />
          </InputClaims>
          <IncludeTechnicalProfile ReferenceId="AppInsights-Common" />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
  <ClaimsProvider>
			<DisplayName>Password Reset without same password</DisplayName>
			<TechnicalProfiles>

				
				<TechnicalProfile Id="LocalAccountWritePasswordUsingObjectId">
					<DisplayName>Reset password</DisplayName>
					<Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<Metadata>
						<Item Key="ContentDefinitionReferenceId">api.localaccountpasswordreset</Item>
						<Item Key="UserMessageIfClaimsTransformationBooleanValueIsNotEqual">You must not use your old password.</Item>
					</Metadata>
					<CryptographicKeys>
						<Key Id="issuer_secret" StorageReferenceId="B2C_1A_TokenSigningKeyContainer" />
					</CryptographicKeys>
					<InputClaims>
						<InputClaim ClaimTypeReferenceId="objectId" />
					</InputClaims>
					<OutputClaims>
						<OutputClaim ClaimTypeReferenceId="oldPassword" Required="true" />
						<OutputClaim ClaimTypeReferenceId="newPassword" Required="true" />
						<OutputClaim ClaimTypeReferenceId="reenterPassword" Required="true" />
					</OutputClaims>
					<ValidationTechnicalProfiles>
						
						<ValidationTechnicalProfile ReferenceId="ComparePasswords" />
						<ValidationTechnicalProfile ReferenceId="AAD-UserWritePasswordUsingObjectId">
							<Preconditions>
								<Precondition Type="ClaimEquals" ExecuteActionsIf="true">
									<Value>SamePassword</Value>
									<Value>True</Value>
									<Action>SkipThisValidationTechnicalProfile</Action>
								</Precondition>
							</Preconditions>
						</ValidationTechnicalProfile>
					</ValidationTechnicalProfiles>
				</TechnicalProfile>

				
				<TechnicalProfile Id="ComparePasswords">
					<DisplayName>Compare Email And Verify Email</DisplayName>
					<Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.ClaimsTransformationProtocolProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
					<OutputClaims>
						<OutputClaim ClaimTypeReferenceId="SamePassword" />
					</OutputClaims>
					<OutputClaimsTransformations>
						<OutputClaimsTransformation ReferenceId="CheckPasswordEquivalence" />
						<OutputClaimsTransformation ReferenceId="AssertSamePasswordIsFalse" />
					</OutputClaimsTransformations>
				</TechnicalProfile>
			</TechnicalProfiles>
		</ClaimsProvider>
  </ClaimsProviders>
  <UserJourneys>
    <UserJourney Id="SignIn">
      <OrchestrationSteps>
        <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin">
          <ClaimsProviderSelections>
            <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
          </ClaimsProviderSelections>
          <ClaimsExchanges>
            <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="TrackSignInRequest" TechnicalProfileReferenceId="AppInsights-SignInRequest" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="3" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmail" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="4" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserReadWithObjectId" TechnicalProfileReferenceId="AAD-UserReadUsingObjectId" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="5" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="false">
              <Value>newUser</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>newUser</Value>
              <Value>false</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="TrackUserSignUp" TechnicalProfileReferenceId="AppInsights-UserSignup" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="6" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="TrackSignInComplete" TechnicalProfileReferenceId="AppInsights-SignInComplete" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="7" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
    </UserJourney>
  </UserJourneys>
</TrustFrameworkPolicy>

**Comment by JasSuri** [comment]
Can you describe exactly what the problem is?

**Comment by sandipNGA** [comment]
Hi Jas,


Thanks for your email. We would like the password to be expired within 120 seconds in the Development environment for testing purpose and then will make the necessary changes when deploying in the higher environment to set the password expiry to 90days. This feature is not working. Users are not forced to change pwd after timespan expired.



[cid:image003.png@01D6B14B.096B9F80]



If needed I can send the custom policy in the email again for your review and circle back what changes needs to be made to get it working. We were working with Microsoft Support on this and they have requested to raise this issue through github.


Thank you.

Sincerely,
NGA Human Resources | Sandip Chakraborty| Manager – Middleware, Build | Global Technology
Mobile: (+91) 8297000993 | E-mail: sandip.chakraborty@ngahr.com
[cid:image004.png@01D6B14B.D9225DE0]
>>Please consider the environment before printing this e-mail<<

**Comment by JasSuri** [comment]
The policy that you have in your post is not related to your question. That policy tries to prevent the user from using their last password for their new password.

Use this sample:
https://github.com/azure-ad-b2c/samples/tree/master/policies/force-password-reset-after-90-days

Provide a copy of how you have configured the claims transform `ComparePasswordResetOnWithCurrentDateTime`.

**Comment by sandipNGA** [comment]
Hello Jas,

Thanks again for your help. Please find attached the custom policy herewith this email. Please let me know what further changes should be done.
However, I was following Microsoft suggestion when opening the case, see below. If it helps I can open another one using the correct link if you provide me.
[cid:image001.png@01D6B1CA.E678B9B0]

Thank you.

Sincerely,
NGA Human Resources | Sandip Chakraborty| Manager – Middleware, Build | Global Technology
Mobile: (+91) 8297000993 | E-mail: sandip.chakraborty@ngahr.com
[cid:image004.png@01D6B1CA.F2413C40]
>>Please consider the environment before printing this e-mail<<

**Comment by JasSuri** [comment]
Your "email" ends up on public github, attachments are stripped. Can you please provide a copy of how you have configured the claims transform `ComparePasswordResetOnWithCurrentDateTime`.

**Comment by sandipNGA** [comment]
Hi Jas,

Can you please let me know your email ID, I will send it to you directly again?

Thank you.

Sincerely,
NGA Human Resources | Sandip Chakraborty| Manager – Middleware, Build | Global Technology
Mobile: (+91) 8297000993 | E-mail: sandip.chakraborty@ngahr.com
[cid:image002.png@01D6B205.84D17B30]
>>Please consider the environment before printing this e-mail<<
