### ISSUE TITLE
Custom TOTP Sample - SSO fails and break silent token calls

### ISSUE THREAD

**Issue by Webrusterkk** [azure-ad-b2c/samples#134]
For [Totp MFA]( https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-mfa-totp) even though we set the session expiry for 8hrs in `sign-in` policy , application is logging out after 24min 

Added `token_lifetime_secs` as `<Item Key="token_lifetime_secs">1200</Item>`
Added `id_token_lifetime_secs` as `<Item Key="id_token_lifetime_secs">1200</Item>` in  `JwtIssuer` Under `B2C_1A_TrustFrameworkBase`

In `Sign-in` Policy configured Session Expiry as follows:

`<SessionExpiryType>Absolute</SessionExpiryType>
   <SessionExpiryInSeconds>28800</SessionExpiryInSeconds>`

Any suggestions ?

**Comment by JasSuri** [comment]
Can you describe what you mean by `application is logging out after 24min`. The application will have its own session cookies that are not related to AAD B2C.

**Comment by Webrusterkk** [comment]
We are handling session for our application from the `token` generated after successfull login to the ADB2C, and we are continussly verifying the token and refreshing from the Azure AD-B2C.but without MFA, we are able to logout the user session after 8-hrs based on above configuration.  When we Add MFA Policy  the session is logging out after 20-24 min time.

**Comment by JasSuri** [comment]
Ok, I don't see how the sample would have any effect on the settings you mention.
Test with the starter pack policies to confirm whether you get the same or different behavior.

Make sure your REST APIs are not falling asleep and causing some sort of timeout.
If a silent token call works at least once, i would not expect the policy to be an issue. Considering you say it works for 20-24min - I presume you did at least 1 silent token call during this period?

**Comment by Webrusterkk** [comment]
It is a React JS App we are using `msal.js`. Actually we raised  Support ticket regarding this issue. the solution we got from engineering team is 


> During the next authorize request we are returning at following step in user journey. the SSO is not set correctly for this step. 
> This is a issue with policy and not a service issue.

```
        <OrchestrationStep Order="6" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>strongAuthenticationAppQRCodeBitmap</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AppFactorChallengeExchange" TechnicalProfileReferenceId="AppFactor-Challenge" />
          </ClaimsExchanges>
        
</OrchestrationStep>
```

So we were following the above sample, for our custom MFA setup

**Comment by JasSuri** [comment]
You need to answer all the questions for this to go anywhere.
- What version of MSAL.js
- Implicit or PKCE flow?

Considering you say it works for "20-24min":
- I presume you did at least 1 silent token call before 20 minutes elapsed? 
- Then silent token calls fail after 20 minutes?

**Comment by JasSuri** [comment]
Reading the policy

```xml
        <OrchestrationStep Order="9" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>strongAuthenticationAppQRCodeBitmap</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
```

In all requests where the user has already registered, and doing a sign in, `strongAuthenticationAppQRCodeBitmap` will not exist. It only exists during a Sign Up.
Therefore this _is_ a policy issue, and **ALL** silent token calls would fail. **Can you confirm that?**

**Comment by Webrusterkk** [comment]
> You need to answer all the questions for this to go anywhere.
> 
> * What version of MSAL.js
_We are using 1.3.2_
> * Implicit or PKCE flow?
_Implicit flow_
> 
> Considering you say it works for "20-24min":
> 
> * I presume you did at least 1 silent token call before 20 minutes elapsed?
_Yes we are doing_
> * Then silent token calls fail after 20 minutes?
_yes (authorize request fails)_

**Comment by Webrusterkk** [comment]
> Reading the policy
> 
> ```
>         <OrchestrationStep Order="9" Type="ClaimsExchange">
>           <Preconditions>
>             <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
>               <Value>strongAuthenticationAppQRCodeBitmap</Value>
>               <Action>SkipThisOrchestrationStep</Action>
>             </Precondition>
> ```
> 
> In all requests where the user has already registered, and doing a sign in, `strongAuthenticationAppQRCodeBitmap` will not exist. It only exists during a Sign Up.
> Therefore this _is_ a policy issue, and **ALL** silent token calls would fail. **Can you confirm that?**
_Yes , silent token calls are failing_ . if its a policy issue means a bug in the sample ?

**Comment by JasSuri** [comment]
So that makes more sense, its not that it fails after 20-24mins. It fails **ALL** the time when calling `acquireTokenSilent()`.
Yes, that is bug in the Policy session management.

We need to take a look at this line:
https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-mfa-totp/policy/TrustFrameworkExtensions.xml#L209

This needs to be re-enabled correctly, such that we skip this technical profile if the user already did it once (at Sign In). That would then allow `acquireTokenSilent()` to not get interrupted by an interactive request.

**Comment by Webrusterkk** [comment]
> So that makes more sense, its not that it fails after 20-24mins. It fails **ALL** the time when calling `acquireTokenSilent()`.
> Yes, that is bug in the Policy session management.
> 
> We need to take a look at this line:
> https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-mfa-totp/policy/TrustFrameworkExtensions.xml#L209
> 
> This needs to be re-enabled correctly, such that we skip this technical profile if the user already did it once (at Sign In). That would then allow `acquireTokenSilent()` to not get interrupted by an interactive request.

We were expecting the same and thought that is place where the issue is and trying to add the following :  
` <UseTechnicalProfileForSessionManagement ReferenceId="SM-AAD" />`
But in order to make it work, what is the `SSO` type we need to configure. currently its in `Suppressed` (because user closes or try to login he need to come from login)

**Comment by JasSuri** [comment]
Try this

```xml
        <TechnicalProfile Id="AppFactor-Challenge">
          <DisplayName>App Factor</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
            <Item Key="ContentDefinitionReferenceId">api.selfasserted</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="issuer_secret" StorageReferenceId="B2C_1A_TokenSigningKeyContainer" />
          </CryptographicKeys>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="email" />
            <InputClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppSecretKey" />
            <InputClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppTimeStepMatched" />
          </InputClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="strongAuthenticationAppCode" Required="true" />
            <OutputClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppTimeStepMatched" />
          </OutputClaims>
          <ValidationTechnicalProfiles>
            <ValidationTechnicalProfile ReferenceId="AppFactor-VerifyTotpWebHook" />
          </ValidationTechnicalProfiles>
          <!--<UseTechnicalProfileForSessionManagement ReferenceId="SSOSession-PhoneFactor" />-->
        </TechnicalProfile>

**Comment by Webrusterkk** [comment]
> ```
> Tenant
> ```

Do we need to add the same config in[ AppFactor-Register](https://github.com/azure-ad-b2c/samples/blob/5bdc982eb8116f45520411f585d102f8d1af4164/policies/custom-mfa-totp/policy/TrustFrameworkExtensions.xml#L183) and also  in [AAD-WriteUserAppCodeByObjectId](https://github.com/azure-ad-b2c/samples/blob/5bdc982eb8116f45520411f585d102f8d1af4164/policies/custom-mfa-totp/policy/TrustFrameworkExtensions.xml#L141) ?

**Comment by JasSuri** [comment]
You **do not** need to add the same config in `AppFactor-Register` and `AAD-WriteUserAppCodeByObjectId`.
Soon means matter of days potentially. Best to follow that with a support ticket.

**Comment by Webrusterkk** [comment]
@JasSuri  I tried the above approach , but it **didn't worked** , here is my configuration i tried:

**SignUpOrSignIn**

```
      <SingleSignOn Scope="Tenant" />
      <SessionExpiryType>Absolute</SessionExpiryType>
      <SessionExpiryInSeconds>86400</SessionExpiryInSeconds>
```

**TrustFrameworkExtensions**

```
  <TechnicalProfile Id="AppFactor-Challenge">
          <DisplayName>App Factor</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
            <Item Key="ContentDefinitionReferenceId">teststyle</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="issuer_secret" StorageReferenceId="B2C_1A_TokenSigningKeyContainer" />
          </CryptographicKeys>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="email" />
            <InputClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppSecretKey" />
            <InputClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppTimeStepMatched" />
          </InputClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="strongAuthenticationAppCode" Required="true" />
            <OutputClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppTimeStepMatched" />
          </OutputClaims>
          <ValidationTechnicalProfiles>
            <ValidationTechnicalProfile ReferenceId="AppFactor-VerifyTotpWebHook" />
          </ValidationTechnicalProfiles>
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-MFA" />
        </TechnicalProfile>
        <TechnicalProfile Id="SM-MFA">
          <DisplayName>MFA</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <PersistedClaims>
            <PersistedClaim ClaimTypeReferenceId="extension_StrongAuthenticationAppTimeStepMatched" />
          </PersistedClaims>
        </TechnicalProfile>
```

**TrustFrameworkBase**

 ```
 <Item Key="token_lifetime_secs">1200</Item>
  <Item Key="id_token_lifetime_secs">1200</Item>
```

**Comment by JasSuri** [comment]
I updated the sample which should fix SSO (silent token calls in JS apps using Implicit Flows) as per my testing.
