### ISSUE TITLE
Redirect to custom error page from if b2c invitation link expired

### ISSUE THREAD

**Issue by vaibhavrmore1** [azure-ad-b2c/samples#136]
When a user is invited to join the b2c tenant with an invitation link if the user tries to access that link it says that the link is expired as the expiry time is 24 hours.

Upon expiry user sees Microsoft Defined error page where it does not state that the link/ token has expired.

So, wanted to either redirect to a custom error page or display a custom error page with proper messages.

How to show the custom error page in this scenario?

The eg. invitation link is [here](http://url7078.skypointcloud.com/ls/click?upn=I9-2BQ5GOoTvwuGZAHKCtQhTnJrJD4s4jS9qpUNQ7hkDyKksEQ8oaQxwxdX5NJBUEQyHvNZCZ5HiiXcibNCRzxoBZFSzdQBqxx2tjPgJclhRit4O8uRjezPNaLxs5wptQitjVU6UAL9bBaMJD8sATLTtzb-2BXO6vNs0uli70s255x-2BSA9xB-2F2YT6vTd1jBDXARSF0C3DU1r6yVZh4hUucOYfTudd5zGdBafc9XgzBW1Dh3xW6nfL3djqEggxALJgL-2F-2F7TC6pfzrUUL8ej4TMunf90srrmnoN9ipcHd4h-2FHZ2-2FkP3HlRAeh5epwefOWbDyk-2Fc41xWxPxiMvQq2uRAjFg8yXvuhh9WkKAmc56s9HUOngxb6AFKBt0g-2F0R91L4hfucsYg5xOxZk7jI3HgQRFD40fXq4wlFj-2BEJAn0LiegEpUXrLVR6mNqDPZUxT4Io8gyOpqc1vMks9DK9x8hZBL6-2BmSfKYaZxH5EOOsCdFOV-2BvqKy27WBOXN9XaKi4quHtxQRnDoScTZzI29wzsPw-2FMrUZjBt9Bcfp9pdUpAnVU770VNFEVdDZNrg6JqOO0tGugAffRqsIWKwfQSyQYpJlFaKLaYtCVUa5c6-2FK78IQ1qxLzLXD1ijG4GdWjRdeKtUaT72i3W09GimnghVchitTf9eG7pZqcP0qIhKn9f-2F24eenlfCzZMFBlIUJtACfM8hY84aUfmThIz4-2FcpqjwNoYCZ-2BsBVbJjwoP9l1NpOzVN2RgYFI7HU6spSwEwYmt9-2F0qorlpLScMwbdY4C9ufoBrPwe-2Beq2vj2FqbTvfFgCTD6s-2BIneSQX3nuQKivZmhhymGvRHH0uhd3cRLxYm0wuKKbgsaGzIM4lMWK1pqUGknlvFWejWY1Ln7cllwsggUv1kkPJ78yltoRrHzVY6O7TJiC9nNsDbh1emAFJOn72SRjDTfqfz8k-2BmQo5iBAo6NWoIOaY747I13QgApYMrN-2BOQp5SeNKG1CcGtZDYNuU2dthKFtsKabSsq0-2BSujimB5puq3BzyWHeJ9gWiM5J86s9NThU4bwTdfSCJRch7Oy6rOtE5yahLsE2YSWb1-2BJap-2BZUQTXJeSZFEbQPcfc8UXH6oJke-2B-2BggNGeA56EA8MXaIMtKXaMoG6b88G-2BDRaAy1nrPZ5h0grQVMtHncwPelzzp4UQ5kc7vsFYvAec-2Fbir7cjZV-2BfDcpm420bxJKPXHZIjKfvLyx9eTpdv12FpiIumLTfWfiZwj7t1Cya5jjuiMKNPYbjr1-2FLJ1sAlUC0Dd5WtXAoGs8KROWIjkwqIS-2FF9RTFtzE-2FArJ25INKrfldm9Lu80e9Oh0d5VgmrXwDVtjA6WDZfIqAeVhl9sq1iiyDW6-2B9OYxY5nN-2FKeipSqNHPBP2U6SAQ0m-2BNFz5rylmr-2FWs9Vi-2F9sOU5795im2E3Qry3rl0-2BzqRw-3D-3D-Qx0_59ZvMWwGHHs6pW-2B4SIFrU5uLQtMdJ-2FOOGl3KUa1FdSi2RReUH2Z-2FpRZYYftkZoWg1LHw3sm7-2FfgAZiLYQvRXYNAIz0z5GsvLniq-2F98R3qhr4qDANlfYbiINwnrFU-2F-2BOocJ39vtwv0abQQ1sbU24CldU5gBvGq-2BqxKFAMaX6Aj4j3Xi7ao5uW6hK-2FGfWMBpMS8S0poJzYiArjIe8ZDZpX2Q2a2nY3Tz7SrMeT0x8gHZw-3D ).

**Comment by JasSuri** [comment]
client_assertion is deprecated.
Use the new sample that uses id_token_hint instead, that does allow you to handle an expired invite.
https://github.com/azure-ad-b2c/samples/tree/master/policies/invite
