### ISSUE TITLE
Impersonation only works for local accounts

### ISSUE THREAD

**Issue by mrochon** [azure-ad-b2c/samples#137]
The impersonate sample uses signInNames to find the user to be impersonated by their email (in the AAD-AAD-ImpersonatedUserRead technical profile). That will only work for local users. Federated users' email will not be stored in ssignInNames (identities property) - only their anchor/unique id in the federated IdP will be stored. Consequently, a user will not be able to ask to impersonate a federated user - they will get a user not found message after entering their email address.

**Comment by JasSuri** [comment]
There is no way to do it with social as you don’t have a unique identifier for them that can be used by an Admin to locate the account. It’s located by the id that’s sent from the social IdP.

You could write the email into the signInNames collection to resolve this, but then a social account user can no longer use the same email to sign up with a local account.

We can make this clear in the sample.

**Comment by JasSuri** [comment]
Added section:  [Handling users with Social Accounts](https://github.com/azure-ad-b2c/samples/blob/master/policies/impersonation/readme.md#handling-users-with-social-accounts).

**Comment by jrummell-elite** [comment]
I see the updated readme, but how do I do this in the xml?

> If this functionality is not desired, it is possible to write the federated account's email address into signInNames.emailAddress when the account is created using the AAD-UserWriteUsingAlternativeSecurityId technical profile.

**Comment by mrochon** [comment]
Just add <PersistedClaim ClaimTypeReferenceId="email" PartnerClaimType="signInNames.emailAddress" /> to AAD-UserWriteUsingAlternativeSecurityId .

**Comment by jrummell-elite** [comment]
> Just add to AAD-UserWriteUsingAlternativeSecurityId .

.. but how? Which xml file? What xpath? What syntax? Is there some documentation you're aware of that explains this to someone new to custom policies?

**Comment by mrochon** [comment]
Add it to the instance of AAD-UserWriteUsingAlternativeSecurityId that is hierarchically nearest to the RelyingParty. If there is only one, in the TrustFrameworkBase.xml, define a new instance of the same TechnicalProfile in the TrustFrameworkExtensions.xml but remove from it everything else but the <PersistedClaims> element with just this one line:

        <TechnicalProfile Id="AAD-UserWriteUsingAlternativeSecurityId">
          <PersistedClaims>
            <PersistedClaim  ClaimTypeReferenceId="email" PartnerClaimType="signInNames.emailAddress"  />
          </PersistedClaims>
        </TechnicalProfile>

(Sorry, meant to add it to my previous comment).

**Comment by jrummell-elite** [comment]
> Add it to the instance of AAD-UserWriteUsingAlternativeSecurityId that is hierarchically nearest to the RelyingParty. If there is only one, in the TrustFrameworkBase.xml, define a new instance of the same TechnicalProfile in the TrustFrameworkExtensions.xml but remove from it everything else but the element with just this one line:
> 
> ```
>     <TechnicalProfile Id="AAD-UserWriteUsingAlternativeSecurityId">
>       <PersistedClaims>
>         <PersistedClaim  ClaimTypeReferenceId="email" PartnerClaimType="signInNames.emailAddress"  />
>       </PersistedClaims>
>     </TechnicalProfile>
> ```
> 
> (Sorry, meant to add it to my previous comment).

Thank you!
