### ISSUE TITLE
Unified Link Unlink - Twitter not working

### ISSUE THREAD

**Issue by justinasfour04** [azure-ad-b2c/samples#138]
I have updated the Sample for linking and unlinking social media account from the local account and added my consumer key and secret as per https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-twitter-custom?tabs=app-reg-ga. Every time I run the custom policy, I can't seem to get twitter to work.

I keep getting the following error: The call to https://api.twitter.com/oauth/request_token for a request token of enXQGNBsVXWheTvRu0BXPVzcs returned an error Unauthorized

I made sure that he redirect url in twitter is right. I can't figure what may be wrong with the policy that it won't allow me to login with twitter let alone link twitter to my local account.

Can someone please help!!!

**Comment by JasSuri** [comment]
First setup Twitter with the starter pack to eliminate any other issue.
Usually this error is because of a bad secret or you haven’t given the right permissions at Twitter.

**Comment by justinasfour04** [comment]
Which setup should I be following? I followed this one https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-twitter-custom?tabs=app-reg-ga. I have the right secret for Twitter. I've used it before in the B2C user flow for sign in sign up

**Comment by JasSuri** [comment]
User Flow configuration is independent of AAD B2C Custom Policies. My advise stands.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started

https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-twitter-custom?tabs=app-reg-ga

**Comment by justinasfour04** [comment]
@JasSuri I don't know what I did differently but it is working all of a sudden. I had the right consumer key and secret. The redirect url was properly set-up in the developer portal. No idea but all of a sudden things are working
