### ISSUE TITLE
id_token_hint proper usage via App Link missing

### ISSUE THREAD

**Issue by iamalexmang** [azure-ad-b2c/samples#139]
Hi,

In my opinion the 'magic-link' (https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link) sample could really use an enhancement, namely to specify how the resource is secured.

As of right now, the sample specifies how to flow works but even that is incomplete. Namely, after the link is clicked the user is NOT yet authenticated in the application (as the image suggests) - the missing step is in fact the creation of the URL (the authentication URL) which uses a custom endpoint to pull the id_token_hint. This custom endpoint should call the Challenge method using the authenticationproperties and the magic_link_policy as parameters.

**Comment by JasSuri** [comment]
We will get this updated to reflect the correct usage of the id_token_hint via MSAL.

**Comment by JasSuri** [comment]
Updated the readme with section: [Using this in your Production Application](https://github.com/azure-ad-b2c/samples/blob/master/policies/sign-in-with-magic-link/README.md#using-this-in-your-production-application).
