### ISSUE TITLE
User delete via Graph API causes "AADB2C99002 This user does not exist and profile AAD-UserReadUsingObjectId" if you sign in with same user after

### ISSUE THREAD

**Issue by vistpp** [azure-ad-b2c/samples#140]
I create AD B2C local user, then call DELETE /users/{userId} via Graph API successfully.

If I try signing in with same deleted user immediately (within 5-10 minutes) I get the following error.

`AADB2C99002 This user does not exist and profile AAD-UserReadUsingObjectId requires the user to have already been created.`

After ~10 minutes I start getting expected validation message instead of this error. Seems like some cache in AD B2C.

Is there any way to fix this? Maybe I can invalidate this cache manually after deleting user?

**Comment by JasSuri** [comment]
This is a global infra, and you can expect some replication delay. Nothing you can do to change this.
Usually this should only effect for less than a minute.
