### ISSUE TITLE
custom-mfa-totp missing standard app image file  

### ISSUE THREAD

**Issue by todosrc** [azure-ad-b2c/samples#144]
https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-mfa-totp/source-code/AADB2C.MFA.TOTP/wwwroot/selfasserted-appfactor-registration.html

where is the images  ?

https://wingtipb2ctmpls.blob.core.windows.net/wingtiptoys/images/apple-app-store.png
https://wingtipb2ctmpls.blob.core.windows.net/wingtiptoys/images/google-play-store.png
https://wingtipb2ctmpls.blob.core.windows.net/wingtiptoys/images/microsoft-windows-store.png

**Comment by JasSuri** [comment]
Removed the image references.
You can find the images from the respective vendors.
