### ISSUE TITLE
custom-email-verifcation-displaycontrol

### ISSUE THREAD

**Issue by zhouzhou1102** [azure-ad-b2c/samples#145]
DisplayControl_TrustFrameworkExtensions.xml 
B2C_1A_DisplayControl_sendgrid_Extensions where is this strategy

**Comment by BradCandell** [comment]
I'm not sure that I am understanding the question?

Are you referencing this file:
https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-email-verifcation-displaycontrol/policy/SendGrid/DisplayControl_TrustFrameworkExtensions.xml

The policy ID of that file is, `B2C_1A_DisplayControl_sendgrid_Extensions`

**Comment by zhouzhou1102** [comment]
I want to implement SendGrid as a verification mail service for registration and resetting passwords. Can the current three files (DisplayControl_PasswordReset.xml, DisplayControl_SignUpOrSignin.xml, DisplayControl_TrustFrameworkExtensions.xml) be implemented?

**Comment by zhouzhou1102** [comment]
![image](https://user-images.githubusercontent.com/38065901/101109142-23544000-3611-11eb-8fc4-29010276714f.png)

**Comment by zhouzhou1102** [comment]
Thank you for your reply. The analysis found that the TrustFrameworkBase.xml file is missing. The password reset and the verification code sent through SendGrid were successful. An error was reported when the policy was uploaded, registered and logged in.

![image](https://user-images.githubusercontent.com/38065901/101130919-56152d00-363f-11eb-9fdb-f86be945c559.png)

**Comment by zhouzhou1102** [comment]
TrustFrameworkBase.xml：

  
![image](https://user-images.githubusercontent.com/38065901/101131544-6ed21280-3640-11eb-87cc-63b7158c0566.png)

**Comment by JasSuri** [comment]
The pre requisite for all samples is to first follow this guide: https://aka.ms/ief. It shows how to configure login-interactive too. This will provision the starter pack files, then you can use samples in this repo.
