### ISSUE TITLE
Enable/Disable TOTP MFA from target application 

### ISSUE THREAD

**Issue by DerekJDev** [azure-ad-b2c/samples#146]
(My policy is based on the  _TOTP multi-factor authentication_ sample)

Does anyone know of a way to Enable/Disable MFA using the TOTP MFA in the sign in user flow?

In our app, we would like to allow a user to enable or disable 2FA, then when they sign in the would see the 2FA step according to what they set. What is the best way to track if they have 2FA enabled? Would is be to create a custom attribute claim that our API can update? 

Thanks in advance, any insight would be great!

**Comment by JasSuri** [comment]
You could create a profile edit policy and implement if using an attribute to control the logic.

Similar to this:
https://github.com/azure-ad-b2c/samples/blob/master/policies/mfa-email-or-phone

I will close this as it’s not an issue with any sample here. For advice use stackoverflow.
