### ISSUE TITLE
Custom policy login failed

### ISSUE THREAD

**Issue by zhouzhou1102** [azure-ad-b2c/samples#147]
![image](https://user-images.githubusercontent.com/38065901/101427672-45fc9680-393a-11eb-9798-a6ab3fb6afc8.png)

**Comment by zhouzhou1102** [comment]
![image](https://user-images.githubusercontent.com/38065901/101427846-9a077b00-393a-11eb-847b-eb0136b74765.png)

Is it because of permissions? How to configure it? Hope to get help.

**Comment by JasSuri** [comment]
Try the automated setup here
https://github.com/azure-ad-b2c/Scripts/tree/master/IEFTenantSetup

**Comment by zhouzhou1102** [comment]
<ClaimType Id="tenantId">
        <DisplayName>**User's Object's Tenant ID**</DisplayName>
        <DataType>string</DataType>
        <DefaultPartnerClaimTypes>
          <Protocol Name="OAuth2" PartnerClaimType="tid" />
          <Protocol Name="OpenIdConnect" PartnerClaimType="tid" />
          <Protocol Name="SAML2" PartnerClaimType="http://schemas.microsoft.com/identity/claims/tenantid" />
        </DefaultPartnerClaimTypes>
        <UserHelpText>Tenant identifier (ID) of the user object in Azure AD.</UserHelpText>
      </ClaimType>

      <ClaimType Id="objectId">
        <DisplayName>User's Object ID</DisplayName>
        <DataType>string</DataType>
        <DefaultPartnerClaimTypes>
          <Protocol Name="OAuth2" PartnerClaimType="oid" />
          <Protocol Name="OpenIdConnect" PartnerClaimType="oid" />
          <Protocol Name="SAML2" PartnerClaimType="http://schemas.microsoft.com/identity/claims/objectidentifier" />
        </DefaultPartnerClaimTypes>
        <UserHelpText>Object identifier (ID) of the user object in Azure AD.</UserHelpText>
      </ClaimType>

**Comment by zhouzhou1102** [comment]
<ClaimType Id="objectId">
        <DisplayName>User's Object ID</DisplayName>
        <DataType>string</DataType>
        <DefaultPartnerClaimTypes>
          <Protocol Name="OAuth2" PartnerClaimType="oid" />
          <Protocol Name="OpenIdConnect" PartnerClaimType="oid" />
          <Protocol Name="SAML2" PartnerClaimType="http://schemas.microsoft.com/identity/claims/objectidentifier" />
        </DefaultPartnerClaimTypes>
        <UserHelpText>Object identifier (ID) of the user object in Azure AD.</UserHelpText>
      </ClaimType>


User's Object ID  --- What is meant？

**Comment by JasSuri** [comment]
This doesn’t appear to be an issue with a sample from this repo so I will close this. For general help, use stackoverflow.
