### ISSUE TITLE
Independent Local account signup link on api.selfasserted page

### ISSUE THREAD

**Issue by Sharatmenon** [azure-ad-b2c/samples#148]
Hi @JasSuri 

I am using this [sample ](https://github.com/azure-ad-b2c/samples/tree/master/policies/default-home-realm-discovery)to allow users to login using Azure AD or else get redirected to the local account login. 

My client currently requires a local account signup link on the api.selfasserted page where we accept only the email address for looking up the domain hint. How can I achieve this ? 

Secondly we need that signup link to work independently as well so that it can be shared to invite signups.

Thanks!
Sharat

**Comment by JasSuri** [comment]
Two options 
1. Use a combinedSignInAndSighUp step, and use JavaScript to enter a dummy password to satisfy the form. Use CSS to hide the password field.

2. Create a separate sign up journey and put a link in your custom html to myapp.com/signup which will send the user to the sign up policy.

**Comment by JasSuri** [comment]
Closing - general help/design questions should go via stackoverflow.
