### ISSUE TITLE
Issues with signup-signin-with-phone-number

### ISSUE THREAD

**Issue by rbrayb** [azure-ad-b2c/samples#15]
You need to use the SocialAndLocalAccountsWithMfa starter pack not the SocialAndLocalAccounts as per the Readme.

There is a missing:

ClaimsProviders
		**ClaimsProvider**

in the xml.

When you run the sample, when it asks "Enter user name", you need to enter the phone number.

**Comment by JasSuri** [comment]
Fixed all 3, thanks.
