### ISSUE TITLE
Unable to find Policy user_info

### ISSUE THREAD

**Issue by vaaridra** [azure-ad-b2c/samples#152]
Hi,
I am unable to find the following policy code:
https://github.com/azure-ad-b2c/samples/tree/master/policies/user_info

It was really helpful to fetch user info while using OIDC with Azure B2C.

Please help me with the details. Is the code restructured into a different directory or is there a new alternative to achieve the same solution?

**Comment by JasSuri** [comment]
This is about to go public preview, should hit public docs over at https://aka.ms/ief very soon.

**Comment by vaaridra** [comment]
Hey JasSuri, thanks for the update. Couldn't reply earlier. Will try this and let you know if I face any further issues.

One quick question. Can I use this along with standard email sing-up sing-in user flow. Right now I am using email and google login. I just need to fix the issue with loading user info when authenticating through oidc-client library. (https://github.com/perarnborg/vuex-oidc)

**Comment by JasSuri** [comment]
I don’t think that will work as it uses a different signing key.
