### ISSUE TITLE
Localized Resources Encoding

### ISSUE THREAD

**Issue by gitlebreton** [azure-ad-b2c/samples#153]
Hello
I updated my policy to add custom email check verification
following this documentation [Custom email verification with SendGrid](https://docs.microsoft.com/fr-fr/azure/active-directory-b2c/custom-email-sendgrid)

I encountered an encoding issue with some of my LocalizedString

`<LocalizedResources Id="api.custom-email.fr">
        <LocalizedStrings>
          
          
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="intro_msg">Une vérification est nécessaire. Merci de cliquer sur le bouton Envoyer.</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="success_send_code_msg">**Un code de vérification vous a été envoyé. Merci de le copier dans le champ ci dessous.**</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="failure_send_code_msg">Nous ne parvenons  pas à vérifier votre email. Merci de saisir une adresse email valide et d'essayer à nouveau.</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="success_verify_code_msg">E-mail vérifié. Vous pouvez poursuivre.</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="failure_verify_code_msg">Nous ne parvenons  pas à vérifier votre email. Merci d'essayer à nouveau.</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="but_send_code">Envoyer un code de vérification</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="but_verify_code">Vérifier le code</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="but_send_new_code">Envoyer un nouveau code</LocalizedString>
          <LocalizedString ElementType="DisplayControl" ElementId="emailVerificationControl" StringId="but_change_claims">Modifier l'e-mail</LocalizedString>
          
          <LocalizedString ElementType="ClaimType" ElementId="emailVerificationCode" StringId="DisplayName">**Code de vérification**</LocalizedString>
          <LocalizedString ElementType="ClaimType" ElementId="emailVerificationCode" StringId="UserHelpText">Code de vérification reçu par email.</LocalizedString>
          <LocalizedString ElementType="ClaimType" ElementId="emailVerificationCode" StringId="AdminHelpText">Code de vérification reçu par email.</LocalizedString>
          <LocalizedString ElementType="ClaimType" ElementId="email" StringId="DisplayName">Email</LocalizedString>
          
          <LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfSessionDoesNotExist">Vous avez dépassé le temps imparti.</LocalizedString>
          <LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfMaxRetryAttempted">Vous avez dépassé le nombre d'essais autorisés.</LocalizedString>
          <LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfInvalidCode">Vous avez saisi un code incorrect.</LocalizedString>
          <LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfSessionConflict">Impossible de vérifier le code, merci d'essayer plus tard.</LocalizedString>
          <LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfVerificationFailedRetryAllowed">La vérification a échoué, merci d'essayer à nouveau.</LocalizedString>
        </LocalizedStrings>
      </LocalizedResources>`

![image](https://user-images.githubusercontent.com/52410404/102515430-0e09f780-408e-11eb-8719-db9794db50c1.png)

As seen on picture

LocalizedString for **success_send_code_msg** do not handle é charactere 
whereas same character is correctly handled for LocalizedString ElementId="**emailVerificationCode**" StringId="DisplayName"

Is that an issue or do I missed something

Thanks

**Comment by JasSuri** [comment]
I suggest you open a support ticket for this issue, it is not sample specific issue, but more a general issue with the localisation.
