### ISSUE TITLE
Replace id_token in the Reply URL for Zendesk

### ISSUE THREAD

**Issue by ravitol** [azure-ad-b2c/samples#155]
Hello folks

I am enabling SSO with Zendesk and our Azure AD B2C Authorization server which has custom sign-up and sign-in policies.  On zendesk configuration, I can add the authorization service endpoint that prompts the user with the login information.  After the login, the service expects the access token in the following format. 

https://your-subdmain.zendesk.com/access/jwt?jwt={payload} 

I have added the response_mode=query which adds id_token={payload} to the redirect_uri.    How do I change the parameter id_token to jwt ?

Also, in order to integrate with zendesk, I have changed the signing container to HS256 instead of RSA256.   Zendesk provides the signing key for the JWT token and would like to understand which Technical profile would need to be updated to append the signature to the JWT token so it can be validated by the service,.

Thanks for your support in advance.

Regards

**Comment by JasSuri** [comment]
This needs to be posted on stackoverflow, it is not an issue with any sample here that we support.

Both of these things (payload format and HS256), is not something I’ve seen used before with AAD B2C. You might have better compatibility with SAML integration.
