### ISSUE TITLE
password-reset-with-Username-SMSVerify Not working

### ISSUE THREAD

**Issue by Jimish-Shah24** [azure-ad-b2c/samples#162]
I have tried to implement it, though I am having the user with given name and number, its till gives an error saying user or phone number does not exist.

**Comment by JasSuri** [comment]
The journey doesnt include a sign up via username and MFA enrollment.

Have you tried setting up a User Flow with Username based local account identity provider with MFA enabled - then signing up an account through it first?

**Comment by Jimish-Shah24** [comment]
@JasSuri  I am not getting you, Do I need to create User flow as well ? As I am implementing this custom policy to reset the password through phone number, which is not possible through User Flow. I am stuck with below issues here..
1. I got to know if will enter phone number in Authentication method then it will work for me, but I cant see that options for my user, how do I enable that?
![image](https://user-images.githubusercontent.com/77672132/105166873-fa92f600-5b3d-11eb-9280-aa751c594e2e.png)
![image](https://user-images.githubusercontent.com/77672132/105166899-04b4f480-5b3e-11eb-9009-05add5424f80.png)
2. After resetting the password, it's not redirecting me to the sign in page.
3. Back button is not working it gives me an error.

**Comment by JasSuri** [comment]
1. This means your User Flow is not enabled for MFA, and didnt sign up the user using MFA.
2. That is not supported. 
3. That is not supported.

**Comment by Jimish-Shah24** [comment]
@JasSuri Thanks so much for your valuable inputs, the policy is working perfectly by implementing it the way you have described.
 Please address below two concerns if possible,
1. In the second question, the problem is you have suggested force password reset on first logon. But I want that using this 
    policy once user successfully reset the password it should redirect him to the sign in page is it possible?
2. I wanted to customize the label highlighted below, is it possible ? How to customize the label like this for custom policy as well 
    as user flows? 
   ![image](https://user-images.githubusercontent.com/77672132/105351344-73fc1880-5c12-11eb-9cee-5651ab71f6f1.png)

**Comment by JasSuri** [comment]
1. No, you are always logged in once a journey completes. You can log the user out the application if it detects the PolicyId to be from the password reset journey.
2. https://docs.microsoft.com/en-us/azure/active-directory-b2c/localization, https://docs.microsoft.com/en-us/azure/active-directory-b2c/localization-string-ids

Since there is no issue with the sample itself, i will close this.
Please take miscellaneous questions to stackoverflow and user the azure-ad-b2c tag.
