### ISSUE TITLE
How to implement magic link which can be used only once? 

### ISSUE THREAD

**Issue by iamkarlson** [azure-ad-b2c/samples#163]
Hello,
We have a sign-in flow when users getting navigated to B2C from the email. As an example of such flow I was using this [policies](https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link).  For some reasons, we cannot allow users to use the same link more than once. In the example above link is expired in minutes which we can't make in our flow. The link should live long enough that users can be back in several days and still able to log in. Currently, magic link is implemented via id_token_hint and it would be great just to revoke these jwt tokens. However, it doesn't seem to be feasible. I do realize that the JWT is not revokable by standard but I'm open to hear any suggestions on how to do that. 

What would be the best way to implement such scenario: magic link which lives long enough (~3d) but can be used only once?

**Comment by JasSuri** [comment]
You would need to make the flow stateful. For example, in the id_token_hint JWT issue a claim like `id:GUID`. Your API needs to then store this GUID. 

When you build the id_token_hint redemption journey, step 1 should parse the claims in the JWT. 
Step 2 should send the `id:GUID` to the API for the API to return whether it has been used or not. If it hasn't been used, it needs to now mark it as used, or right before the last step, make an API request to mark it as used.
If it has been used, direct the user to a selfasserted page showing an error message.

You can see how to integrate API calls in the journey [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-rest-api-claims-validation).

You could use the B2C directory store (user attributes) to hold this state, but this is not the intended purpose of the attribute store.

Better to move this question to stackvoverflow as its not a specific issue/bug with the sample.

**Comment by HMoen** [comment]
@JasSuri, would it go against the standard to capture the id_token at the client app level which generated the id_token_hint (perform GET on the link with redirect back to the app) and send the id_token received from the redirect to the user via email instead of sending the user an email with the id_token_hint? (which seems to be an irrevocable id_token generator)
