### ISSUE TITLE
emailVerificationSSPRControl isn't rendering intro_msg

### ISSUE THREAD

**Issue by jpalo** [azure-ad-b2c/samples#164]
With regards to: https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-email-verifcation-displaycontrol/policy/SendGrid/DisplayControl_TrustFrameworkExtensions.xml

For some reason Azure B2C `emailVerificationSSPRControl` isn't rendering the `intro_message` text, but only shows empty green box. Additional UI texts after submitting email display correctly. In fact, even if I don't define any LocalizedString values, it is also empty as if the control would be missing that definition. Is there something that could be done to the issue?

intro_message in first line is not shown, but the success_send_code_msg works: 
![image](https://user-images.githubusercontent.com/6917905/105351920-e4487100-5bf5-11eb-8883-916c01fd5028.png)

intro_message empty:
![image](https://user-images.githubusercontent.com/6917905/105351935-e90d2500-5bf5-11eb-84e8-9703219379bf.png)

success_send_code_msg shows correctly:
![image](https://user-images.githubusercontent.com/6917905/105351967-f32f2380-5bf5-11eb-8d34-6ad924a06cd7.png)

(NOTE! Also asked in StackOverflow as I'm not sure at all what might be causing this: https://stackoverflow.com/questions/65827319/emailverificationssprcontrol-isnt-rendering-intro-msg)

**Comment by JasSuri** [comment]
Closing and will help at SO.
