### ISSUE TITLE
Do we need to fill something into ConditionalAccessPoliciesToEvaluate?

### ISSUE THREAD

**Issue by katz** [azure-ad-b2c/samples#167]
In conditional access policy sample, there's `ConditionalAccessPoliciesToEvaluate` metadata but it's commented out.
In order for conditional access evaluation to work properly, do we need to fill something in the metadata?

https://github.com/azure-ad-b2c/samples/blob/5e33a4d2ae6b35fdfb6ee9c7fda866f1cfc49c5f/policies/conditional-access/policy/TrustFrameworkExtensions.xml#L204-L210

**Comment by JasSuri** [comment]
Not needed.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/conditional-access-technical-profile#conditional-access-evaluation

“ For every sign-in, Azure AD B2C evaluates all policies and ensures all requirements are met before granting the user access.”
