### ISSUE TITLE
The username or password provided in the request are invalid.

### ISSUE THREAD

**Issue by Jimish-Shah24** [azure-ad-b2c/samples#173]
I am using below custom policy, but when I am trying to login with username and password it gives me an error saying "The username or password provided in the request are invalid". Though, I am able to login with same user using user flow.

Policy: https://github.com/azure-ad-b2c/samples/tree/master/policies/force-password-reset-first-logon

**Comment by JasSuri** [comment]
Incorrect setup of the starter pack.
Deploy using my tool https://aka.ms/iefsetup

**Comment by JasSuri** [comment]
You might have `login-noninteractive` technical profile redefined in another file with incorrect resource and clientid values.
The problem is always to do with incorrect config of `login-noninteractive` technical profile.
