### ISSUE TITLE
Unable to connect to the metadata endpoint

### ISSUE THREAD

**Issue by v-alingaraj-ignitec** [azure-ad-b2c/samples#178]
Endpoint configured successfully and able to access publicly but yet the B2C Login Flow complain
Error Shown Below:
-----------------
Sorry, but we're having trouble signing you in.
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, please try again.
Correlation ID: 2dcaacd5-d3a0-41c5-aa14-0308a2bf94f0
Timestamp: 2021-03-01 02:58:21Z
AADB2C: Unable to connect to the metadata endpoint 'https://redacted-url/signinwithapple/.well-known/openid-configuration'

**Comment by v-alingaraj-ignitec** [comment]
https://web-api.demo.ignitecinc.com/signinwithapple/.well-known/openid-configuration

**Comment by JasSuri** [comment]
B2C only supports metadata endpoints secured with a certificate from a valid CA.

**Comment by v-alingaraj-ignitec** [comment]
Tried with Azure Blob Containers with MS Certificates and failed with same error.

**Comment by JasSuri** [comment]
What is the Certificate Authority?

**Comment by dkrasnove** [comment]
Also experiencing this issue when B2C attempts to access the metadata endpoint of an AD FS IdP.

Additional info from app insights: "The request was aborted: Could not create SSL/TLS secure channel."

**Comment by JasSuri** [comment]
You need to secure the endpoint with a cert. And that cert needs to be from a CA that Microsoft trusts

**Comment by dkrasnove** [comment]
@JasSuri The endpoint is secured by the DigiCert SHA2 Secure Server CA.
