### ISSUE TITLE
Passwordless email seems to have a security flaw

### ISSUE THREAD

**Issue by Ponant** [azure-ad-b2c/samples#182]
Comment in the reference to `CreateRandomPassword` here https://github.com/azure-ad-b2c/samples/blob/fe0f24b7aa6b0b3169151777cc77a86253f185bc/policies/passwordless-email/policy/TrustFrameworkExtensions_passwordless_only.xml#L87

and the code still runs on signup for a new user. The issue persists if the `CreateRandomPassword` transformation is completely removed as it is used only once in the link above.

Hence it is not clear what the Engine is doing with the password, which one is created, if any?

I would appreciate an answer as I am implementing pwdless signin/signup and still did not find a proper way to make sure a rnd password has been created. I am trying to output newPassword in the jwt (for testing!), without success so far.

**Comment by JasSuri** [comment]
You can’t output the password claim into any subsequent orchestration step from which it was initialised. So you definitely can’t see it in the token.

the sample generates a random password and writes it to the user. What is your question specifically?

**Comment by Ponant** [comment]
You answered my question. Thank you.
