### ISSUE TITLE
'Cancel' button on embedded password reset flow doesn't return user to sign-in

### ISSUE THREAD

**Issue by rugglcon** [azure-ad-b2c/samples#183]
When a user enters the password reset flow using the embedded reset sample, and they click the 'Cancel' button, it sends an error code to the redirect URL and not back to the sign-in page. What changes are needed to make this happen? The only thing I am finding from Googling is to have the backend application handle that code, but that is not a feasible option for us.

**Comment by JasSuri** [comment]
The only workaround would be to replace the cancel button with a button to https://myapp/signin.

Soon we are bringing a more built in flow which will have better support.

**Comment by rugglcon** [comment]
Can you be more specific on "soon" and "more built in flow"? That would be very nice.

**Comment by JasSuri** [comment]
Essentially this sample, without the requirement of javascript etc. Rather its configured in the policy itself, similar to how Sign Up works. I am not aware whether the "cancel" button during password reset will send you back to Sign In, this may still need the workaround I mentioned. 

Likely the public docs will go up within a couple of weeks.

**Comment by rugglcon** [comment]
Okay, thank you.

Different question: on successful password reset, the user state is not preserved and the application does not redirect correctly. How would I go about preserving the current state when I am redirected to the forgot password flow?

**Comment by JasSuri** [comment]
We released the new doc:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy#self-service-password-reset-recommended

I'm not completely following your question, but you can store the "state" in the state parameter as part of the OIDC request to AAD B2C. This is then returned back to your application such that it can send the user to where they left off. You may want to move this question to stackoverflow.
