### ISSUE TITLE
CAPTCHA-INTEGRATION sample - broken link

### ISSUE THREAD

**Issue by felickz** [azure-ad-b2c/samples#187]
https://github.com/azure-ad-b2c/samples/tree/master/policies/captcha-integration

> Test a live version of this policy [here](https://b2cprod.b2clogin.com/b2cprod.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_Captcha_signin&client_id=51d907f8-db14-4460-a1fd-27eaeb2a74da&nonce=defaultNonce&redirect_uri=https://jwt.ms&scope=openid&response_type=id_token&prompt=login).

**Comment by JasSuri** [comment]
Fixed.

**Comment by felickz** [comment]
@JasSuri - which HTML template did you start with on the captcha integration - would be nice to see a diff of before/after. (you only have one checkin so cant check out source control)

**Comment by JasSuri** [comment]
It uses the selfAsserted page. You can deduce this from the dataURI of the api.selfAsserted content definition which step 1 of the journey uses.
