### ISSUE TITLE
Username/Email Enumeration on sign In page

### ISSUE THREAD

**Issue by kberawala** [azure-ad-b2c/samples#188]
Valid usernames can be enumerated due to different error messages for username and password when logging in.

1. Type in an invalid email address and observe the error message to be ‘We can’t seem to find your account’.
2. Type in a valid email address but an incorrect password, and observe the error message to be ‘Your password is incorrect’.

when the combination of username/password is incorrect, show a message like "Invalid Username/Password."

**Comment by JasSuri** [comment]
It’s configurable. We make it as such so as a developer you know why you’re having trouble to begin with.

**Comment by Nautigsam** [comment]
It is wrong to say it can be configured as @JasSuri said. The server sends an error code with the message, and that can't be changed.
Language customization gives you a false sense of security, while the vulnerability is still there.
