### ISSUE TITLE
Blank claims provider selection - embedded password reset

### ISSUE THREAD

**Issue by judedaryl** [azure-ad-b2c/samples#190]
Embedded password reset doesn't work well on local sign ins that don't have other sign in options. In the example it was built with a facebook exchange.

In my use-case, i only have a local signin and password reset.

```xml
       <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.unified.emailsignin">
            <ClaimsProviderSelections>
                <ClaimsProviderSelection TargetClaimsExchangeId="ForgotPasswordExchange" />
                <ClaimsProviderSelection ValidationClaimsExchangeId="SignIn" />
            </ClaimsProviderSelections>
            <ClaimsExchanges>
                <ClaimsExchange Id="SignIn" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
            </ClaimsExchanges>
        </OrchestrationStep>
```

<img width="610" alt="Screen Shot 2021-03-12 at 6 45 56 PM" src="https://user-images.githubusercontent.com/13645031/110929694-30e13a80-8363-11eb-821a-8d7bc0742ed8.png">

**Comment by JasSuri** [comment]
All targetClaimsExchanges are considered “external IdPs”, hence the addition of the heading. You can use CSS to hide it. It’s not an issue with the sample itself, so I will close this as this is expected for now.
