### ISSUE TITLE
B2C- Log out user after "change sign in name" custom policy is run

### ISSUE THREAD

**Issue by Sharatmenon** [azure-ad-b2c/samples#194]
Hi @JasSuri , @yoelhor 

I am using the below policy to change email address/ sign in name for a logged in user. Everything works fine. I just need to be able to sign out the user after the email change is complete. I would like the user to login with the new email address.

[Change Sign in Name](https://github.com/azure-ad-b2c/samples/tree/master/policies/change-sign-in-name/policy )

Is there a log out step or something that can be added to the user journey ? 

Our application is a SPA in react that is using OAuth PCKE flow.

FYI. I have created a support ticket with Microsoft for this and no solution so far. Any help will be appreciated.

Thanks!
Sharat

**Comment by JasSuri** [comment]
The best place for design help is stackoverflow. You cannot use a policy step to logout the user.

Detect the `tfp` claim in the token which tells your soo from which policy the user logged in via, and then issue a logout call.

Since this is not an issue with any policy here, I’ll close this.
