### ISSUE TITLE
custom-mfa-totp

### ISSUE THREAD

**Issue by ruitomexpand** [azure-ad-b2c/samples#196]
Hi, I am trying to set up TOTP MFA and I have followed this guide https://medium.com/@snkaushi_9371/enable-totp-based-multi-factor-authentication-in-azure-ad-b2c-84e967d76aa4

This guide is based on the sample provided here https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp

I followed all the steps but I've been getting the following exception:

`Exception Message:Output claim type "alternativeSecurityId" specified in the technical profile with id "SelfAsserted-LocalAccountSignin-Email" in policy "B2C_1A_signup_signin" of tenant "xxx.onmicrosoft.com" does not specify a UserInputType or a DefaultValue, and is not retrieved from a ValidationTechnicalProfile either., Exception Type:InvalidDefinitionException`

Is there an updated guide I can follow?

Thanks in advance

**Comment by JasSuri** [comment]
There shouldn’t be any scenario where that claim is output in that technical profile. Delete the output claim and see if it works. Our policy sample doesn’t make such a change either.
