### ISSUE TITLE
Pass API key in header

### ISSUE THREAD

**Issue by josh-authy** [azure-ad-b2c/samples#2]
Instead of passing the API key in the URL, like this:
$"https://api.authy.com/protected/json/users/new?api_key={AppSettings.Key}";

You should pass it in the header.  See here:
https://github.com/AuthySE/Authy-API-Samples/blob/master/sendSMS.bat#L11
 -H "X-Authy-API-Key: %AUTHY_API_KEY%"

**Comment by chadhasbrook** [comment]
@josh-authy  can you be specific on which sample(s) you are referencing? Thanks!

**Comment by josh-authy** [comment]
All of those cURL samples show how to pass the API key in the header.

Here is an example in C# of how to past it in via the header.
https://github.com/TwilioDevEd/account-security-csharp/blob/a84ea97a3c45687419bcef8d81fe4f0975a7a5b4/src/AccountSecurity/Services/Authy.cs#L48

If it's passed in via a query param, it is very likely your API key will end up in logs.... which isn't good.

**Comment by josh-authy** [comment]
@chadhasbrook 
Oof.  That isn't what you were asking.

Here you go:
https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-mfa-authy-app/source-code/AADB2C.MFA.AuthyApp/Controllers/IdentityController.cs#L83

**Comment by jasjeetsuri** [comment]
Thanks @josh-authy, we shall update the sample to pass the key in the header instead.

**Comment by jasjeetsuri** [comment]
Added headers to pass api key in identityController.cs
