### ISSUE TITLE
Email MFA is not showing in Social login

### ISSUE THREAD

**Issue by 1992-rd** [azure-ad-b2c/samples#202]
For Social login (Google/Facebook) when we are trying to use the Email MFA. The Email address is not populating in the Email field . 

Please find the below screenshot.
<img width="384" alt="Google-Email_MFA_Signin" src="https://user-images.githubusercontent.com/81624775/112983889-d37b2500-917b-11eb-9a94-fc5455768b7a.PNG">

Can you please help me on this.

**Comment by JasSuri** [comment]
Can you link to what sample you’re using?

**Comment by 1992-rd** [comment]
Please find below sample we are using,

https://github.com/azure-ad-b2c/samples/tree/master/policies/idps-filter/policy .

**Comment by JasSuri** [comment]
You need to capture the email from the social IdP technical profile using an output claim and then send this claim as an input claim to the technical profile that shows the email verification. 

Use the app insights to view the claim bag to understand what’s happening.

As there is no issue with the sample itself, I will close this and better to seek help on stackoverflow for design questions.
