### ISSUE TITLE
Custom policy: An exception has occurred

### ISSUE THREAD

**Issue by emaborsa** [azure-ad-b2c/samples#203]
I am trying to create a user flow using custom policies. I followed [this](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp) sample. Testing the _SignUpSignIn_ with _https://jwt.ms_ I get the following error:

![susi_error](https://user-images.githubusercontent.com/9129912/113163716-b3fa0000-9240-11eb-8884-41fbd6644e43.png)

Error: server_error
AADB2C: An exception has occurred.
Correlation ID: b4d4bbf6-a75b-42dd-bd26-2c7a53e08487
Timestamp: 2021-03-31 14:36:56Z

Here is my policy:
[customPolicy.zip](https://github.com/azure-ad-b2c/samples/files/6237458/customPolicy.zip)

I set up an application insights, in the logs I find followings, but dont know what it means:
_Output claim type \"alternativeSecurityId\" specified in the technical profile with id \"SelfAsserted-LocalAccountSignin-Email\" in policy \"B2C_1A_MFA_susi\" of tenant \"hgvit.onmicrosoft.com\" does not specify a UserInputType or a DefaultValue, and is not retrieved from a ValidationTechnicalProfile either._

**Comment by JasSuri** [comment]
I’m not sure where this line came from, it’s not part of the sample, but remove it from SelfAsserted-LocalAccountSignin-Email technical profile.

<OutputClaim ClaimTypeReferenceId="alternativeSecurityId" />

**Comment by emaborsa** [comment]
For sure I added it...but I thought it was necessary and was trying to fix it addin other stuff.
Actually, removing it works.
Thanks!

**Comment by emaborsa** [comment]
The SignIn works, but the SignUp doesn't. It complains because of the missing _alternativeSecurityId_:

`Claim type "alternativeSecurityId" is the input claim of technical profile "AAD-UserReadUsingAlternativeSecurityId" in step "3" of user journey "ProfileEdit" but it is not an output claim in any of the previous steps.`

**Comment by JasSuri** [comment]
The step `AAD-UserReadUsingAlternativeSecurityId` is for Social Account logins. If you dont have a Social IdP configured, then this step will never have an AltSecId to operate on. AlSecIds are only issued as an output claim of a Social IdP technical profile.

You likely dont have any Social idP configured, so need to get rid of the steps referencing AltSecId (read +write).

**Comment by emaborsa** [comment]
Actually, I took the _SocialAndLocalAccountsWithMfa_ sample and tried to remove the social part.
Now I recreated the policy by taking the _LocalAccounts_ sample and adding mfa stuff, seems to work.
Thanks for the hint!
