### ISSUE TITLE
Username Format

### ISSUE THREAD

**Issue by Sesh360** [azure-ad-b2c/samples#204]
I'm trying to understand valid username formats.

This document is mentioned:
[https://tools.ietf.org/html/rfc3696#section-3](https://tools.ietf.org/html/rfc3696#section-3)

Via this documentation for valid usernames, issuerAssignedId must be a valid local part of an email address:
[(https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-profile-attributes)](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-profile-attributes)

I need to be able to store usernames in different forms, such as !!@@##, etc.

I have a modified version of the susi with username or email. It works fine with usernames in more common formats such as joe123 or emails such as joe123@live.com, etc.

Is there any way to be able to store these usernames, possibly by escaping within the custom policy? Or would this have to be a graph call?

**Comment by JasSuri** [comment]
Instead of `signInNames.username`, use `signInNames.myCustomThing`. That should bypass all restrictions.

**Comment by Sesh360** [comment]
> Instead of `signInNames.username`, use `signInNames.myCustomThing`. That should bypass all restrictions.

That makes sense, looking at it now and I see that it can be any type you would like.

I’m assuming read/write would have to be changed to rely on this custom type or by objectid.

I will try it. Thank you.

**Comment by Sesh360** [comment]
This will resolve my issue.

Thanks again for the help.
