### ISSUE TITLE
Mitigating scenario where claim from external IdP can be either string or stringCollection

### ISSUE THREAD

**Issue by dkrasnove** [azure-ad-b2c/samples#206]
We have to federate with several external IdPs (using industry-standard solutions such as AD FS, F5, etc) which issue group claims.

When a user has multiple groups, these IdPs issue a response with the claim in the following format:

```json
"groups": ["Domain Users", "US Users", "Administrators"]
```

But when a user has only a single group:

```json
"groups": "Domain Users"
```

Here is the b2cGroups ClaimType as defined in TrustFrameworkExtensions:

```xml    
<ClaimType Id="b2cGroups">
    <DisplayName>Groups</DisplayName>
    <DataType>stringCollection</DataType>
    <AdminHelpText>User's groups.</AdminHelpText>
</ClaimType>
```

And the OutputClaim in the external IdP TechnicalProfile:

```xml
<OutputClaim ClaimTypeReferenceId="b2cGroups" PartnerClaimType="groups" />
```

In the current configuration, B2C throws a fatal exception when a user has only a single group:

    The data type 'String' of the claim with id 'groups' does not match the DataType 'StringCollection' of ClaimType with id 'b2cGroups' specified in the policy.

I can alter the claim definition from stringCollection to string:

```xml
<ClaimType Id="b2cGroups">
    <DisplayName>Groups</DisplayName>
    <DataType>string</DataType>
    <AdminHelpText>User's groups.</AdminHelpText>
</ClaimType>
```

But now when a user has multiple groups:

    The data type 'StringCollection' of the claim with id 'groups' does not match the DataType 'String' of ClaimType with id 'b2cGroups' specified in the policy.

The exception happens during execution of the OIDC or SAML2 technical profile itself, so I can't use a claims transformation to manipulate the data. It seems B2C has no leniency for this potential inconsistency in data types, which is right in theory, but in practice, the major federated identity solutions (such as AD FS, which is also a MS product) don't adhere to this standard.

This has become a major issue that, left unresolved, will force us to tear up our existing B2C infrastructure and migrate to another CIAM solution. Is there a fix, or hack that I can apply to mitigate this issue?

**Comment by JasSuri** [comment]
The only workaround would be to not return the claim in the IdP technical profile, instead call an API in a subsequent step and have it fetch the value from the IdP and always return an array back to B2C.

**Comment by JasSuri** [comment]
Closing as duplicated on stackoverflow.

**Comment by Vincentvdc** [comment]
Even though I know this issue is closed I want to make it known that I too suffer from this problem. We cannot call an API since we are trying to interface with our clients' AD FS idp.

**Comment by dkrasnove** [comment]
@Vincentvdc I recommend submitting a ticket directly to Microsoft. We did that and they classified it as a bug but gave no timeline for a fix.

**Comment by CodyMorris** [comment]
Any updates on this?

**Comment by dkrasnove** [comment]
@CodyMorris MS never provided a solution so we had to ask the client to ensure all users had at least two group in AD FS.
