### ISSUE TITLE
Deploy to Azure does not work 

### ISSUE THREAD

**Issue by chetansk** [azure-ad-b2c/samples#207]
Hi,

I tried the Deploy-to-Azure on the page https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp. 

When I click on deploy, I get an error

This site can’t be reached
deploy.azure.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

I am trying this on a Linux host using chrome browser. I have an azure account and already deployed an azure service (application insights) on this account, so no issue with the account.

Thanks
C

**Comment by cljung** [comment]
deploy.azure.com has been retired, so until we've updated the sample, you have to deploy the backend code manually
