### ISSUE TITLE
Reset QR Code

### ISSUE THREAD

**Issue by emaborsa** [azure-ad-b2c/samples#209]
I have implemented the mfa access for my b2c tenant using [this sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp). But what if I lose my phone or delete the Authenticator app? How do I recover the access to my account? I'd need a sort of QR reset flow. Is there something among the samples? I took a look but did not find any.

**Comment by JasSuri** [comment]
This is a design question, and it depends what you want a recovery flow to look like. I suggest you come up with your requirements and ask on stackoverflow for help to implement it if needed. You can build any flow you like with custom policy.
