### ISSUE TITLE
Javascript errors running mfa-totp-sample

### ISSUE THREAD

**Issue by emaborsa** [azure-ad-b2c/samples#211]
I have implemented [this sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp). It is working but in the console (browser) I get some errors:
![js_errors](https://user-images.githubusercontent.com/9129912/114066653-3f583e80-989c-11eb-9808-e9966477373e.png)

Did I something wrong? I checked the appId d8d326b2-a4bc-4c47-9791-371fd1104c39 from the log, I don't have that app registered in my tenant.

**Comment by JasSuri** [comment]
These look like errors from the AAD B2C service delivered JS. Logger.ts is not part of the sample.

**Comment by emaborsa** [comment]
OK, what does it mean for me/us?

**Comment by JasSuri** [comment]
You should raise a MS Support ticket for this as a service issue to get an answer on this one.
