### ISSUE TITLE
Account linkage: Prompted for username twice

### ISSUE THREAD

**Issue by karrocon** [azure-ad-b2c/samples#212]
Here is my use case:
1. I'm inviting a new user to our directory following the id_token_hint invite example (sending an email with SendGrid).
2. The user clicks on the register link and is prompted to create a local account in the directory with some basic data (Display Name, First Name, etc.).
3. After creating the local account the user can sign in using local account credentials (email + password)
4. I also want to provide social account integration following the AccountLinkage example but when the user tries to log in using his Microsoft account (which has the same @hotmail.com email as the local account) it is asked to fill his personal information once more (Display Name, First Name, etc.).

Am I missing something?

**Comment by JasSuri** [comment]
Sounds like you need to adjust the logic for your needs so if an account link process is occurring, it skips the selfasserted-social step. Better to ask on stackoverflowsjowing your logic and xml governing that process.
