### ISSUE TITLE
Signup Sign in using Username

### ISSUE THREAD

**Issue by tokenDeveloper2020** [azure-ad-b2c/samples#213]
I was trying to use "Signup Sign in using Username" custom policy. But after registration/sign in I am getting not emails claim back.

![image](https://user-images.githubusercontent.com/75836438/114617171-04bc2080-9c65-11eb-8c90-8ef2915a6662.png)

**Comment by JasSuri** [comment]
Change this line
https://github.com/azure-ad-b2c/samples/blob/master/policies/username-signup-or-signin/policy/Username_TrustFrameworkExtensions.xml#L247

To
```xml
OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="strongAuthenticationEmailAddress" />
```

**Comment by tokenDeveloper2020** [comment]
> Change this line
> https://github.com/azure-ad-b2c/samples/blob/master/policies/username-signup-or-signin/policy/Username_TrustFrameworkExtensions.xml#L247
> 
> To
> 
> ```
> <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="strongAuthenticationEmailAddress" />
> ```

Still no email claim after changing

**Comment by JasSuri** [comment]
Ok scratch that. It needs to be added to the Technical Profile `AAD-UserReadUsingObjectId`.

```xml
<OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="strongAuthenticationEmailAddress" />
```
