### ISSUE TITLE
Password reset without Social Accounts

### ISSUE THREAD

**Issue by emaborsa** [azure-ad-b2c/samples#214]
I set up a custom policy, started from [LoclaAccounts](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/LocalAccounts) and added [MFA](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-mfa-totp). It works.
Then I wanted to add the password reset policy, followed [this tutorial](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy) and [this sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/embedded-password-reset), I removed some Social Account stuff and it works, but with this result:
![b2c_pwd_reset](https://user-images.githubusercontent.com/9129912/114692815-43131780-9d19-11eb-8c34-5b30550e53b8.png)

The part signed in red is rendered by the following code in the OrchestrationStep:
`<ClaimsProviderSelection TargetClaimsExchangeId="ForgotPasswordExchange"/>`

Removing this line, the login view is as needed:
![b2c_pwd_reset2](https://user-images.githubusercontent.com/9129912/114692830-473f3500-9d19-11eb-9c7b-ade4ff2742ad.png)

But when the **Forgot your password?** link is clicked, obviously an exception is thrown:
`"Claim exchange 'ForgotPasswordExchange' provided in the request is not one of the available during claims provider selection."`

Here my policy: [customPolicy.zip](https://github.com/azure-ad-b2c/samples/files/6310012/customPolicy.zip)

**Comment by JasSuri** [comment]
This is a known issue, the only thing you can do is hide that with CSS.
