### ISSUE TITLE
Secure REST api

### ISSUE THREAD

**Issue by ducalai** [azure-ad-b2c/samples#215]
I'm trying to add security on sample https://github.com/azure-ad-b2c/samples/tree/master/policies/remote-profile and secure both SignUp() and SignIn() webapi endpoints.

I followed Secure REST api using OAuth2 Bearer documentation (https://docs.microsoft.com/en-us/azure/active-directory-b2c/secure-rest-api#using-oauth2-bearer). In TrustFrameworkExtensions.xml, I did:
- define claims to store the bearer token (bearerToken, grant_type and scope)
- add a new technical profile to call https://login.microsoftonline.com/your-tenant-name.onmicrosoft.com/oauth2/v2.0/token in order to get an access_token. I tested it separately with Postman using my client_id, client_secret, scope and grant_type and I got correctly an access_token
- change the REST-SignUpOrEditProfile technical profile to use bearer token authentication

But when I test my SignUpOrSignin policy on Azure and try to SignUp, I receive error: "Claim 'bearerToken' specified for the bearer token is not present in the available claims. Available claims 'objectId, email, displayName, givenName, surname'." 

Do I missed some steps?

**Comment by JasSuri** [comment]
Post your technical profiles.

**Comment by ducalai** [comment]
```
<ClaimsProvider>  
       <DisplayName>REST APIs</DisplayName>

	  <TechnicalProfiles>

	  <TechnicalProfile Id="SecureREST-AccessToken">
         <DisplayName></DisplayName>
         <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
         <Metadata>
           <Item Key="ServiceUrl">https://login.microsoftonline.com/your-tenant-name.onmicrosoft.com/oauth2/v2.0/token</Item>
           <Item Key="AuthenticationType">Basic</Item>
           <Item Key="SendClaimsIn">Form</Item>
         </Metadata>
         <CryptographicKeys>
           <Key Id="BasicAuthenticationUsername" StorageReferenceId="B2C_1A_SecureRESTClientId" />
           <Key Id="BasicAuthenticationPassword" StorageReferenceId="B2C_1A_SecureRESTClientSecret" />
         </CryptographicKeys>
         <InputClaims>
           <InputClaim ClaimTypeReferenceId="grant_type" DefaultValue="client_credentials" />
           <InputClaim ClaimTypeReferenceId="scope" DefaultValue="https://your-tenant-name.onmicrosoft.com/api/.default" />
         </InputClaims>
         <OutputClaims>
           <OutputClaim ClaimTypeReferenceId="bearerToken" PartnerClaimType="access_token" />
         </OutputClaims>
         <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
       </TechnicalProfile>

	  
       <!-- Demo: Remote profile sign-up REST API -->

	  <TechnicalProfile Id="REST-SignUpOrEditProfile">

	    <DisplayName>Validate user input data and return loyaltyNumber claim</DisplayName>

	    <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />

	    <Metadata>

	      <Item Key="ServiceUrl">http://your-app.azurewebsites.net/api/Identity/signup</Item>

	      <Item Key="AuthenticationType">Bearer</Item>

	      <Item Key="SendClaimsIn">Body</Item>
           <Item Key="AllowInsecureAuthInProduction">false</Item>
           <Item Key="UseClaimAsBearerToken">bearerToken</Item>

	    </Metadata>

	    <InputClaims>

	      <InputClaim ClaimTypeReferenceId="objectId" />

	      <InputClaim ClaimTypeReferenceId="email" />

	      <InputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="displayName" />

	      <InputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="givenName" />

	      <InputClaim ClaimTypeReferenceId="surname" PartnerClaimType="surname" />

	    </InputClaims>

	    <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />

	  </TechnicalProfile>



	  <!-- Demo: Remote profile sign-in REST API -->

	  <TechnicalProfile Id="REST-SignIn">

	    <DisplayName>Validate user input data and return loyaltyNumber claim</DisplayName>

	    <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />

	    <Metadata>

	      <Item Key="ServiceUrl">http://your-app.azurewebsites.net/api/Identity/signin</Item>

	      <Item Key="AuthenticationType">Bearer</Item>
	      <Item Key="SendClaimsIn">Body</Item>
           <Item Key="AllowInsecureAuthInProduction">false</Item>
           <Item Key="UseClaimAsBearerToken">bearerToken</Item>

	    </Metadata>

	    <InputClaims>

	      <InputClaim ClaimTypeReferenceId="objectId" />

	    </InputClaims>

	    <OutputClaims>

	      <OutputClaim ClaimTypeReferenceId="email" />

	      <OutputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="displayName" />

	      <OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="givenName" />

	      <OutputClaim ClaimTypeReferenceId="surname" PartnerClaimType="surname" />

	    </OutputClaims>

	    <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />

	  </TechnicalProfile>



	  </TechnicalProfiles>

	</ClaimsProvider>
```

**Comment by JasSuri** [comment]
And where are you invoking `SecureREST-AccessToken`? It needs to be called before `REST-SignIn`.

**Comment by ducalai** [comment]
I did it a little bit after that in TrustFrameworkExtensions.xml, in UserJourneys section.

`<UserJourney Id="SignUpOrSignIn">
      <OrchestrationSteps>
      
        <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin">
          <ClaimsProviderSelections>
            <ClaimsProviderSelection TargetClaimsExchangeId="FacebookExchange" />
           <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
          </ClaimsProviderSelections>
          <ClaimsExchanges>
            <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
          </ClaimsExchanges>
        </OrchestrationStep>

        
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="FacebookExchange" TechnicalProfileReferenceId="Facebook-OAUTH" />
           <ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmail" />
          </ClaimsExchanges>
        </OrchestrationStep>

        
        <OrchestrationStep Order="3" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>localAccountAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserReadUsingAlternativeSecurityId" TechnicalProfileReferenceId="AAD-UserReadUsingAlternativeSecurityId-NoError" />
          </ClaimsExchanges>
        </OrchestrationStep>

        
        <OrchestrationStep Order="4" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="SelfAsserted-Social" TechnicalProfileReferenceId="SelfAsserted-Social" />
          </ClaimsExchanges>
        </OrchestrationStep>

        
        <OrchestrationStep Order="5" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>socialIdpAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserReadWithObjectId" TechnicalProfileReferenceId="AAD-UserReadUsingObjectId" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        
        <OrchestrationStep Order="6" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="SecureRESTAccessToken" TechnicalProfileReferenceId="SecureREST-AccessToken" />
          </ClaimsExchanges>
        </OrchestrationStep>

        
        <OrchestrationStep Order="7" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="RESTSignIn" TechnicalProfileReferenceId="REST-SignIn" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        
        <OrchestrationStep Order="8" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserWrite" TechnicalProfileReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
          </ClaimsExchanges>
        </OrchestrationStep>
 
        <OrchestrationStep Order="9" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
 
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
    </UserJourney>

    <UserJourney Id="ProfileEdit">
      <OrchestrationSteps>
      
        <OrchestrationStep Order="1" Type="ClaimsProviderSelection" ContentDefinitionReferenceId="api.idpselections">
          <ClaimsProviderSelections>
            <ClaimsProviderSelection TargetClaimsExchangeId="FacebookExchange" />
            <ClaimsProviderSelection TargetClaimsExchangeId="LocalAccountSigninEmailExchange" />
          </ClaimsProviderSelections>
        </OrchestrationStep>
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="FacebookExchange" TechnicalProfileReferenceId="Facebook-OAUTH" />
            <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="3" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>localAccountAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserRead" TechnicalProfileReferenceId="AAD-UserReadUsingAlternativeSecurityId" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="4" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>socialIdpAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserReadWithObjectId" TechnicalProfileReferenceId="AAD-UserReadUsingObjectId" />
          </ClaimsExchanges>
        </OrchestrationStep>

        
        <OrchestrationStep Order="5" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="SecureRESTAccessToken" TechnicalProfileReferenceId="SecureREST-AccessToken" />
          </ClaimsExchanges>
        </OrchestrationStep>
 
         
        <OrchestrationStep Order="6" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="REST-SignIn" TechnicalProfileReferenceId="REST-SignIn" />
          </ClaimsExchanges>
        </OrchestrationStep>

        <OrchestrationStep Order="7" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="B2CUserProfileUpdateExchange" TechnicalProfileReferenceId="SelfAsserted-ProfileUpdate" />
          </ClaimsExchanges>
        </OrchestrationStep>

        <OrchestrationStep Order="8" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
 
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
    </UserJourney>

    <UserJourney Id="PasswordReset">
      <OrchestrationSteps>
        <OrchestrationStep Order="1" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="PasswordResetUsingEmailAddressExchange" TechnicalProfileReferenceId="LocalAccountDiscoveryUsingEmailAddress" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="NewCredentials" TechnicalProfileReferenceId="LocalAccountWritePasswordUsingObjectId" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="3" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
    </UserJourney>
 
  </UserJourneys>`

**Comment by JasSuri** [comment]
According to that, `REST-SignIn` should work fine.
But you did not show where you called `REST-SignUpOrEditProfile`. Where do you call `REST-SignUpOrEditProfile`?

**Comment by ducalai** [comment]
In ClaimsProviders section I have:


    <ClaimsProvider>
      <DisplayName>Local Account</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="LocalAccountSignUpWithLogonEmail">
          <Metadata>
            <Item Key="EnforceEmailVerification">False</Item>
          </Metadata>
          <ValidationTechnicalProfiles>
            
            <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingLogonEmail" />
            <ValidationTechnicalProfile ReferenceId="REST-SignUpOrEditProfile" />
          </ValidationTechnicalProfiles>          
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>

    <ClaimsProvider>
      <DisplayName>Self Asserted</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="SelfAsserted-Social">
          <ValidationTechnicalProfiles>
            
            <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
            <ValidationTechnicalProfile ReferenceId="REST-SignUpOrEditProfile" />
          </ValidationTechnicalProfiles>
        </TechnicalProfile>

        <TechnicalProfile Id="SelfAsserted-ProfileUpdate">
        <InputClaims>
            <InputClaim ClaimTypeReferenceId="displayName" />
          </InputClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="displayName" />
          </OutputClaims>
          <ValidationTechnicalProfiles>
            
            <ValidationTechnicalProfile ReferenceId="AAD-UserWriteProfileUsingObjectId" />
            <ValidationTechnicalProfile ReferenceId="REST-SignUpOrEditProfile" />
          </ValidationTechnicalProfiles>
        </TechnicalProfile>

      </TechnicalProfiles>
    </ClaimsProvider>

**Comment by ducalai** [comment]
Do I need to add `<ValidationTechnicalProfile ReferenceId="SecureREST-AccessToken" />` before each `<ValidationTechnicalProfile ReferenceId="REST-SignUpOrEditProfile" />` line ?

**Comment by JasSuri** [comment]
There's your problem. `REST-SignUpOrEditProfile` in Step 2 runs before your `SecureREST-AccessToken` in Step 5. So there is no `bearerToken` available here.

You can fix it in two ways:
First method:
```xml
        <ValidationTechnicalProfile ReferenceId="AAD-UserWriteProfileUsingObjectId" />
        <ValidationTechnicalProfile ReferenceId="SecureREST-AccessToken" />
        <ValidationTechnicalProfile ReferenceId="REST-SignUpOrEditProfile" />
```

But this will mean you call `SecureREST-AccessToken` twice overall, which is a waste.

Second method change the journey itself:
```xml

    <OrchestrationStep Order="1" Type="ClaimsExchange">
      <ClaimsExchanges>
        <ClaimsExchange Id="SecureRESTAccessToken" TechnicalProfileReferenceId="SecureREST-AccessToken" />
      </ClaimsExchanges>
    </OrchestrationStep>

    <OrchestrationStep Order="2" Type="ClaimsProviderSelection" ContentDefinitionReferenceId="api.idpselections">
      <ClaimsProviderSelections>
        <ClaimsProviderSelection TargetClaimsExchangeId="FacebookExchange" />
        <ClaimsProviderSelection TargetClaimsExchangeId="LocalAccountSigninEmailExchange" />
      </ClaimsProviderSelections>
    </OrchestrationStep>

```
And get rid of step 5.
This is preferred, as in your journey, regardless of sign in or sign up, you need to get the bearerToken claim. So you can call it right at the start.

**Comment by JasSuri** [comment]
Those client credentials should be generated by creating an **Azure AD Application Registration** (Account from this organisation only option) in the directory which you want to protect your API with (usually you would create it in your Organisation Azure AD and not your Azure AD B2C).
