### ISSUE TITLE
Throwing error when trying to upload the policy

### ISSUE THREAD

**Issue by sandipNGA** [azure-ad-b2c/samples#218]
Hi,

Not sure why it is happening. Whenever I am trying to upload the policy, it is throwing me the following error. Can you please help what I might be missing?

"B2C_1A_SIGNIN_EMAILORPH_MFA" of tenant "ngahreudevadb2c.onmicrosoft.com".A required Metadata item with key "ApplicationObjectId" was not found in the TechnicalProfile with id "AAD-UserWriteMFAMethod" in policy "B2C_1A_signin_emailOrPh_mfa" of tenant "ngahreudevadb2c.onmicrosoft.com".A required Metadata item with key "ApplicationObjectId" was not found in the TechnicalProfile with id "AAD-UserWritePhoneNumberUsingObjectId" in policy "B2C_1A_signin_emailOrPh_mfa" of tenant "ngahreudevadb2c.onmicrosoft.com".A required Metadata item with key "ApplicationObjectId" was not found in the TechnicalProfile with id "AAD-UserWriteMFAMethod" in policy "B2C_1A_signin_emailOrPh_mfa" of tenant "ngahreudevadb2c.onmicrosoft.com".A required Metadata item with key "ApplicationObjectId" was not found in the TechnicalProfile with id "AAD-UserWritePhoneNumberUsingObjectId" in policy "B2C_1A_signin_emailOrPh_mfa" of tenant "ngahreudevadb2c.onmicrosoft.com".

**Comment by JasSuri** [comment]
Follow the pre requisites 

https://github.com/azure-ad-b2c/samples#prerequisites


For any custom policy sample which makes use of Extension attributes, follow the guidance here and here. The AAD-Common Technical profile will always need to be modified to use your ApplicationId and ObjectId

**Comment by ShamithaSIlva** [comment]
I think the answer is not focusing to the question. There is no mention about "ApplicationObjectId" in the link you proided @JasSuri
