### ISSUE TITLE
About the "password-reset-only" sample: Need to add HTML content along with an <a> tag that can be rendered as HTML when claim is transformed

### ISSUE THREAD

**Issue by tiwari-abhishek** [azure-ad-b2c/samples#22]
The sample for "password reset only" works great.
https://github.com/azure-ad-b2c/samples/tree/master/policies/password-reset-only

The TrustFrameworkExtensions file has the below content.

`    <ClaimsTransformations>
        
        <ClaimsTransformation Id="GetPasswordResetUserMessage" TransformationMethod="CreateStringClaim">
            <InputParameters>
                <InputParameter Id="value" DataType="string" Value="Your password has been successfully updated. To continue click on the sign-in link below." />
            </InputParameters>
            <OutputClaims>
                <OutputClaim ClaimTypeReferenceId="userMessage" TransformationClaimType="createdClaim" />
            </OutputClaims>
        </ClaimsTransformation>
    </ClaimsTransformations>`

How can I add an Anchor tag here to show a link along with some friendly text. I tried to HTML Encode a string with an Anchor tag but it just renders as plain text without parsing the HTML parts.

**Comment by JasSuri** [comment]
I don't think you can do that, rather it might be better to put the link/text in your custom HTML file and use CSS to move it into the right position.
