### ISSUE TITLE
[Query] Unable to understand that the two types of issuer in aad b2c are in the access token. 

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [azure-ad-b2c/samples#220]
When I use aad b2c, I can get two types of issuer in the access token through user flow. They are:
- iss claims: https://xxxxb2c.b2clogin.com/tenant-id/v2.0/
- iss claims:  https://xxxxb2c.b2clogin.com/tfp/tenant-id/b2c_1_signupsignin1/v2.0/

I am very surprised about the first one, why does the issuer not contain the user flow name, and there is no way to get the OpenID Connect metadata document through issuer splicing **/.well-known/openid-configuration**. The second issuer can do it. Is there any special reason for this?

**Comment by JasSuri** [comment]
Some libraries use the issuer to fetch the metadata. Some construct it using the authority. Some require it manually. Use the issuer that makes sense for your authentication library.
