### ISSUE TITLE
Embedded password reset doesn't respect setting.operatingMode

### ISSUE THREAD

**Issue by andrewalderson** [azure-ad-b2c/samples#221]
I implemented the new recommended 'Forgot Password' functionality as outlined in the [docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy#self-service-password-reset-recommended) but when I updated the DataUri as per this step
```
<!-- 
<BuildingBlocks>
  <ContentDefinitions> -->
    <ContentDefinition Id="api.signuporsignin">
      <DataUri>urn:com:microsoft:aad:b2c:elements:contract:unifiedssp:2.1.2</DataUri>
    </ContentDefinition>
  <!-- 
  </ContentDefinitions>
</BuildingBlocks> -->
```
it no longer respects the setting.operatingMode set to Email. The input in the UI has `type="text"` instead of `type="email"`.

**Comment by JasSuri** [comment]
Change UserInputType for the claim to `EmailBox` from `TextBox`.
