### ISSUE TITLE
Embedded password reset shows empty "Login with your social account" heading

### ISSUE THREAD

**Issue by TaekeK** [azure-ad-b2c/samples#222]
I implemented the new self service password reset for a user journey without other social providers. Because it is setup as a new ClaimsProviderSelection it will show the "Login with your social account" heading, but there is nothing to show and that section remains empty. Is there a setting to hide this heading for cases where no other social providers are defined?

**Comment by JasSuri** [comment]
As of yet, the only solution is to use CSS to hide it with your custom HTML template.
