### ISSUE TITLE
Edge browser: Tracking Prevention blocked access to storage for [...]

### ISSUE THREAD

**Issue by copiltembel** [azure-ad-b2c/samples#227]
Trying to use this sample in Microsoft Edge browser leads to the following warnings:

> 
> Tracking Prevention blocked access to storage for https://www.gstatic.com/recaptcha/releases/9qx0v7NiOAe_XnW_ULNZm9e3/styles__ltr.css.
> Tracking Prevention blocked access to storage for https://www.gstatic.com/recaptcha/releases/9qx0v7NiOAe_XnW_ULNZm9e3/recaptcha__en.js.
> Tracking Prevention blocked access to storage for https://www.gstatic.com/recaptcha/api2/logo_48.png.

I guess this will entirely prevent the recaptcha from working. 

Other browsers (Chrome, Firefox) seem to work fine.

Is there a solution to make it work in Edge as well?

**Comment by JasSuri** [comment]
I don't think this is a AAD B2C issue, more likely, even if it was your own HTML in your Edge browser, it would have the same problem.
