### ISSUE TITLE
Policy Engine demanding IDPSSODescriptor from Service Provider

### ISSUE THREAD

**Issue by dfbaskin** [azure-ad-b2c/samples#228]
I am connecting a SAML application to B2C using a custom policy as described in the documentation. The B2C Policy Engine was throwing an error:

> The metadata specified for the identity provider does not contain an IDPSSODescriptor

The application was not providing an IDPSSODescriptor definition in its metadata and adding this information (basically copying the SPSSODescriptor definition) was sufficient to make the authentication process work without error.

Perhaps I'm missing something, but it doesn't make sense that the policy engine would be demanding Identity Provider details from a service provider.  And in fact, the same application connects fine with SSOCircle without the IDSPSSODescriptor element.

Is this possibly an issue with the details of the custom policy? Or maybe the engine itself?

**Comment by JasSuri** [comment]
Where exactly where you providing this metadata endpoint? Post your xml snippet.

**Comment by dfbaskin** [comment]
In the `PartnerEntity`:

```xml
  <RelyingParty>
    <DefaultUserJourney ReferenceId="SAMLIdpSignUpOrSignIn" />
    <TechnicalProfile Id="PolicyProfile">
      <DisplayName>Policy Profile</DisplayName>
      <Protocol Name="SAML2"/>
      <Metadata>
        <Item Key="PartnerEntity">https://....blob.core.windows.net/public/saml-app-metadata.xml</Item>
      </Metadata>
```

**Comment by JasSuri** [comment]
Can try the latest guidance which has the service provider metadata configured in the `samlMetadataURL` of the Application Registration in the AAD B2C directory, and remove this metadata section in your XML.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/saml-service-provider?tabs=windows&pivots=b2c-custom-policy#register-your-saml-application-in-azure-ad-b2c

Under the section `Share the application's metadata with Azure AD B2C`.

**Comment by dfbaskin** [comment]
The application manifest already had the correct address in the `samlMetadataUrl` property.  But removing the `<Metadata>` element above causes B2C to give this error:

```
          {
            "Key": "SendErrorTechnicalProfile",
            "Value": "SamlProtocolProvider"
          },
          {
            "Key": "Exception",
            "Value": {
              "Kind": "Handled",
              "HResult": "80131500",
              "Message": "Application registered corresponding to IssuerUri \"com:vdenotaris:spring:sp\" in AuthRequest does not have assertion consumer service URL \"http://localhost:8080/saml/SSO\" specified in its metadata.",
              "Data": {
                "IsPolicySpecificError": false
              }
            }
          }
```

However, the metadata does have this assertion consumer service defined:

```
<md:AssertionConsumerService
   Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
   Location="http://localhost:8080/saml/SSO" index="0" isDefault="true"/>
```

**Comment by dfbaskin** [comment]
I've updated the metadata so that it _does not_ include the `IDPSSODescriptor` element and restored the `<Metadata>` element in the policy to point to this updated metadata as well as the `samlMetadataUrl` in the app manifest.

And now I'm no longer getting the "The metadata specified for the identity provider does not contain an IDPSSODescriptor" error.  Go figure.

**Comment by JasSuri** [comment]
Most likely you got the error around the ACS not existing because the identifierURI (entityId in the AuthNRequrst) isn’t mapping to the app registration you’re working on.
