### ISSUE TITLE
Initial page background color customisation

### ISSUE THREAD

**Issue by AurelianTimu** [azure-ad-b2c/samples#229]
Hi,

Before/during downloading the HTML content specified in the `ContentDefinition`, Azure AD B2C displays a "Loading" page.
The "issue" with this "Loading" page is that the background is white - there is no way (that i know of) to customise the background color.
This causes a flicker when the HTML content specified in the `ContentDefinition` is loaded/rendered, and is using any other background color besides white.

I would like to implement a dark/light color scheme for my HTML, however there is no way to change the css of the Azure AD B2C "initial" page. 
Is it possible to change the css of the Azure AD B2C "initial" page?I would be very nice if it were possible, as this would enable usage of dark/light themes without any flicker and it would boost UX a lot.

<img width="1440" alt="Screenshot 2021-05-05 at 20 25 36" src="https://user-images.githubusercontent.com/7172837/117183885-c2f44500-ade0-11eb-9d9c-32c3e542d724.png">

**Comment by JasSuri** [comment]
This needs to go on stackoverflow, it is not a bug with any sample here.
