### ISSUE TITLE
Magic link: OpenIdConnectAuthenticationHandler: message.State is null or empty

### ISSUE THREAD

**Issue by AmitavaHazra** [azure-ad-b2c/samples#233]
Reference:
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link

Using this in your Production Application - Could you please help how can we use authentication library to create a state and handle authentication request using id_token_hint.

It has been explained in this referenced link. Please help if there is any link how we can integrate magic link custom policy with production app. Note: using run as link and jwt.ms it is working as expected.

**Comment by JasSuri** [comment]
What programming language? What auth library? Post this on stackoverflow please.

**Comment by AmitavaHazra** [comment]
@JasSuri  I am using Asp.net core 3.1 and c# programming language. I was following web api which is mentioned in this doc (source code) . I added another controller, model and view with top of this api(which has identity controller and oidc controller).
