### ISSUE TITLE
Generate direct Link to Embedded Password Reset subjourney to force password reset on first-login.

### ISSUE THREAD

**Issue by AlbozDroid** [azure-ad-b2c/samples#235]
We register users automatically in B2C using the Microsoft Graph API.
We then want to send an email with a direct link to the Embedded Password Reset flow, so that users resets their password.

How can we generate a link directly in the Password Reset subjourney?

Thanks.

**Comment by JasSuri** [comment]
Not possible, in this case you can just use a separate policy for direct password reset via your app myapp.com/pwdReset, which launches a dedicated password reset journey. 

Ask on stackoverflow for more information.
 Closing as it’s not an issue with any sample.

**Comment by AlbozDroid** [comment]
@JasSuri  We did exactly that but we have found this issue: 

Sorry, but we're having trouble signing you in.
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, please try again.
Correlation ID: d5a7e1ed-a6d2-4b6d-bc87-b8612a5419b4
Timestamp: 2021-05-27 12:19:05Z
AADB2C: An exception has occurred.

**Can you find out what is the exception? based on the correlation ID?** It'd be of great help.

**Comment by JasSuri** [comment]
Your error is `Claims exchange with id 'LocalAccountSigninEmailExchange' could not be found in orchestration step '5' and the step contains more than one claims exchange.`

Please follow up on stackoverflow using the `azure-ad-b2c` tag, and provide your user journey in the problem description.
In theory the password reset journey should just follow the default starter pack user journey for this scenario to work.

**Comment by AlbozDroid** [comment]
OK will follow in Stackoverflow.

**Comment by AlbozDroid** [comment]
@JasSuri Here is the link with the explanation and Policy: https://stackoverflow.com/questions/67735232/azure-ad-b2c-cannot-login-immediately-after-going-through-a-password-reset-flow
