### ISSUE TITLE
Cannot grant delegated permission in B2C for Microsoft graph API for permission User.Read 

### ISSUE THREAD

**Issue by Sahildange0** [azure-ad-b2c/samples#236]
As described here- > https://github.com/azure-ad-b2c/samples/tree/master/policies/B2C-Token-Includes-AzureAD-BearerToken
cannot add /grant delegated permission in B2C for Microsoft graph API for permission User.Read  . Please verify 
![user](https://user-images.githubusercontent.com/12394752/120150233-6ed65800-c208-11eb-9af8-e01e44255467.PNG)

**Comment by JasSuri** [comment]
When creating the application registration, choose type: “Accounts in this organisational directory only” (first option).

**Comment by Sahildange0** [comment]
Before closing think twice --> Please refer the documentation :- https://github.com/azure-ad-b2c/samples/tree/master/policies/B2C-Token-Includes-AzureAD-BearerToken . Clearly it is written (3rd option)-->From the Azure AD B2C portal, select App registration, create a friendly name for the app, and select the “Accounts in any organization directory or any identity provider…” under the Supported Account Types. By selecting this application option, it makes the application type to be a Multi-tenant app, thus making it available to Azure AD tenants. I want to get a access token from Azure AD, not Azure AD B2C.   “Accounts in this organisational directory only” (first option). dont work with Azure AD

**Comment by JasSuri** [comment]
Got it, can you test with the **second option** (Accounts in any organizational directory) - It should work. And then I will update the phrasing.

**Comment by Sahildange0** [comment]
@JasSuri : Thanks a lot, second option did worked.!

**Comment by JasSuri** [comment]
Updated sample.
