### ISSUE TITLE
Terms Of Use policy for Social Accounts

### ISSUE THREAD

**Issue by jordanvector** [azure-ad-b2c/samples#243]
I have been able to implement the versioned tou custom policy referenced here https://github.com/azure-ad-b2c/samples/blob/master/policies/sign-in-sign-up-versioned-tou

This works great for local accounts, however I cannot seem to get the tou values persist to AD for social accounts, so users logging in with google or facebook are prompted to accept the terms every login.

Is there another example that I am missing that implements tou acceptance for social accounts as well as localaccounts?

**Comment by JasSuri** [comment]
You need to follow the same process.

Collect the TOU on the SelfAsserted-Social technical profile - the attribute collection screen for Social Id Sign Ups from the B2C starter pack. Similar process how the checkbox is displayed on the Sign Up technical profile.

Then you need to follow the same process to write the TOU record as this sample using AAD-UserWriteUsingAlternativeSecurityId technical profile, which is also part of the starter pack to create the Social Id in B2C directory.

Please post design questions on stackoverflow, this is not a bug in this sample.
