### ISSUE TITLE
Self-Served Password Reset (Embedded Password Reset sample) does not prepopulate the email field with what the user has already entered in email field

### ISSUE THREAD

**Issue by AlbozDroid** [azure-ad-b2c/samples#244]
When using HRD (but also in a normal email/password sign-in page) if the email field has already been populated by the user, and they click "Forgot your password" link, in the Reset password flow the user is prompted to enter the email again.

Is there a way to prepopulate it with what the user has already entered in the email field?

**Comment by JasSuri** [comment]
Design questions should be posted on stackoverflow.
