### ISSUE TITLE
Enable email verification in invite by email custom policy.

### ISSUE THREAD

**Issue by moizzaveri** [azure-ad-b2c/samples#247]
I am sending the link through my API to frontend and then the frontend trigger the signup process with a click on a button. Due to this the email verification part through email is skipped. Is there any way to enable email verification just like the one in signup userflow by sending the otp to user entered email address?

I already tried changing the `<Item Key="EnforceEmailVerification">False</Item>` to True but the email verification is still not active.
Am I missing anything?

**Comment by JasSuri** [comment]
There is not enough detail here and this does not seem to be a bug with any sample here. Please raise the issue on stackoverflow with azure-ad-b2c tag with full details of your scenario and relevant XML snippets.
