### ISSUE TITLE
Wrong clientId in invite-via-email example?

### ISSUE THREAD

**Issue by Ted-chiptech** [azure-ad-b2c/samples#248]
I am looking at "policies\invite-via-email" example, The run.csx function under the source-code folder seems odds to me.

Inside the redeem method call, the clientId says "this should be the client_id or your real webapp"(Line 24), However, the clientId value used in the generate link request could be a different one as "this can be a client_id you set up just for getting this JWT" (Line 38).

I think they have to be the same clientId to make this work, as "AzureB2C validates the signature, issuer name and token audience." If they're not the same, the token audience validation would fail?

**Comment by JasSuri** [comment]
The metadata in the id token hint technical profile isn’t configured for any particular audience restriction. If it was, then the clientId would need to match. In this case, it’s just accepting and JWT issued from the same tenant.

**Comment by Ted-chiptech** [comment]
Hi JasSuri, thanks for your answer, somehow I am getting "The provided id_token_hint parameter does not contain an accepted audience" error. But what you said makes sense, I will keep checking if anything wrong on my side. Thanks for your help!

**Comment by JasSuri** [comment]
Review this
https://docs.microsoft.com/en-us/azure/active-directory-b2c/id-token-hint#metadata

**Comment by Mattdjuret** [comment]
@Ted-chiptech Did you manage to solve this? I'm experiencing the same problem.
IdTokenAudience is not present as metadata, but still I get  "The provided id_token_hint parameter does not contain an accepted audience" error

**Comment by Ted-chiptech** [comment]
> @Ted-chiptech Did you manage to solve this? I'm experiencing the same problem.
> IdTokenAudience is not present as metadata, but still I get "The provided id_token_hint parameter does not contain an accepted audience" error

@Mattdjuret I switched to use https://github.com/azure-ad-b2c/samples/tree/master/policies/invite instead as I do still experiencing that issue, and I think that "invite-via-email" policy is a little bit hacky to use the old idToken and swap out clientId to make it work.

I think the invite solution is more appropriate and I updated it by putting the certificate in Azure KeyVault to let it auto-renew.
