### ISSUE TITLE
IEF Experimental Setup fails for both types of link accounts

### ISSUE THREAD

**Issue by tommycbarker** [azure-ad-b2c/samples#249]
Same failed response for the IEF Automation Application Experimental setup option, for both link account sample folders. B2C tenant is fully populated as I have successfully used the base application multiple times. See below. Please advise.

![image](https://user-images.githubusercontent.com/12501329/123289174-34e23400-d4de-11eb-9df9-d58e80f09e31.png)

**Comment by JasSuri** [comment]
I wouldn’t expect these to work as they use policy keys that the tool never setup. If you’re saying that you already added the dependencies, then can you upload them through the Azure portal and paste the error here?

**Comment by tommycbarker** [comment]
Thanks for your reply, no, I am saying IEF automation tool showed a failed status, so based on your response they are expected to show a status of "Failed". Thanks for clarifying.
