### ISSUE TITLE
b2c-extensions-app config missing for B2C IEF Custom Policy - Sign Up and Sign In with 'Terms of Use' prompt

### ISSUE THREAD

**Issue by leniel** [azure-ad-b2c/samples#25]
This sample https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-sign-up-versioned-tou is missing a notice in its doc telling that it's necessary to configure `b2c-extensions-app` data in `TrusFrameworkBase.xml` as discussed [here](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/issues/34#issuecomment-563350806).

**Comment by JasSuri** [comment]
None of the samples are explicit on this since it’s part of the main readme pre req. we look to change it so it’s mentioned in each sample too.

**Comment by WhippsP** [comment]
Closing this issue as this is comon across all examples and is on the backlog of updates to change.
