### ISSUE TITLE
SignUp with email invitation bug?

### ISSUE THREAD

**Issue by omcgdelacruz** [azure-ad-b2c/samples#250]
I'm trying to set up the AD B2C "SignUp with email invitation" policy.
According to documentation: "_Azure AD _B2C_ validate the input id_token_hint, asks the user to provide the password and user data (the email is read only)"_.
![image](https://user-images.githubusercontent.com/80857436/123333201-0cbafb00-d507-11eb-9fee-a4f56b1ca5a0.png)

The problem is when I try to configure the application, everything works great except the email input field is not pre-filled (with the same email I sent the invitation to, with the confirmation link) and it's not a read-only field, so the user could change the existing email we have already registered in our database. I'm using a sign up user flow in our b2c tenant as indicated.

Is there a way to pre-filled a read-only email field using a User flow or do I need custom policy?
![image](https://user-images.githubusercontent.com/80857436/123334879-560c4a00-d509-11eb-971e-7ae64c885bdd.png)
Thanks in advance.

**Comment by JasSuri** [comment]
You need to use the custom policy user journey in the sample, it won’t work with the default sign up journey.
