### ISSUE TITLE
Using this in your Production Application - Magic Link

### ISSUE THREAD

**Issue by AmitavaHazra** [azure-ad-b2c/samples#252]
Reference:
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link

On the above do it is stated that for production user we should not create magic link with hard coded values instead we should let MSAL to create this.

Could you please explain such code sample or MSAL implementation of such authentication request and flow using id_token_hint parameter.

Also in the section "Using this in your Production Application" it states about it and in a incomplete way.

See the docuementation for the library in use to implement this.

But there is no such doc link available to refer.

**Comment by JasSuri** [comment]
Will update the sample

https://docs.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-web-application-options#pass-id-token-hint


https://docs.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-spa-app-options
