### ISSUE TITLE
How to define custom route to integrate magic link with production app

### ISSUE THREAD

**Issue by AmitavaHazra** [azure-ad-b2c/samples#254]
https://myapp.com/redeem?hint=<id_token_hint value>
Here do we need to have any custom controller suppressing "Account" controller. ? 
----------------------------------------------
 services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApp(options =>
                    {
                        Configuration.Bind("AzureAdB2C", options);
                        options.Events ??= new OpenIdConnectEvents();
                        options.Events.OnRedirectToIdentityProvider += OnRedirectToIdentityProviderFunc;
                    });
--------------------------------------------------
 private async Task OnRedirectToIdentityProviderFunc(RedirectContext context)
        {
            // The idTokenHint variable holds your ID token 
            context.ProtocolMessage.IdTokenHint = **idtoken**
 
           // More code
            await Task.CompletedTask.ConfigureAwait(false);
        }

================================================================
Please help me to define a path in app so that I can pass idtoken value to startup.cs file.

Plan,

1. Upon click on "Sign in with Magic link" option, I can create a idtoken using jwt but could not find a way to pass that value to application path. so that upon clicking on that link app should proceed further.

**Comment by JasSuri** [comment]
Open a thread on stackoverflow, this is not a bug with any sample here.
