### ISSUE TITLE
Getting Error AADB2C90233: The provided id_token_hint parameter failed signature validation (Invite Template)

### ISSUE THREAD

**Issue by omcgdelacruz** [azure-ad-b2c/samples#256]
I kepp getting the Error AADB2C90233: The provided id_token_hint parameter failed signature validation. Please provide another token and try again.

I'm using the app and "SignUpInvitation.xml" policy in https://github.com/azure-ad-b2c/samples/tree/master/policies/invite.
The TrustFrameworkBase.xml and TrustFrameworkExtensions.xml policies we uploaded in our B2C are from the starter pack here: https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/LocalAccounts.

I'm running the project locally. I replaced the issuer in the HomeController.cs line 102 as specified on another issue reported before: string issuer = $"https://omcgroupdev.b2clogin.com/omcgroupdev.onmicrosoft.com/v2.0/";

This is Id_token_hint from the email:
id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5RDczNkRGOUNFNkZBQUNGMEQ5MzlCMEU1NTMwQzUyQTJEN0MyQjQiLCJ4NXQiOiJhZGMyMzV6bS1xencyVG13NVZNTVVxTFh3clEiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiR3VpbGxlcm1vIFlhaG9vIiwiZW1haWwiOiJnZGxjc0B5YWhvby5jb20iLCJuYmYiOjE2MjU4NDYwNDQsImV4cCI6MTYyNjQ1MDg0NCwiaXNzIjoiaHR0cHM6Ly9vbWNncm91cGRldi5iMmNsb2dpbi5jb20vb21jZ3JvdXBkZXYub25taWNyb3NvZnQuY29tL3YyLjAvIiwiYXVkIjoiMjgzNjU0ZmQtMGYyNy00Zjc4LTljOGMtNWIwZGFlNWYwY2YzIn0.iLWCSF-_tQZ2OcD0kxnTe5SWXvH8Kpmq6ieUsqLNbIlmGaF5OdKniai7lxH_GanL9E48_JgcDpDGvhB4YUEOa8WncpMczDf2SaSLk5fhZ-TCIbRebmtethyhbC44nOnC2SZaNbRfvfcixZV6h2feXheTbmNQG1XzEImNAx4sWkZbkZLGNyBuGjbKqTFsVNng0j-go9vohHZYYV9WF-R12mWbDgr1Bd1_CfTDgnrCnwx9-Kmvjzfp39zLSkq77O224wC_p0ulqCE_IIhUFfNuSqXB722nf6Zq_Z-WitzbSohb15aHQyROPyts9tx5HXhgo5S9w_7_BuKfbX-WJTYgTg

Could you point me in the right direction?
Thanks

**Comment by JasSuri** [comment]
Did you configure this line
https://github.com/azure-ad-b2c/samples/blob/master/policies/invite/policy/SignUpInvitation.xml#L143

Needs to point to your apps metadata document url.

**Comment by TaekeK** [comment]
Yes that line is configured as well as the other required keys, like UsePolicyInRedirectUri is false. That key should make the configured URI work and policy should not be needed. Redirection to the OIDC IdP works, but redirect back from the IdP to B2C, however, gives the resource not found error. The redirect URI in the IdP is configured like in the documentation: https://{your-tenant-name}.b2clogin.com/{your-tenant-name}.onmicrosoft.com/oauth2/authresp, with your-tenant-name being my tenant. That URI gives a resource not found error.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by JasSuri** [comment]
> Yes that line is configured as well as the other required keys, like UsePolicyInRedirectUri is false. That key should make the configured URI work and policy should not be needed. Redirection to the OIDC IdP works, but redirect back from the IdP to B2C, however, gives the resource not found error. The redirect URI in the IdP is configured like in the documentation: https://{your-tenant-name}.b2clogin.com/{your-tenant-name}.onmicrosoft.com/oauth2/authresp, with your-tenant-name being my tenant. That URI gives a resource not found error. Sent from Nine<http://www.9folders.com/>
> […](#)

Not sure how any of that is related to the original issue of invalid signature.

**Comment by TaekeK** [comment]
Oops, replied to wrong thread.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by JasSuri** [comment]
There is a whole set of instructions if you want to have AAD B2C host the metadata document:
https://github.com/azure-ad-b2c/samples/tree/master/policies/invite#using-b2c-to-generate-the-metadata-endpoints

Usually that would not be "p=B2C_1A_SIGNUP_INVITATION" when following those above instructions, as that is your main policy.

**Comment by omcgdelacruz** [comment]
Thanks for you quick response @JasSuri.

I already followed all the "Steps to have B2C create these metadata endpoints":
- I generated a Policy Key (B2C_1A_IdTokenHintCert), key type RSA and usage to be Signature.
- I created a set of new base from the started pack using LocalAccounts: TrustFrameworkExtensions.xml, TrustFrameworkBase.xml and SignUpOrSignin.xml. At the moment, I won't be needing EditProfile or PasswordReset. At the same time I created the TokenSigningKeyContainer signing key and the okenEncryptionKeyContainer encryption key in our Azure AD B2C.
- I Updated B2C_1A B2C_1A_TokenSigningKeyContainer to B2C_1A_IdTokenHintCert (On TechnicalProfile Id="JwtIssuer") on the TrustFrameworkBase.xml file and uploaded it again.

My custom policies:
![image](https://user-images.githubusercontent.com/80857436/125358873-204fc980-e32f-11eb-9961-220c9c715a6a.png)
My policy keys:
![image](https://user-images.githubusercontent.com/80857436/125358948-3493c680-e32f-11eb-8924-de20652ba260.png)


Regarding the format you mentioned, I already tried:
- https://omcgroupdev.b2clogin.com/omcgroupdev.onmicrosoft.com/B2C_1A_SIGNUP_INVITATION/v2.0/.well-known/openid-configuration (With B2C_1A_SIGNUP_INVITATION from the custom policy on the "Invite" App).
- https://omcgroupdev.b2clogin.com/omcgroupdev.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration (With B2C_1A_SIGNUP_SIGNIN from the LocalAccounts policies started pack).

**Comment by JasSuri** [comment]
This is your issue
> I generated a Policy Key (B2C_1A_IdTokenHintCert), key type RSA and usage to be Signature.

You are supposed to create your own certificate (.pfx) and upload this into the Policy Keys menu.
Then you use the private part of your certificate to generate the id_token_hint JWT.

And AAD B2C uses the metadata of the uploaded certificate to use the public key to verify the id_token_hint JWT.

**Comment by omcgdelacruz** [comment]
Thanks @JasSuri for all your help.

Is there an easier or a simple way to create my own certificate? On my Azure App Service if I go to TLS/SSL Settings>>Private Key Certificates (.pfx) and click on "Create App Service Managed Certificate", I have to add a custom domain, add a binding to that domain and so on...

I think on Azure, the only other way is to Buy and App Service Certificate on the TLS/SSL settings tab, am I right?

![image](https://user-images.githubusercontent.com/80857436/125522923-3ab767b7-0ea8-4374-9b4b-fcd774b922a9.png)

Thanks again for your help.

**Comment by JasSuri** [comment]
The readme explains how you can generate your own self signed certificate. You can buy a certificate from your preferred place if you like.
