### ISSUE TITLE
Not able to remove "Sign in with your social account" from the footer

### ISSUE THREAD

**Issue by arupnayak** [azure-ad-b2c/samples#257]
I am using the custom policy for Local account sign in and signup. "Sign in with your social account" appears on the footer. I am not able to remove it.

I am using the below content definition
api.signuporsigninwithpasswordreset

![image](https://user-images.githubusercontent.com/22816677/125209113-b3ddb780-e2a7-11eb-93e8-2c31ec68c8dc.png)

**Comment by JasSuri** [comment]
Required to use CSS with your custom HTML to get rid of that header when using the latest combined signin, sign up and password reset policy.
