### ISSUE TITLE
Account duplication when using the advanced policies for account-linkage-unified. When user signs-up with a social account like FB and then uses the same email to sign-up as a Local Account

### ISSUE THREAD

**Issue by lizetpenamsft** [azure-ad-b2c/samples#258]
We had an issue with  user account duplication when end-users use social accounts for sign-up and they have the same email used across several social account OIDC providers. The set of advanced policies **account-linkage-unified** solve that initial problem just fine. They allow the end-user to link their social accounts in B2C.

**However, there is a use case or scenario that is not covered by these advanced policies and is a major challenge, problem for us.**

Policies repo location
https://github.com/azure-ad-b2c/samples/tree/master/policies/account-linkage-unified

When the end-user signs-up with a social account, let's say FB (the same problem manifests when they select a different social account provider like Google), a user object is created in B2C with the identity type federated. If the user then signs-up with the same email he/she used with the social provider, lets say FB, **_but instead registering for a B2C Local Account_**, **_there will be 2 user objects created in B2C with no relationship at all, one FB federated user and the new Local Account user with the same email and UPN_**.

These set of policies, **account-linkage-unified**, do not prevent the user from signing up for a Local Account with the same email used by the Federated Identities; when there are several Federated Accounts from Social providers linked under the same email. They also do not allow the user to link their Local Account with the Federated Identities from Social Providers.

There is no issue if the user first registers or signs-up with a B2C local account and **then** attempts to use a social provider to sign up again. These accounts are linked under a single user with  2 identities, the Federated one from the OIDC provider and the Local Account one; B2C creates a single user with several Identities when the events happen in this sequence.

We're looking for suggestions to change the Orchestration Steps on the AccountLink User Journey to prevent the problem reported here.
Thank you!

cc: @JasSuri , @yoelhor

**Comment by JasSuri** [comment]
An easy solution is to always create the social with a signInName equal to the email returned from the social and random password. 

That means to get back into this account with local creds, they have to go through forgot password.

It prevents the issue you explain as they cannot then sign up for a local account, it’ll already exist to some extent.

**Comment by lizetpenamsft** [comment]
@JasSuri 
Hi Jas,
Let me see if I understand correctly, since I have to advise the customer team and help them modify the AccountLink policy and I presume the AccountLink Orchestration steps under the AccountLink User Journey.
When the user doesn't have yet a local account and he/she signs-up with a social provider, before creating the newUser in B2C, the custom policy must have an orchestration step to call a technical profile that will create a local account with the email from the social account and a random password.
**Correct?**

Can this be achieved modifying the custom policy only, or do we have to make calls to Graph API in the policy as part of the Orchestration steps.
I do understand the proposed solution, but I'm having a hard time visualizing the how, how to implement the solution.

Thank you.

**Comment by JasSuri** [comment]
Yes, that logic is correct and you can use the AAD technical profile to write a local account.

**Comment by lizetpenamsft** [comment]
Could we please re-open this issue, the changes we implement in the policy are giving us Policy Engine errors in the B2C tenant and we're unable to link the existing social account with the local account that is created.
