### ISSUE TITLE
Exception instead of user not found error message when using sign-in-with-email policy

### ISSUE THREAD

**Issue by HMoen** [azure-ad-b2c/samples#264]
We are using the [sign-in-with-email](https://github.com/azure-ad-b2c/samples/blob/master/policies/sign-in-with-email/policy/SigninWithEmail.xml#L39) custom policy with endpoints hosted by B2C. For accounts that exists, we successfully receive the id_token. If we create an id_token_hint using an email that is not associated to any account in B2C, we would expect https://github.com/azure-ad-b2c/samples/blob/548ff919b330975038d5ae3884ca5a86c23c0aed/policies/sign-in-with-email/policy/SigninWithEmail.xml#L39 to occur, but instead the exception below occurs (logged in application insights):

Exception Message: A Claim of ClaimType with id "accountEnabled" was not found, which is required by the ClaimsTransformationImpl of Type "Microsoft.Cpim.Data.Transformations.AssertBooleanClaimIsEqualToValueTransformation" for TransformationMethod "AssertBooleanClaimIsEqualToValue" referenced by the ClaimsTransformation with id "AssertAccountEnabledIsTrue" in policy "B2C_1A_TrustFrameworkBase" of tenant "smxpatients.onmicrosoft.com"., Exception Type:PolicyException, CorrelationID:95284105-ee16-4a17-acd3-5e82edd4896e

What change(s) do we need to make to the custom policy for the expected action to occur? Thanks in advance.

**Comment by JasSuri** [comment]
This sample policy relies on the AAD B2C starter pack.

The journey uses AAD-UserReadUsingObjectId, which is also defined in the starter pack: https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/LocalAccounts/TrustFrameworkBase.xml#L499

It references the AssertAccountEnabled claims transform.

You’re reading an account that doesn’t exist, so after that, the AssertAccountEnabled fails to operate on a null value (accountEnabled).

You can either remove the reference to AssertAccountEnabled in AAD-UserReadUsingObjectId or pass in accountEnabled as a claim in your id_token_hint.
