### ISSUE TITLE
Using KMSI with RBAC policy

### ISSUE THREAD

**Issue by sjthompsonengl** [azure-ad-b2c/samples#268]
We're using the RBAC sample policy approach to retrieve B2C group memberships and return as claims. This works fine until a user checks KMSI box, the user stays signed in but the group memberships claim is not stored.

Is there a way to include the group membership claim in the KMSI cookie? or a different approach to this?

**Comment by JasSuri** [comment]
Persist the claim “groups” into SM-AAD technical profile. That will store it in the cookie.
