### ISSUE TITLE
Find federated account without having AlternativeSecurityId

### ISSUE THREAD

**Issue by Viper61x23** [azure-ad-b2c/samples#269]
We have implemented a flow based on the home realm discovery.  

We have another custom policy for username discovery which we are trying to extend to handle local and federated accounts.

During the self asserted email capture we have the following validation technical profiles:

          <ValidationTechnicalProfiles>
            <ValidationTechnicalProfile ReferenceId="GetEmailAddressAndDomainCheck" />           
            <ValidationTechnicalProfile ReferenceId="AAD-UserReadUsingLogonEmailSilent" >            
              <Preconditions>
                <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
                  <Value>isKnownDomainCustomer</Value>
                  <Value>True</Value>
                  <Action>SkipThisValidationTechnicalProfile</Action>
                </Precondition>
              </Preconditions>                        
            </ValidationTechnicalProfile>         
            <ValidationTechnicalProfile ReferenceId="AAD-UserReadUsingAlternativeSecurityId-NoError" >            
              <Preconditions>
                <Precondition Type="ClaimEquals" ExecuteActionsIf="false">
                  <Value>isKnownDomainCustomer</Value>
                  <Value>True</Value>
                  <Action>SkipThisValidationTechnicalProfile</Action>
                </Precondition>
              </Preconditions>                        
            </ValidationTechnicalProfile>                        
          </ValidationTechnicalProfiles>    

So obviously the issue is that we cannot search for federated accounts using the alternativeSecurityId as this is something we cannot generate as it's based on their userid from their federated account.

How can we search for these accounts?

**Comment by JasSuri** [comment]
What you need to do is, when registering a federated account, write their email into signInNames.emailAddress or signInNames.custom.

**Comment by JasSuri** [comment]
Closing as this is not a bug with any sample. Continue on stackoverflow use the [azure-ad-b2c] tag.
