### ISSUE TITLE
Password Reset issue with MSAL React SPA

### ISSUE THREAD

**Issue by brriann** [azure-ad-b2c/samples#274]
I am seeing a possible issue with this implementation of Password Reset
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy

We are using Custom Policies, and our SignUpSignIn UserJourney/ all config came from the provided LocalAccounts starterpack.
https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack

We are using a React SPA as our client, with @azure/msal-browser v2.14.0 and @azure/msal-react v1.0.1
https://www.npmjs.com/package/@azure/msal-browser

The issue is:
- when a user follows the Password Reset ('forgot your password?') steps and lands in the React SPA
- and immediately tries to Edit Profile or Change Password 
- they are confronted with a sign in screen before seeing the Edit Profile or Change Password self-asserted technical profile screen
- users who are logged in, in the React SPA, who have NOT just reset their password, do not see this additional sign in screen
- This suggests that a user who has just finished the Password Reset flow is not properly authenticated / logged in as a user

More info:
- We are using the starter pack ProfileEdit UserJourney and RelyingParty file, as seen below
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-profile-editing-policy?pivots=b2c-custom-policy
- We are using a PasswordChange User Journey and RelyingParty file as seen below
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-change-policy?pivots=b2c-custom-policy
- We provide the user with menu options to Edit Profile or Change Password within the React SPA
- The extra sign in screen seems to be coming from SelfAsserted-LocalAccountSignin-Email, the first TechnicalProfile in both our ProfileEdit and PasswordChange UserJourneys

Observed:
- Using AppInsights logging with AADB2C, we observed differences in both claims and tokens, during a SignUpSignIn with PasswordReset, vs a happy path SignUpSignIn
- PasswordReset: email claim exists, userPrincipalName claim exists, signInName claim is in GUID/UPN format 
- happy path: email claim does not exist, userPrincipalName claim does not exist, signInName claim is of form "email => GUID/UPN format"
- PasswordReset: no tokens captured
- happy path: tokens from login-NonInteractive are captured

Theories:
- The Password Reset tutorial (above) mentions enabling Implicit Grant Flow.  However, MSAL 2 is not compatible with Implicit Grant Flow.  Maybe this explains absence of tokens visible in AppInsights, or is causing some other issue with MSAL not being able to properly sign in a user using Implicit Grant Flow
- We are missing some sort of OutputClaim or PartnerClaimType mapping between email and signInName, in one of the starterpack technical profiles (AAD, or one of the self-asserted login related)

I'm wondering if anyone else has observed issues like this, using the MS provided Password Reset instructions.  Thank you!  And please let me know if I can provide any more information.

**Comment by JasSuri** [comment]
This is likely due to the password reset flow not actually interacting with SM-AAD session mgmt technical profile. So moving to profile edit afterward will show the sign in screen. 

Creating some dummy orchestration step as part of the password reset user journey which writes the objectId to SM-AAD would probably be a workaround.

**Comment by brriann** [comment]
Thank you very much @JasSuri !  Your suggestion seems to have fixed the issue. 
Demo here https://github.com/brriann/b2c-msal-pwreset

**Comment by JasSuri** [comment]
The issue I have with your “fix”, is it applies session management to a very security sensitive step. 

It would also break flows like signing in through “forgot password” then trying to do a “change password”, because now the step to collect the new password is part of the session and will get skipped.

A better solution would be to add a claim transformation technical profile that outputs the objectId and uses SM-AAD. Call that right before the last orchestration step.

**Comment by brriann** [comment]
Thank you for the feedback @JasSuri !  I updated the fix demo.  Agreed, it makes sense to only associate that SM-AAD call to the PasswordReset SubJourney.
