### ISSUE TITLE
Error message while upload the custom policy : policies/sign-up-deep-link/policy/SignUpOrSignin.xml

### ISSUE THREAD

**Issue by gxgrammatikos** [azure-ad-b2c/samples#278]
I'm trying to upload the [sign-up-deep-link](https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-up-deep-link) custom policy but, 
I encounter the error message below:

_Validation failed: 1 validation error(s) found in policy "B2C_1A_SIGNUP_SIGNIN_WITH-SIGN-UP-DEEP-LINK" of tenant "#####.onmicrosoft.com".TechnicalProfile "Facebook-OAUTH" in policy "B2C_1A_signup_signin_with-sign-up-deep-link" of tenant "######.onmicrosoft.com" defines an invalid value "" for the metadata item "client_id."TechnicalProfile "Facebook-OAUTH" in policy "B2C_1A_signup_signin_with-sign-up-deep-link" of tenant "######.onmicrosoft.com" defines an invalid value "" for the metadata item "client_id."_

 while I'm trying to upload the SignUpOrSignin.xml.

**Comment by souvik2014** [comment]
You can comment the facebook related authentication
