### ISSUE TITLE
Hosting the application in Azure App Service for Linux (Invite Template)

### ISSUE THREAD

**Issue by omcgdelacruz** [azure-ad-b2c/samples#286]
Hi!

I'm trying to deploy the "SignUp with email invitation" on a Linux-based App Service. I already uploaded my certificate as a PFX file.

According to this link (https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-in-linuxwindows-containers) private certificates in Linux containers are stored in /var/ssl/private.

I double cheked and opened a SSH session to my App Service and I found my privete certificate on that folder:
4E*********************************B8.p12

So, I need to replace this piece of code in HomeController and OidcController:

```
public HomeController(ILogger<HomeController> logger, IOptions<AppSettingsModel> appSettings, IWebHostEnvironment hostingEnvironment)
        {
            this.AppSettings = appSettings.Value;
            this.HostingEnvironment = hostingEnvironment;
            this._logger = logger;
            // Sample: Load the certificate with a private key (must be pfx file)
            SigningCredentials = new Lazy<X509SigningCredentials>(() =>
            {
                X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
                certStore.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection certCollection = certStore.Certificates.Find(
                                            X509FindType.FindByThumbprint,
                                            this.AppSettings.SigningCertThumbprint,
                                            false);
                // Get the first cert with the thumb-print
                if (certCollection.Count > 0)
                {
                    return new X509SigningCredentials(certCollection[0]);
                }
                throw new Exception("Certificate not found");
            });
        }
```
According to documentation, I replaced it with:

```
public  HomeController(ILogger<HomeController> logger, IOptions<AppSettingsModel> appSettings, IWebHostEnvironment hostingEnvironment)
        {
            string finalPath = $"/var/ssl/private/<MYCERTIFICATETHUMBPRINT>.p12";
            var bytes = System.IO.File.ReadAllBytes(finalPath);
            var cert = new X509Certificate2(bytes);
        }
```
But when I try to send the email invitation or I try to open the metadata endpoint (https://******.azurewebsites.net/.well-known/openid-configuration) I get the following error:

_Internal Server Error:
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object._

Could you point me in the right direction?
Thanks

**Comment by JasSuri** [comment]
You should post on stackoverflow for help specifically with referencing a cert on a Linux app service.

**Comment by omcgdelacruz** [comment]
Thanks for the feedback @JasSuri. I already posted the question on stackoverflow.

Anyway, could it be possible to include in this documentation and the source-code (https://github.com/azure-ad-b2c/samples/tree/master/policies/invite) the instructions to host the application in a Linux-based App Service?

Thanks in advance.
