### ISSUE TITLE
force-password-reset-after-90-days policy- Unable to validate the information provided

### ISSUE THREAD

**Issue by gxgrammatikos** [azure-ad-b2c/samples#289]
I have tried the force-password-reset-after-90-days policy, but when I click the button "CREATE", it returns the error message below: 

![image](https://user-images.githubusercontent.com/10853004/134670515-1285e6fe-9f5b-41c0-ab9d-62a77e1884d5.png)

**Comment by JasSuri** [comment]
Can you get App insights logs
https://docs.microsoft.com/en-us/azure/active-directory-b2c/troubleshoot-with-application-insights

**Comment by gxgrammatikos** [comment]
Please find the log files below:

[2021-10-01 1.txt](https://github.com/azure-ad-b2c/samples/files/7266497/2021-10-01.1.txt)
[2021-10-01 2.txt](https://github.com/azure-ad-b2c/samples/files/7266498/2021-10-01.2.txt)
[2021-10-01 Step 1.txt](https://github.com/azure-ad-b2c/samples/files/7266499/2021-10-01.Step.1.txt)
[2021-10-01 Step 2.txt](https://github.com/azure-ad-b2c/samples/files/7266500/2021-10-01.Step.2.txt)

**Comment by JasSuri** [comment]
You have not enabled extension attribute support.
Follow this:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes?pivots=b2c-custom-policy#azure-ad-b2c-extensions-app

Or use my deployment tool to deploy the starter pack with extension attribute support enabled: https://aka.ms/iefsetup
This sample is also available for [quick deploy](https://b2ciefsetupapp.azurewebsites.net/Home/Experimental?sampleFolderName=force-password-reset-after-90-days).
