### ISSUE TITLE
invite-via-email example - insecure B2C_1A_genlink flow

### ISSUE THREAD

**Issue by muxout** [azure-ad-b2c/samples#290]
In the invite-via-email example, anybody with the URL to the B2C_1A_genlink flow would be a able to generate a token. Is there a recommended way to secure the B2C_1A_genlink flow so that it is only accessible by the Azure function?

**Comment by JasSuri** [comment]
This is a conceptual flow. Normally you’d generate your own token to be used as an id token hint. This example uses B2C itself to produce such a token.

This sample is more realistic to deploy as-is
https://github.com/azure-ad-b2c/samples/tree/master/policies/invite
