### ISSUE TITLE
Information request about Microsoft Authenticator

### ISSUE THREAD

**Issue by simonziegler** [azure-ad-b2c/samples#291]
Hi, I understand that using Authenticator with B2C via user flows (rather than custom policies, which are a step too far for me) is in private beta. Do you have a potential timescale for its release?

Many thanks,    Simon

https://github.com/azure-ad-b2c/samples/blob/master/policies/totp/media/userflow.png

![image](https://user-images.githubusercontent.com/11708435/135240325-bbc67953-8bfc-4be3-b2e5-707162908aa5.png)

**Comment by JasSuri** [comment]
Couple of months probably.
