### ISSUE TITLE
Home Realm Discovery - In browser, cannot use the application in 2 tabs

### ISSUE THREAD

**Issue by foramkumar-parekh** [azure-ad-b2c/samples#292]
I have used [Home Realm Discovery](https://github.com/azure-ad-b2c/samples/tree/master/policies/home-realm-discovery-modern), to log in users from 2 of our Azure AD tenants and other users (local account).

The concern is, once a user, logs in, in (for example) chrome, and tries to access the application again in a new tab, it just does not redirect to the B2C login page.

For example, if in tab-1 when I go to the application, I get the login page of the B2C custom policy. then I enter the mail address of one of my accounts and then the policy redirects me to the appropriate login method/page, based on the email domain. Now, I am logged in with user of tenant <tttt-tttt-tttt> and app registration of this tenant <aaaa-aaaa-aaaa>. Now when I go to the application in the new tab, tab-2,  it does not take me to the login page of the B2C custom policy. It directly takes me to the login page of <aaaa-aaaa-aaaa>.

Technically, in tab-2, either the user should see the login page of the B2C custom policy or should directly be able to access the application.

Is this the expected behaviour? Can this be fixed?

**Comment by JasSuri** [comment]
Because the policy is enabled for single sign on, the expectation is that the user has a single identity and would authenticate the same way every time. In tab 2, the expectation is that the user is SSOd into the application without interaction. If you are left hanging at the federated IdP, it indicates an SSO session problem at that IdP.

You can remove the session management technical profile references to prevent specific orchestration steps being skipped if that’s what you need. But that will break cookie based SSO, which is usually desired when tokens expire as a fallback.

**Comment by foramkumar-parekh** [comment]
@JasSuri can you elaborate more on this. Also if you can share, what we can try in policy or in the tenant/app registration settings, that would be helpful

**Comment by JasSuri** [comment]
Is the issue that the user is left hanging at the Idp in tab 2, or that you want to prompt for the email regardless of the users signed in state in tab 2?

**Comment by foramkumar-parekh** [comment]
The issue here is the user is left hanging at federated IDP. 
But if you can share the way to fix both the issues you mentioned, it would be better for us to decide which one to proceed with.

**Comment by JasSuri** [comment]
If the user is left hanging at the federated IdP, that is not a custom policy issue - that is an issue with the SSO configuration at the federated IdP.

To always prompt the user for the email, even in an SSO scenario, you have two options.
1. Set the policy SSO to disabled, follow this article [here]().
2. Set the SSO Management references to SM-Noop on the following technical profiles: `SelfAsserted-Signin-Email`, `SelfAsserted-LocalAccountSignin-Email`

Both options will cause silent token acquisitions using cookies to fail. Which means the maximum time the user can maintain a logon session to your application is governed by the [web session cookie lifetime](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy#configure-azure-ad-b2c-session-behavior). If you use implicit flow, then the maximum logon time will be equal to the access token lifetime.

**Comment by foramkumar-parekh** [comment]
I changed the msal cache setting from session storage to local storage and it worked.
