### ISSUE TITLE
The claims for verification control have not been verified.

### ISSUE THREAD

**Issue by Ponant** [azure-ad-b2c/samples#293]
I am sorry to leave this issue here rather than on the azure feedback / uservoice website since the latter is not available anymore.

The error is due to an upgrade of the selfasserted versions from 2.1.4 to 2.17  or 2.1.8 (versions in between not tested).

When using the password reset flow, we get at the end of the VerificationEmailControl the populated div (see picture)

````html
<div id="claimVerificationServerError" class="error pageLevel" style="display: block;" aria-hidden="false" 
role="alert" aria-live="polite" tabindex="1">The claims for verification control have not been verified.</div>
````

Other times the `display` is set to `none` but the message is here in the dev tools. There also seems to be a race condition, for example if a non-existing user tries to reset the pwd, then he should get a message of the sort "No account found with this email", whereas instead, often we get the error  "The claims for verification control have not been verified.".
The snapshot below was taken with a user that exist in the directory.

The error occurs with built-in password reset policies 2.1.7 and 2.1.8 (and petrhaps prior versions down to 2.1.5 included), or custom policies. Indeed we also have seen this in our website live with custom html.

We are serving pages in French and English so we will highly appreciate if someone could:

-Confirm or not if this is a bug
-What are we supposed to understand from this message
-Where can we narrow down this string as we did not found it in the localization jsons.

Thank you
![Capture1a](https://user-images.githubusercontent.com/19961806/135495391-2f859692-d5a5-496c-935e-8bb5655b1e40.PNG)

Edit : it seems to be only 2.1.7 and 2.1.8.

**Comment by JasSuri** [comment]
Appears to be a bug with the service, not any sample here - raise a support ticket with Microsoft.

**Comment by benedib1** [comment]
Has support for localization been added for this error message?

We are using verification controls and running into the same issue.
<DisplayControl Id="someIdControl" UserInterfaceControlType="VerificationControl">

I am able to reproduce the error during a password reset flow by:
1. input verification code into input box but DON'T verify the code
2. Attempt to submit the form.

We are also supporting multiple languages but there error message always displays in English, so we would like to localize this message.

**Comment by leandroamore** [comment]
hi, any update on this issue?

**Comment by kamilzzz** [comment]
Still awaiting response regarding localization of this error message...

**Comment by kamilzzz** [comment]
This error message can be localized using following StringId:
```
<LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfVerificationControlClaimsNotVerified">Abcdef.</LocalizedString>
```

I really don't understand why this isn't documented anywhere and why this issue is open for more than 6 months without any suggestion from product team how to localize this message.

It literally took me 30 minutes to find out solution by looking at traces generated by Application Insights.
```
"RecorderRecord": {
  "Values": [
    {
      "Key": "Validation",
      "Value": {
        "Values": [
          {
            "Key": "SubmittedBy",
            "Value": "SignUpWithLogonEmailExchange"
          },
          {
            "Key": "ProtocolProviderType",
            "Value": "SelfAssertedAttributeProvider"
          },
          {
            "Key": "Exception",
            "Value": {
              "Kind": "Handled",
              "HResult": "80131500",
              "Message": "ErrorTextKey: UserMessageIfVerificationControlClaimsNotVerified",
              "Data": {
                "IsPolicySpecificError": false
              }
            }
          }
        ]
      }
    }
  ]
}
```

**"Message": "ErrorTextKey: UserMessageIfVerificationControlClaimsNotVerified",**

Anyway, at least this is solvable.

**Comment by JasSuri** [comment]
Issues on docs should be raised on docs themselves. This repo is for B2C IEF policy samples, and this is not a bug in the sample itself per se. Creating the issue against the correct item will flag the correct team, or as mentioned, raise a support ticket for a product issue.

As part of selfAsserted technical profile, the localization docs [outline](https://docs.microsoft.com/en-us/azure/active-directory-b2c/localization-string-ids#sign-up-and-self-asserted-pages-error-messages):
> UserMessageIfClaimNotVerified | Claim not verified: {0}

If this is not clear, then raise a docs issue against the article.

**Comment by jtorresen** [comment]
Has anyone tried and achieved to override this string with the ElementType="ErrorMessage" StringId="UserMessageIfVerificationControlClaimsNotVerified"? 

When  I try to do it I get the response that it is not a valid override 
![image](https://user-images.githubusercontent.com/102551925/162837201-4b072875-444b-4caf-acc5-0e0589f08676.png)

(I've already tried it with the layout 2.1.10 and previous layouts for phone sign up and local account sign up, but I still get the same response)

**Comment by kamilzzz** [comment]
@jtorresen are you using User flows? I tested this even today and it works fine for me with custom policies.

**Comment by jtorresen** [comment]
Thank you for your response @kamilzzz. Yes, I'm using user flows, but I'm trying to change it through the language customization jsons. I'll try it now through the custom policies.

**Comment by EnzoGorlomi23** [comment]
@JasSuri I get a 200 message, followed by a 400. Very inconsistently. 

 {
              "name": "x-ms-cpim-trans",
              "value": "eyJUX0RJQyI6W3siSSI6IjliZDdjZW....................................................n0="
            }
          ],
          "content": {
            "mimeType": "text/json; charset=utf-8",
            "size": 88,
            "text": "{\"status\":\"400\",\"message\":\"The claims for verification control have not been verified.\"}"
          },

**Comment by Ponant** [comment]
@EnzoGorlomi23 , this randomness may be because you switch during testing in between hitting enter in the keyboard or using the mouse to click on the button. In the former case, if I remember, the error appeared to me on 2.8 and other versions. It took me some time to explain this to the support people, and below is their latest answer in late December 2021. I send them HAR files and videos of the flow. it is there in custom flows and built-in ones.
To check this your side, enter a random code in the input field (and not the one you received by email), and hit enter. The string should appear. If you try again and use your mouse to click the button, it should not occur. All this is recalls from my memory.

The error most likely it a server error from the assemblies that are used to check out the claim. I said this to the Azure guys.
In the mean time I had to go to production, so I used version 2.1.6 because it is out of question that I present this to users. 

To all,
They recognized this is a bug, but I am not sure it is solved yet. In the meantime 
On 21.12.2021
"XXX has been great, timely and available and did his best to communicate with the dev team at Azure as far as I can see.

However, the problem is not solved yet. I understand the Azure acknowledges this is a bug on the Azure B2C user-built-in flows, but I am still looking for an updated version of such policies to implement it in our platform.
Have a good day"

**Comment by EnzoGorlomi23** [comment]
@Ponant Agreed, this is a Azure b2c bug because API is sending different responses for clicking a button vs pressing enter button. I continue to use 2.1.9 and disabled the enter button using javascript. Thanks for getting back. Cheers!

**Comment by JasSuri** [comment]
> Inconsistent behavior would not be a policy bug, but maybe an issue in the service. Raise a support ticket with MS.

**Comment by thesheebs** [comment]
We have an open ticket with Microsoft for this issue. They have stated that it is the intended behavior and have been resistant in acknowledging that it is a bug. When a user clicks the "enter" key after entering the verification code, the error is show and the buttons are removed and the user cannot continue unless they refresh the page and try again. This is a common user action and more likely to cause issue for those using assistive technologies like a keyboard. I compared the script between version 2.1.6 and 2.1.10 and found the bug. 

1.	When the page loads the button is set to **aria-disabled=”false”** but should **true**
2.	The function _**updateContinueButton**_ is missing in versions 2.1.7 through 2.1.0
3.	The **_updateContinueButton_** function is never called on 2.1.10 because it is missing

### Code 2.1.6 
`return (
    '<button id="continue" type="submit" form="attributeVerification" aria-disabled="**true**" aria-label="' "<button>");
//
$("#continue").click(function (n) {
     if (n.target.getAttribute("aria-disabled") === "true")
       return !1;
      i.verify();
  });

//
**updateContinueButton: function () {
    for (var e = document.querySelectorAll("div.verify"),r = !0,f,t = 0;t < e.length;t++) {
      var n = e[t].getAttribute(u),o = i.getClaimValue(n),s = $("#" + n).prop("readonly") || !1;
      (!i.verificationInfo[n].input || i.verificationInfo[n].input != o || s) &&
        ((i.verificationInfo[n] &&i.verificationInfo[n].confirmation && i.verificationInfo[n].confirmation.success) ||(r = !1));
    }**
//
    i.initialize_DateDropdowns();
    i.initialize_VerifyState();
    **i.updateContinueButton();**
  $("#attributeList input").on("keypress", function (n) {
    if (i.serviceCallInProgress)
      return n.stopImmediatePropagation(), !1;
    i.isEnter(n) &&
      $("#continue")[0].getAttribute("aria-disabled") === "false" && (n.preventDefault(), i.verify());
  });

### Code 2.1.10
return (
    '<button id="continue" type="submit" form="attributeVerification" aria-disabled="**false**" aria-label="' "<button>");
//
$("#continue").click(function (n) {
    if (n.target.getAttribute("aria-disabled") === "true")
      return !1;
    i.verify();
  });
//
**// MISSING updateContinueButton function**
i.initialize_DateDropdowns();
i.initialize_VerifyState();
**// Missing function call**
  $("#attributeList input").on("keypress", function (n) {
    if (i.serviceCallInProgress)
      return n.stopImmediatePropagation(), !1;
    i.isEnter(n) &&
      $("#continue")[0].getAttribute("aria-disabled") === "false" && (n.preventDefault(), i.verify());
  });`

**Comment by wstaelens** [comment]
same issue. How did you resolve this? Updating a package or manually editing the javascript as above?

**Comment by thesheebs** [comment]
> same issue. How did you resolve this? Updating a package or manually editing the javascript as above?

We still have an open ticket with Microsoft. They have not fixed the bug. The current SeflAsserted version is 2.1.14 and the bug started in 2.1.7. You can revert to 2.1.6 until they release a fix, but they have been resistant in even calling it a bug, so not sure if they plan on fixing it anytime soon. Version 2.1.6 works perfectly will maintaining accessibility standards.

In general, overriding the API with JavaScript is not a good idea and generally leads to other issues or has unforeseen consequences.

**Comment by wstaelens** [comment]
We are having the same issue. Any fixes Microsoft?

**Comment by thesheebs** [comment]
> We are having the same issue. Any fixes Microsoft? We ourselves cannot reproduce it (location: Europe) but one of our customers has the same issue (location: USA) and tried different browsers and methods but without success.
> 
> (i've added location, but don't know if this is related)
> 
> **update:**
> 
> @thesheebs i've also created a ticket: Tracking ID: 7S9D-H88
> 
> @thesheebs can you also share your ticket id ? (in case somebody from microsoft looks at my ticket, i linked this github issue)

Microsoft has finally acknowledged that it is indeed a bug. They promised a fix by the end of last week (09.23.2022), but have yet to roll it out. Should be soon though. I am a bit skeptical given the resistance to calling it a bug and stating that the behavior is as expected and is for accessibility reasons.  I have informed them many times that you can meet accessibility requirements without causing a bug and that the **_Continue_** button should have **_aria-disabled="true"_** when the page loads. This lets a user on a screenreader know that the button is there, but not ready to be clicked. Then when the code is verified, **_Continue_** should be set to **_aria-disabled="false"_**. This is how it worked in 2.1.6. Because the continue button is no longer disabled in 2.1.7+, when a user enters the code and hits Enter on the keyboard, the **_Continue_** button is clicked and all the buttons are removed and cannot continue unless they refresh the page and start over.

**Comment by thesheebs** [comment]
Alas, after more than a year and a lot of persistence, Microsoft has fixed the bug.
SelfAsserted 2.1.17 and UnifiedSSP 2.1.8 are now available.

**Comment by Ponant** [comment]
@thesheebs could you say more about where you got this information from? I did not see those versions in the docs yet.
That is great news otherwise.

**Comment by wstaelens** [comment]
@Ponant I also don't see where @thesheebs gets these new version numbers. Nothing here on the Page layout versions history: https://learn.microsoft.com/en-us/azure/active-directory-b2c/page-layout

**Comment by thesheebs** [comment]
@Ponant @wstaelens 

I got the version numbers directly from Microsoft. We have an open ticket with them. They have not updated their website with the latest DataUri's. I have tested as have many other application teams consuming our application and the email verification is working as expected. The next button is disabled on load and active once the user verifies the 6-digit code. Entering or pasting the code and hitting **enter** on the keyboard no longer causes an error.

**Comment by Ponant** [comment]
@thesheebs , so you never need to localize the
`<LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfVerificationControlClaimsNotVerified">Abcdef.</LocalizedString>`?
Thank you

**Comment by thesheebs** [comment]
> @thesheebs , so you never need to localize the `<LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfVerificationControlClaimsNotVerified">Abcdef.</LocalizedString>`? Thank you
It does not have anything to do with localization. You should leave that as the default error or use a custom error. There may be other ways in which that error is triggered, but it the bug is fixed, so you will not see the error when you hit **enter** on the keyboard after entering the 6-digit code.

**Comment by Ponant** [comment]
OK @thesheebs that is good news. However, I think one should be careful because yet I fail to see why this localized string is here
if it is not hit (anymore). Maybe it will popup in another context, so it is better to give it a friendlier message than the default value, just in case.

**Comment by Ponant** [comment]
Issue confirmed also with SelfAsserted 2.1.17. Same procedure as previous comment.

**Comment by JasSuri** [comment]
You'll need to raise a MS Support request, as this is an issue with the service, and not with the XML sample that uses the service.
