### ISSUE TITLE
JIT Migrate from one B2C Instance to another not copying custom fields

### ISSUE THREAD

**Issue by xammob** [azure-ad-b2c/samples#294]
Hi, I'm trying to move b2c users from one tenant to another. I've managed to get this working using the 'JIT b2c->b2c migrate' custom policy sample which works fine. However, I've not been able to get custom field values to copy over. 
Just wondered if anyone knows if the login-Remote part of B2CMigrate_Extensions.xml is able to copy custom field values from the source tenant?

I was focusing in on this section
 
        <TechnicalProfile Id="login-Remote">
          <DisplayName>Remote Account SignIn</DisplayName>

and I've tried all sorts of combinations/permutations such as adding the custom field to the PersistedClaims along with the password, which does get saved in the new tenant

        <TechnicalProfile Id="Create-RemoteUserLocally">
          <DisplayName>Create Remote Account Locally</DisplayName>
          <Metadata>
            <Item Key="ClientId">blah blah</Item>
            <Item Key="ApplicationObjectId">blah blah</Item>
          </Metadata>
          <InputClaimsTransformations>
            <InputClaimsTransformation ReferenceId="copyEmailFromSignin" />
          </InputClaimsTransformations>
          <PersistedClaims>
            <PersistedClaim ClaimTypeReferenceId="password" PartnerClaimType="password" />
            <PersistedClaim ClaimTypeReferenceId="extension_MyCustomField"/>
          </PersistedClaims>            

thanks

**Comment by JasSuri** [comment]
You need to configure optional claims against the Remote AAD B2C directory. Since the sample uses the AAD endpoint of the remote AAD B2C directory, you can use this article: [Optional claims for AAD](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set).

Then you can add the output claims into the policy to capture them from the token:
```xml
<TechnicalProfile Id="login-Remote">
          ...snip...
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="given_name" />
            <OutputClaim ClaimTypeReferenceId="surName" PartnerClaimType="family_name" />
            <OutputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="name" />
            <OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="localAccountAuthentication" />
            <OutputClaim ClaimTypeReferenceId="isLocalUser" DefaultValue="false" AlwaysUseDefaultValue="true" />
            <OutputClaim ClaimTypeReferenceId="extension_myCustomField" PartnerClaimType="extension_GUID_MyCustomField" />
          </OutputClaims>
        </TechnicalProfile>
```

The partnerClaimType must be the exact claim name that you expect in the token from the remote Azure AD endpoint.

Then your `Create-RemoteUserLocally` will work as-is.

**Comment by xammob** [comment]
Thanks very much for replying. I'm afraid it's still not working but that's going to be my fault. Would you mind if I just run some things past you?

I'm using Azure b2c so the article you passed doesn't allow UI editing to specify the optional claims, which means I will have to edit the manifest manually. That's ok, but which app on the remote side do I edit? IdentityExperienceFramework or ProxyIdentityExperienceFramework?

I did edit both but that didn't seem to work at all, so I just edited IdentityExperienceFramework :) With something like this

"optionalClaims": {
		"idToken": [
			{
				"name": "extension_<guidvaluehere>_MyCustomField",
				"source": "user",
				"essential": false,
				"additionalProperties": []
			}
		],
		"accessToken": [],
		"saml2Token": []
	},

I then added the outputclaim to the login-Remote technical profile as you pointed out but it still doesn't look like the custom field is being returned.

 <OutputClaim ClaimTypeReferenceId="extension_MyCustomField" PartnerClaimType="extension_<guidvaluehere>_MyCustomField"/>

Apologies if I'm doing something silly.

thanks

**Comment by JasSuri** [comment]
The optional claims should be added to the `ProxyIdentityExperienceFramework` app. Try adding to the access token section also.
Also remember that the GUID will have **no** dashes.

**Comment by xammob** [comment]
Hi, yes I had app insights turned on. I've been checking the id_token returned and it doesn't contained the custom field. I even added another optional claim into the manifest (for the proxy app) and sure enough the new field (auth_time) did come through in the token

   "optionalClaims": {
		"idToken": [
			{
				"name": "extension_guidwithnodashes_MyCustomField",
				"source": "user",
				"essential": false,
				"additionalProperties": []
			},
            {
            "name": "auth_time",
            "essential": false
            }
		],
		"accessToken": [
			{
				"name": "extension_guidwithnodashes_MyCustomField",
				"source": "user",
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": []
	},

I've double checked again the value of the guid and it's the same number as the id of the 'b2c-extensions-app. Do not modify. Used by AADB2C for storing user data.' without the dashes. I've also used the same guid in graph api access to the tenant.

I also tried changing the PartnerClaimType to have a dot instead of the underscore and that didn't seem to work either.

**Comment by JasSuri** [comment]
This must be the issue

> When configuring directory extension optional claims using the application manifest, use the full name of the extension (in the format: extension_<appid>_<attributename>). **The <appid> must match the ID of the application requesting the claim.**

In this case, the appId will be the B2C-Extensions-App, but the requesting App will be the ProxyIEF App. The only way i can see this working is by referencing the B2C-Extensions-App where the ProxyIEF app is in the custom policy. But, we would need to modify the B2C-extensions-app to have permissions to the IEFApp - That is something untested.

**Comment by xammob** [comment]
ok, thanks again for taking the time to reply to my questions. I think I'll probably look to work around this by maybe post processing the users and getting the custom field data via the graph api
