### ISSUE TITLE
B2C_1A_TrustFrameworkExtensions_HostName.xml example file references foo.b2clogin.com - needs replacing

### ISSUE THREAD

**Issue by JeffGiroux** [azure-ad-b2c/samples#297]
The README has some good steps for replacing specific items with your b2c tenant name. However it appears to miss one. There is a hardcoded reference to foo.b2clogin.com. This too should be replaced and modified with your tenant name. Otherwise the block does not work.

Currently...
```
          <InputParameter Id="contains" DataType="string" Value="foo.b2clogin.com" />
```

Should be...
```
          <InputParameter Id="contains" DataType="string" Value="yourtenant.b2clogin.com" />
```

If you replace the foo reference with 'yourtenant', then the README instructions to do a replace-all of yourtenant with real tenant name will also catch this line too.

I replaced foo with my tenant name then reuploaded the file, blocking now works if I hit my tenant name directly instead of custom domain.

**Comment by JasSuri** [comment]
https://github.com/azure-ad-b2c/samples/commit/91c52481b62a272a608628b51d333c497aabb5a6#diff-06ae1c4e9f4e77f024bf0b8a5bf27889ef7d29d0909df5c05d43ac0f9778e806
