### ISSUE TITLE
Sign in with magic link

### ISSUE THREAD

**Issue by Kalanrk** [azure-ad-b2c/samples#302]
Sign in with magic link explains the policy in terms of OAuth / OpenID authentication, would it work for SAML authentication protocol as well? Is there any restrictions applicable on this context please? Thanks.
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link

**Comment by JasSuri** [comment]
It will not work with SAML Relying parties, because SAML does not have any notion of `id_token_hint`, this is an OpenId connect concept.
