### ISSUE TITLE
Update Powershell/Graph API example in link-local-account-with-federated-account

### ISSUE THREAD

**Issue by lmrisdal** [azure-ad-b2c/samples#309]
The current example uses the old Azure AD Graph API instead of Microsoft Graph. I am unable to figure out how to retrieve an access token for this example as all information I find is for Microsoft Graph.

When using an access token for Microsoft Graph, the endpoint unsurprisingly gives me the following error:
> Your access token has expired. Please renew it before submitting the request.

Please advice how to use the method currently described, or update the example to use Microsoft Graph (if possible)

**Comment by JasSuri** [comment]
https://github.com/azure-ad-b2c/samples/commit/e864b77001f99783eda30755fa74a6131d7c9a7f
