### ISSUE TITLE
When click 'Cancel' button password reset flow leads to "Error 401"

### ISSUE THREAD

**Issue by Kalanrk** [azure-ad-b2c/samples#310]
Hi all,

I'm using SAML B2C custom policies for SSPR and force password reset when first login, on this user journey functionality we're seeing "Cancel" button, when user click this displays the error page "Error 401 - Unauthorized". Sorry, your request could not be proccessed.

Questions:
1.  Can we hide “Cancel” button similar to “Change e-mail”
2.  Would it be possible to handle this using JS on choose of “Cancel” redirecting the control to sign-in login page?
3. OR any other better workaround please? Thanks.

**Comment by JasSuri** [comment]
“Cancel” button should send error message wrapped in a SAML assertion back to the service provider. Who gives the 401? Your application or AAD B2C?

**Comment by Kalanrk** [comment]
@JasSuri I'm sure the 401 error message is from SP/application.  Is there any options on custom policies OR Azure AD B2C IEF / Manifest to specify on choose of "Cancel" redirect the control to the initial sign-in page? OR Do we need to handle this using javascript on our HTML page layout pls? Thanks.

**Comment by Kalanrk** [comment]
We've handled this using JS to redirect the control to sign-in page on choose of cancel. Thanks.

**Comment by JasSuri** [comment]
You need to handle this error in your App.
