### ISSUE TITLE
SAML compatibility for username or email based sign-in

### ISSUE THREAD

**Issue by Kalanrk** [azure-ad-b2c/samples#311]
Hi all,

I've implemented local account email as login-id using b2c custom policy sign-in for my SAML-based application.
However, now I want to enhance the custom policy which should allow user to sign-in using their username or email-id.
Hope I can take this as an example https://github.com/azure-ad-b2c/samples/tree/master/policies/username-or-email

Just want to make this is achievable for SAML based application pls? Could someone who has tried confirm this before I start working on this pls? Thanks.

**Comment by JasSuri** [comment]
All samples work for SAML and OIDC.

**Comment by Kalanrk** [comment]
Thanks Jas.
