### ISSUE TITLE
Signup Error from when click signup button.

### ISSUE THREAD

**Issue by Kalanrk** [azure-ad-b2c/samples#317]
Hi all,

I've deployed started pack b2c custom policies using automated tool. Registered SAML application by following MS guidelines.
I can see B2C login screen with sign-in and Sign-up buttons. However, when I click sign up, getting an strange error **"The page cannot be displayed because an internal server error has occurred."**  - Please note sign-in function works fine, wondering why sign-up not working its same user journey for both sign-in and sign-up i.e OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin" - unified?local=signup&csrf_token URL param returns this error.

Not sure, what settings could possibly gone wrong here? I've successful use cases for other tenant and followed the same exact approach. I greatly appreciate if you can shed some light on this pls. Pls refer the screen-shot below.

![image](https://user-images.githubusercontent.com/27288391/141466575-b8d4e937-5331-4c34-96f9-3a31a3334726.png)

![image](https://user-images.githubusercontent.com/27288391/141466303-092cdcb8-94ed-4df3-a82b-a4613ec0fc7d.png)

**Comment by JasSuri** [comment]
Share your user journey and technical profiles related to the sign in and sign up steps.

**Comment by JasSuri** [comment]
Continue on SO

https://stackoverflow.com/questions/69946164/azure-b2c-custom-policy-sign-up-not-working-error-the-page-cannot-be-displayed

**Comment by Kalanrk** [comment]
Thanks @JasSuri
