### ISSUE TITLE
Passwordless Email Configuration - How to remove fb sign-in pls

### ISSUE THREAD

**Issue by Kalanrk** [azure-ad-b2c/samples#318]
Hi @JasSuri  / All,
I've managed to configure password less sign-in and it works fine.
However, want to remove social account login that appears on screen as we only use local accounts,
Any suggestions pls? - Thanks.
![image](https://user-images.githubusercontent.com/27288391/141679446-bb6c4985-0329-4b57-a807-e14366ec62db.png)

**Comment by Kalanrk** [comment]
Managed to remove Facebook button by commenting TargetClaimsExchangeId. 
However, still seeing the text "Sign in with your social account. It looks no meta data level or custom policy settings to remove this text? Only option is to modify the custom UI html file content? Please confirm. Thanks. 
![image](https://user-images.githubusercontent.com/27288391/141699033-69e3f341-7c04-4915-b5c4-3c922934f833.png)

**Comment by JasSuri** [comment]
When you add `TargetClaimsExchangeId`, they always get set under this field.
You can localize the field to some other text [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/localization-string-ids#sign-up-or-sign-in-page-elements) - `social_intro`.

**Comment by Kalanrk** [comment]
Fantastic, that worked fine. Thanks Jas.
