### ISSUE TITLE
How to append federated identities at sign-up/sign-in attempt? 

### ISSUE THREAD

**Issue by RaphaelSilv** [azure-ad-b2c/samples#321]
Hi all,

following the [Azure AD B2C account linkage](https://github.com/azure-ad-b2c/samples/tree/master/policies/account-linkage-at-signup#azure-ad-b2c-account-linkage) I was able to successfully achieve `Scenario 1` and `Scenario 2` .

However, when I attempt to federated sign-up/sign-in for the second time using an account attached to the same email used first, a new user is created in contrast to an identity append.

The sample [account-linkage-unified](https://github.com/azure-ad-b2c/samples/tree/master/policies/account-linkage-unified) seems the way to go, but from my understanding, the **linkage** must happen intentionally from the user.

which is reinforced at the account linkage sample:
>The sample on account linkage [unified] shows you how the user can correct the problem by joining the two accounts, but that is **active** action by the user.

## Scenario and expected identities

User `foo` uses the same `foo@email.com` for Facebook, Microsoft, Google, and Twitter accounts;

He does attempt to federated sign-up/sign-in using each of these accounts;

Expected accounts: 1
Expected identities:

```json
{
  "displayName": "Foo Smith",
  "identities": [
    {
      "signInType": "userPrincipalName",
      "issuer": "contoso.onmicrosoft.com",
      "issuerAssignedId": "foo@email.com"
    },
    {
      "signInType": "federated",
      "issuer": "facebook.com",
      "issuerAssignedId": "5eecb0cd"
    },
    {
      "signInType": "federated",
      "issuer": "live.com",
      "issuerAssignedId": "345678"
    },
    {
        "signInType": "federated",
        "issuer": "google.com",
        "issuerAssignedId": "345678"
    },
    {
        "signInType": "federated",
        "issuer": "twitter.com",
        "issuerAssignedId": "345678"
    }
  ]
}
````

**Comment by JasSuri** [comment]
None of the samples demonstrate how to detect and link accounts, or check for linked account before trying to create a new one. Essentially you need to decide on a linking factor (eg email) and then perform read operations based on the email and alternativeSecurtyId to see if a match is found.

The samples demonstrate tools on how accounts can be linked - only.

I have a new sample which I shall share in the coming week which is a real world scenario as you mention. Allowing accounts to be linked when the email is detected as the same, and also signing the user into that single account on every logon regardless of the IdP the user used.

**Comment by RaphaelSilv** [comment]
Thanks for your answer, @JasSuri.

Indeed none of the samples show how to link existent accounts with external IDPs by detecting them automatically. Look forward to your sample!

However, could you please elaborate further on
> Essentially you need to decide on a linking factor (eg email) and then perform read operations based on the email and alternativeSecurtyId to see if a match is found.

Also, would the only alternative to your scenario deliberately ask users to link accounts at the sign-in?

**Comment by JasSuri** [comment]
So it depends what you prefer, I always recommend it to work like this:
1. User sign in with FB
2. FB email matches an account in B2C directory
3. Present screen which forces the user to login with matched account using any one of the IdPs detected on that account (maybe Local and Google are registered already to it). We do this by analyzing the identities collection on the account.
4. If the user manages to login to this account, then link FB to it.
5. Now the account has FB, Google and Local identities.

Of course, you can skip step 3 entirely if you like. But that poses some security concerns. Especially if your FB has a weak password, but your Google needs MFA.

**Comment by JasSuri** [comment]
Try the [auto account link sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/auto-account-linking).

**Comment by RaphaelSilv** [comment]
Hi @JasSuri, many thanks for your anticipating the release of this sample. I really appreciate it.

 I´ve been trying to get it running but some issues are blocking me.

Initially, I was getting the error: `"login-NonInteractive" defines an invalid value "" for the metadata item "client_id."` I referred to this GitHub [issue](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/issues/57) that pointed out I was missing a few steps from the starter pack.

So, I´ve added the `TrustFrameworkBase.xml` from the official [starter pack sample](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/SocialAndLocalAccounts/TrustFrameworkBase.xml) alongside the two policies and referenced it from `B2C_1A_AccountLink_Extensions`.

At the extensions file under Azure Active Directory ClaimProvider I added the following piece of code in order to address the missing `client_id` error:

```xml
<TechnicalProfile Id="login-NonInteractive">
     <Metadata>
         <Item Key="client_id">{Settings:LocalAccountClientId}</Item>
         <Item Key="IdTokenAudience">{Settings:LocalAccountIdTokenAudience}</Item>
     </Metadata>
      <InputClaims>
         <InputClaim ClaimTypeReferenceId="client_id" DefaultValue="{Settings:LocalAccountClientId}" />
         <InputClaim ClaimTypeReferenceId="resource_id" PartnerClaimType="resource" DefaultValue="{Settings:LocalAccountIdTokenAudience}" />
      </InputClaims>
</TechnicalProfile>
```

Now, I can successfully upload the policy files but can´t signup or sign in as get the following errors:
- Microsoft social login
![microsoft-login error](https://user-images.githubusercontent.com/42193694/142911259-badb3ca2-9959-478e-ac50-187a68e3f553.png)

- Facebook Social Login
![facebook-login-error](https://user-images.githubusercontent.com/42193694/142911633-8a505f60-a736-4c79-92c9-fb87adb49d86.png)


Note: I am using my own Microsoft and Facebook application credentials.

Please, what am I missing? Here you can find my [sample file](https://github.com/RaphaelSilv/AccountLinkSample).

**Comment by JasSuri** [comment]
### Your first issue
This sample uses extension attributes. Your correlationId shows that the failure was because we could not write to the extension attribute using technical profile `AAD-WriteUserHasPassword`.

Follow the pre reqs fully. I highly advise using my tools to install the starter pack, which also configures support for extension attributes. Then use the quick deploy link to deploy the sample.

### Your second issue
Something wrong with your FB technical profile, or FB App registration.

**Comment by RaphaelSilv** [comment]
Yes indeed! I fixed a typo on my FB `AppId` and after adding the extensions attributes I could get it running :) Many tks!!

However, I notice that after signing up a user using a local account and trying to merge an FB account I got an internal server error after clicking on **Sign in with you email**.

> The page cannot be displayed because an internal server error has occurred.

![link_email](https://user-images.githubusercontent.com/42193694/143065376-2d6fe9c4-9aa1-4cc2-bdc2-c49ede220b91.PNG)

Steps to reproduce:
1. Sign up a user using a local account
2. Try to sign in with Facebook
3. Click on  **Sign in with your email**.


The expected output would be the actual Facebook login process and finally, both social and local accounts merged.

**Comment by JasSuri** [comment]
I couldn't reproduce the issue.
In the HTML DOM Explorer - there will be a correlationId. Please share that here whilst reproducing the error.

It looks like:

**Comment by RaphaelSilv** [comment]
Sorry but I couldn´t find anything:

![CorrelatioId](https://user-images.githubusercontent.com/42193694/143260679-e50632ea-c295-4711-93b4-fdbb63ba14c3.png)

**Comment by RaphaelSilv** [comment]
@JasSuri I will push the error above a bit forward, as it´s not that critical at the moment. Right now I am replicating the MS and FB technical profiles to have Google and LinkedIn IdPs working as well.

For LinkedIn, I followed the same structure of defining a Base, SignIn, and Link technical profiles and properly referenced those at the orchestration steps. However, when trying to sign in with LinkedIn however, I got the following error:


```
AADB2C90037: An error occurred while processing the request. Please contact the administrator of the site you are trying to access.
Correlation ID: fe8c8eef-3da4-4344-8928-1a95e17f23ea
Timestamp: 2021-11-24 15:11:44Z
```

I asked the owner of the tenant I am working on to enable Application Insights so I can quickly refer to such errors. My apologies for any inconvenience.

---
- FWIW: [My B2C_1A_AccountLink_Extensions.xml](https://github.com/RaphaelSilv/AccountLinkSample/blob/main/B2C_1A_AccountLink_Extensions.xml).

**Comment by JasSuri** [comment]
` Claim with id 'socialEmail' was not found in the collection. `

Whatever claim is being mapped in LinkedIn technical profile for `socialEmail`, is coming back null.

**Comment by RaphaelSilv** [comment]
Precisely! By default, the LinkedIn API does not return the email field, so it needs to be fetched in another TechnicalProfile. The following solved the issue.

```xml
  <ClaimsProviders>
    <ClaimsProvider>
      <DisplayName>REST APIs</DisplayName>
      <TechnicalProfiles>
        <!-- Obtain an user email address from linkedIn api -->
        <TechnicalProfile Id="API-LinkedInEmail">
          <DisplayName>Get LinkedIn email</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
              <Item Key="ServiceUrl">https://api.linkedin.com/v2/emailAddress?q=members&amp;projection=(elements*(handle~))</Item>
              <Item Key="AuthenticationType">Bearer</Item>
              <Item Key="UseClaimAsBearerToken">identityProviderAccessToken</Item>
              <Item Key="SendClaimsIn">Url</Item>
              <Item Key="ResolveJsonPathsInJsonTokens">true</Item>
          </Metadata>
          <InputClaims>
              <InputClaim ClaimTypeReferenceId="identityProviderAccessToken" />
          </InputClaims>
          <OutputClaims>
              <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="elements[0].handle~.emailAddress" />
              <OutputClaim ClaimTypeReferenceId="socialEmail" PartnerClaimType="elements[0].handle~.emailAddress" />
          </OutputClaims>
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
    ...
 </ClaimsProvider>
```

---
- More: [Set up sign-up and sign-in with a LinkedIn account using Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-linkedin?pivots=b2c-custom-policy#test-your-custom-policy)

**Comment by RaphaelSilv** [comment]
Now, the issue I have mentioned [here](https://github.com/azure-ad-b2c/samples/issues/321#issuecomment-976828099) is the current blocker. If I first sign up using a local account and try federation with any of the IdPs I got the error:

> The page cannot be displayed because an internal server error has occurred.

With Application Insights enabled, now I can access the logs of these errors, but it doesn't tell me much.

Here's a piece of it:


```json
[
    {
        "Kind": "Headers",
        "Content": {
            "UserJourneyRecorderEndpoint": "urn:journeyrecorder:applicationinsights",
            "CorrelationId": "5cb66cbd-d074-407d-a0d1-8c2eff152f65",
            "EventInstance": "Event:API",
            "TenantId": "foo.onmicrosoft.com",
            "PolicyId": "B2C_1A_AccountLink_SUSI"
        }
    },
   
   "Complex-CLMS": {
                    "issuerUserId": "id",
                    "givenName": "Raphiat",
                    "surname": "Ramos",
                    "displayName": "Raphiat Ramos",
                    "socialEmail": "foobar@gmail.com",
                    "email": "foobar@gmail.com",
                    "identityProvider": "facebook.com",
                    "authenticationSource": "socialIdpAuthentication",
                    "upnUserName": "09f246e5-20b6-49e5-bbb5-b7df24e85a75",
                    "userPrincipalName": "cpim_<>@<>.onmicrosoft.com",
                    "userIdentity": "Microsoft.Cpim.Data.UserIdentity",
                    "userIdentities": "System.Collections.ObjectModel.Collection`1[Microsoft.Cpim.Data.UserIdentity]",
                    "objectId": "<>",
                    "localAccountEmail": "foobar@gmail.com",
                    "currentUserIdentities": "System.Collections.ObjectModel.Collection`1[Microsoft.Cpim.Data.UserIdentity]",
                    "extension_haspassword": "True",
                    "localAccountUpn": "bar@foo.onmicrosoft.com",
                    "currentIssuers": "Null",
                    "containsIssuerAlready": "False"
                },
   ]
```

Is there anything else I can share?


---
- FWIW: [My B2C_1A_AccountLink_Extensions.xml](https://github.com/RaphaelSilv/AccountLinkSample/blob/main/B2C_1A_AccountLink_Extensions.xml).

**Comment by JasSuri** [comment]
In your repo, you've removed this for some reason, and its causing the failure.

**Comment by RaphaelSilv** [comment]
Precisely, again! Many thanks!

So, now the issue is gone, but I noticed that when I successfully sign in with a social account I'm prompted to enter the password I defined for the local account and then both accounts are merged. 

![image](https://user-images.githubusercontent.com/42193694/143583625-2cfda489-499a-45e8-abc2-defba8730ec6.png)

Is this the expected behavior? It is as if a new step was added to **Scenario 1**:

- User has a Local Account (bob@contoso.com)
- User logs in with Facebook, and Facebook returns the email claim - bob@contoso.com
- User is presented with a screen to login with their Local Account
- User logs in with the Local Account
- **User is prompted to enter Local Account password**
- Facebook account is merged with Local Account

**Comment by JasSuri** [comment]
It’s expected, and implied by 
> User logs in with the Local Account

The only way to login to the local account is username/password. I can make it clearer.

**Comment by RaphaelSilv** [comment]
Got it! Thank you very much for all the support @JasSuri!!

**Comment by Veeraj1996** [comment]
@JasSuri : Can you please help me to skip the 3 step so that I want to skip the user to signin with its existing account though your caution seem to be valid.

https://github.com/azure-ad-b2c/samples/issues/321#issuecomment-973889076

I **dont** want to present screen which forces the user to login with matched account using any one of the IdPs detected on that account (maybe Local and Google are registered already to it).

Waiting for your reply.
Thanks in advance
