### ISSUE TITLE
Passwordless Email Input Claims

### ISSUE THREAD

**Issue by Kalanrk** [azure-ad-b2c/samples#324]
Hi @JasSuri / all,

I'm using Azure B2C SAML application.
I'm trying to minimize the claim data that we collect from user during sign-up process, the purpose is to anonymous the user input values and minimize the user inputs for sign-up process.
Is there any way to set the default values for First Name and Surname and still I need to send these output claims to SAML Requester(SP), at the same time dont want to display these fields on sign-up page please? Any example and MS document reference will be helpful. 

At this moment, I'm setting the default values "Anonymous" to first name and last name to send these claims to SP, (so I could not comment this out) currently displaying these fields with the note "OR Leave Blank".  My requirement is to hide these first name and last name fields and still want to send these default values to SP.
 
![image](https://user-images.githubusercontent.com/27288391/142858349-1859d2ba-83ac-4853-bc42-7a0053149bbb.png)

**Comment by JasSuri** [comment]
Remove the output claims from the selfAsserted technical profile. Add the output claims in the relying part section with a defaultValue set for them. This is better posted on stackoverflow.

**Comment by Kalanrk** [comment]
@JasSuri That's excellent, worked fine. Just one last clarification on this password-less journey, the same way I hope that we can suppress email address input as well by assigning default email-id value. (we don't really care about duplicate email-ids) Is there any way to turn off this error and allow to sign-up with a duplicate email-id pls? (i.e. A user with the specified ID already exists. Please choose a different one.) Thanks again.

**Comment by JasSuri** [comment]
Yes, set `RaiseErrorIfClaimsPrincipalAlreadyExists` to `false` in the technical profile that writes the account.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-technical-profile#metadata

**Comment by Kalanrk** [comment]
Thanks @JasSuri That helped really to get rid of the validation error message.
I've tried to hide email address input field as well by following the same way that we hidden first name and last name, however this is not successful with SP response error message An error occurred while processing the request. Please contact administrator of the site you are trying to access.". Is this something out of Azure scope and something to deal with SP. Isn't it? Thanks.
Commented out below lines on B2C_1A_TRUSTFRAMEWORKEXTENSIONS and passing default output claim email value from relying party.
