### ISSUE TITLE
Terms of Use not appearing for new account creation

### ISSUE THREAD

**Issue by DI-James** [azure-ad-b2c/samples#329]
Hi!

We were having some issues with getting the Terms agreement to appear on a sign-up page.  It looks like line 291 in TOU_SUSI_TrustFrameworkExtensions.xml may need to be changed:
current
`<ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmail" />`

proposed
`<ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmailCustom" />`

Without the change it was writing the date attribute without a user needing to consent, since it appears to default to the LocalAccountSignUpWithLogonEmail Technical Profile in the TrustFrameworkBase.xml

It appears to be the same case with the version of this for social login.

**Comment by JasSuri** [comment]
Updated with fix.
