### ISSUE TITLE
How to render two policies within the same HTML file?

### ISSUE THREAD

**Issue by RaphaelSilv** [azure-ad-b2c/samples#332]
Hello, is it possible to achieve the aimed scenario?

```HTML
<!DOCTYPE html>
<html>
<head>
    <title>My Product Brand Name</title>
</head>
<body>
    <!-- api.localaccountsignup section -->
    <div id="api1"></div>
    <!-- api.signuporsignin -->
    <div id="api2"></div>
</body>
</html>
```

Ideally I'd have a frontend that hosts local account signup and signup or signing, as the image below
![image](https://user-images.githubusercontent.com/42193694/146089606-73827930-f75d-422f-a5cd-52e747046287.png)

**Comment by JasSuri** [comment]
This needs to go on Stackoverflow, not an issue with a policy here.

**Comment by RaphaelSilv** [comment]
FWIW: https://stackoverflow.com/questions/70362896/how-to-render-two-custom-policies-within-the-same-html-file-on-azure-b2c
