### ISSUE TITLE
Focus order on b2c login page

### ISSUE THREAD

**Issue by samspade** [azure-ad-b2c/samples#334]
On the b2c login page. The username and password fields have a tabindex="1" so that they receive focus before any other content on the page which is not the natural flow of the document.

![image](https://user-images.githubusercontent.com/900214/146172019-f51725e0-c974-4e8a-95ee-09976f1436eb.png)

If I put content that can receive focus above the username and password (e.g. images) then they are skipped by a keyboard user. This was flagged during an accessibility review as a 2.4.3 Focus Order – Level A defect in WCAG 2.1.  

Are there any workarounds or plans to remove the tabindex from these fields so they can sit in the natural flow of the document?

**Comment by JasSuri** [comment]
Raise a support ticket through the Azure Portal.
