### ISSUE TITLE
Using password-history custom policy example

### ISSUE THREAD

**Issue by pd-sgdev1** [azure-ad-b2c/samples#337]
Hi,

I would like to make use of the "password-history" custom policy but I could not get it to work properly. I'm just getting the "Unable to validate information provided".

![image](https://user-images.githubusercontent.com/45959463/147156073-abb94f92-4e4e-462b-a76e-d78112864c19.png)

I have setup the required Azure services (e.g., app service, key vault), uploaded the custom policies in the following sequence

- TrustFrameworkBase
- TrustFrameworkExtensions
- TrustFrameworkLocalization
- SignUpOrSignin
- HistoryPasswordReset

**Checks done so far**
- SignUp and SignIn is working
- API service has access to the Azure Key vault.
- There are no requests coming into the PasswordHash API service when duing "forgot password" flow

Am I missing some steps here? Appreciate if you could provide any tips/guides on how to get it working.

Thanks
Ken

**Comment by JasSuri** [comment]
You can also troubleshoot by getting the logs:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/troubleshoot?pivots=b2c-custom-policy#troubleshooting-with-application-insights

In the HTML DOM, there will be a correlationId right at the top, post that here.

![image](https://user-images.githubusercontent.com/38688240/147262350-0cd1b6c3-3a2e-4449-8a8b-2f3fc9d1f3be.png)

**Comment by pd-sgdev1** [comment]
Hi @JasSuri, please refer to the correlation Id `4b81e020-0384-4806-a328-83cd8f3d51f3`

**Comment by JasSuri** [comment]
1. Go to the Azure AD B2C blade in the Azure Portal.
2. Go to the Identity Experience Framework menu -> Policy Keys menu
3. Create a new Policy key
4. Give it the name AccountTransformSecret, choose secret, and generate options

**Comment by pd-sgdev1** [comment]
@JasSuri Think I figured it out. thanks

**Comment by JasSuri** [comment]
What did you do to fix it? Then we can update the instructions.

**Comment by pd-sgdev1** [comment]
It was the missing policy key as what you've mentioned - managed to figure it out after posting the exception message here.

**Comment by pd-sgdev1** [comment]
One more question, if I may add. 

How do I link call this password reset policy from the SignUpOrSignIn policy?

Thanks

**Comment by pd-sgdev1** [comment]
@JasSuri How do you call the password-history policy when user clicks on the "Forgot your password?" link?

![image](https://user-images.githubusercontent.com/45959463/148678325-a4c418e2-f890-4673-bc8f-4b10b657c79d.png)

**Comment by JasSuri** [comment]
Sand approach as [this](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy#self-service-password-reset-recommended).

Just put this samples password reset journey into the subjourney, instead of what’s in the doc.

**Comment by pd-sgdev1** [comment]
I see. thanks.

What was the reason for having custom password reset policy in a separate file in the example? So moving forward, all custom policies need to reside in the TrustFrameworkExtensions.xml?

**Comment by JasSuri** [comment]
The doc works with what you would have as a pre-req, which is the B2C starter pack.
In all samples in this repo, they _connect_ to the starter pack. Its easier to manage.
