### ISSUE TITLE
Migrate user when filled in password is incorrect. (not before password is checked)

### ISSUE THREAD

**Issue by Tvde1** [azure-ad-b2c/samples#338]
When a user logs in (`SelfAsserted-LocalAccountSignin-Email`), the last step is `login-NonInteractive` and verifies the password.

Is it possible when this password is incorrect, to then call a 3rd party API, and if `200 OK`, use this new password as the B2C user password and log the user in successfully?

This is because migrated users might change their password at the old IDP, in which case we have to verify whether a user has logged in with a password which is incorrect but correct in the third party IDP.

This will only happen to a handful of users, so we'd rather not call the 3rd party IDP every signon

**Comment by JasSuri** [comment]
Yes, its possible.

- Add the flag `ContinueOnError="true" to `login-noninteractive`. See [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/validation-technical-profile#validationtechnicalprofiles).
- Add a defaultValue to objectId outputclaim in `login-noninteractive`.
- Then add a validationTechnicalProfile to execute with precondition matching the defaultValue set in the above step to call the 3rd party IdP via REST

This means, the validation technical profiles will continue to execute after login-noninteractive fails. 
In the case of failure, objectId is set to some known default value. And this will then force the next validation technical profile to run, which check the password at the 3rd party IdP.

Test thoroughly. Follow up on stackoverflow for more design discussion.

**Comment by Tvde1** [comment]
Thank you for the response! Be warned, when setting a `DefaultValue` for `login-noninteractive` there seems to be no way to get the error message to display when `ContinueOnError="false"` is set on another step.
