### ISSUE TITLE
incorrect value in custom policy for deep link to signup

### ISSUE THREAD

**Issue by lemenhir** [azure-ad-b2c/samples#339]
https://github.com/azure-ad-b2c/samples/blob/374499e49e29dd910c9f01b7bdac919bcbbdb8ef/policies/sign-up-deep-link/policy/TrustFrameworkExtensions.xml#L28

The current value is "singup".
Must be changed to "signup".

**Comment by JasSuri** [comment]
Fixed: https://github.com/azure-ad-b2c/samples/commit/b6ade7de339932ec7cf7bc4fad3ef0874c8227bf
