### ISSUE TITLE
b2ciefsetupapp.azurewebsites.net broken

### ISSUE THREAD

**Issue by r2musings** [azure-ad-b2c/samples#342]
I get this after entering credentials. 

This b2ciefsetupapp.azurewebsites.net page can’t be foundNo webpage was found for the web address: https://b2ciefsetupapp.azurewebsites.net/Error?msg=QUFEU1RTNTAwMjAyOiBVc2VyIGFjY291bnQgJ3tFbWFpbEhpZGRlbn0nIGZyb20gZXh0ZXJuYWwgaWRlbnRpdHkgcHJvdmlkZXIgJ2xpdmUuY29tJyBpcyBub3Qgc3VwcG9ydGVkIGZvciBBUEkgdmVyc2lvbiAnMi4wJy4gTWljcm9zb2Z0IGFjY291bnQgcGFzcy10aHJ1IHVzZXJzIGFuZCBndWVzdHMgYXJlIG5vdCBzdXBwb3J0ZWQgYnkgdGhlIHRlbmFudC1pbmRlcGVuZGVudCBlbmRwb2ludC4NClRyYWNlIElEOiBiZTFiODVjYy0xZTdlLTRjODAtYTAwNy1jNzJmOTcyZGMzMDANCkNvcnJlbGF0aW9uIElEOiBmM2M2MTY2Yi1kNGUyLTRmYWUtODhhOS1lN2RhODlkZWFhNWQNClRpbWVzdGFtcDogMjAyMi0wMS0xNiAxODowMDoyM1o
HTTP ERROR 404

**Comment by JasSuri** [comment]
Works ok here. Try incognito window.

**Comment by r2musings** [comment]
Thanks.  I ended up just doing it all manually.

**Comment by JasSuri** [comment]
> Thanks. I ended up just doing it all manually.

Ouch, we are trying to avoid that!
