### ISSUE TITLE
Issue when opening multiple tabs of a same Policy

### ISSUE THREAD

**Issue by romain030992** [azure-ad-b2c/samples#343]
Hello,

I noticed a really weird issue when opening two tabs running the same policy. The steps are the following ones :

- Open SignupOrSignin policy
- Navigate to the signup part
- Fill in the form
- Submit the form
✅ Everything is fine

- Open SignupOrSignin policy (tab1)
- Navigate to the signup part
- Fill in the form
- Open SignupOrSignin policy in another tab (tab2)
- Submit the form in the tab 1
❌ There is an error saying the email is requested. Seems like the claim is reset. Maybe something related to the cookies...

Do you know if this issue is documented somewhere and if a fix is possible ?

I also tested this behavior with User flows and I had the same issue (but with missing password).

Thank you for your help.

**Comment by JasSuri** [comment]
Known issue. There is no fix available for it.
