### ISSUE TITLE
App insights instrumentation key left in sample

### ISSUE THREAD

**Issue by DavidAtImpactCubed** [azure-ad-b2c/samples#345]
In the Send Grid sample an App Insights instrumentation key has been left in place. I'm guessing this is in error as it is not related to SendGrid, and appears to be a real key.

https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-email-verifcation-displaycontrol/policy/SendGrid/DisplayControl_PasswordReset.xml

<JourneyInsights TelemetryEngine="ApplicationInsights" InstrumentationKey="c5b9a7ce-3135-442d-b825-fa2be4f61189" DeveloperMode="true" ClientEnabled="false" ServerEnabled="true" TelemetryVersion="1.0.0" />

**Comment by yoelhor** [comment]
Thanks @DavidAtImpactCubed for your feedback. The API has been removed. For more information, please see the commit.
