### ISSUE TITLE
Custom Policy throws an error in Browser Console

### ISSUE THREAD

**Issue by aptyp-tyt** [azure-ad-b2c/samples#346]
Used: Custom Policy without enabling JavaScript, LoginRedirect Flow
Browsers: Edge, Chrome, and others with the same Engine

Any action (sign in, reset the password, cancel, continue, etc.),  throws the next errors in Browser Console:
![image](https://user-images.githubusercontent.com/48277797/151930397-96f3fb5d-4527-454d-9e2b-3254fe9fc2cc.png)

**Comment by JasSuri** [comment]
Appears to be a service issue, not specific to any sample, raise a support ticket with Microsoft.
