### ISSUE TITLE
Policy.ReadWrite.TrustFramework

### ISSUE THREAD

**Issue by hpaterson-abcam** [azure-ad-b2c/samples#349]
i am using a service principle that has global admins access to the b2c tenant but get an auth error

Uploading:
	B2C_1A_BASE
{
   "error": {
      "code": "AADB2C",
      "message": "The application does not have any of the required application permissions (Policy.ReadWrite.TrustFramework) to access the resource. ",
      "innerError": {

**Comment by hpaterson-abcam** [comment]
the service principle need Policy.ReadWrite.TrustFramework  permission within the b2c, the service principle in the main AD tenant access did not pass through

**Comment by JasSuri** [comment]
Azure AD tenant is completely isoalted tenant to AAD B2C tenant.
If you want to call Graph API of a particular tenant, then you have to create an App Reg/ServicePrincipal pair in the respective tenant.
