### ISSUE TITLE
mark email as read only / set focus to password field

### ISSUE THREAD

**Issue by thdotnet** [azure-ad-b2c/samples#350]
I'm using the ready to use User Flow available for SignUpIn. I've figure out it's possible to pass the email using the querystring parameter login_hint, but the focus stays on the email field and my customer wants to avoid an additional 'tab' in order to speedup the login process.

I also found a [sample ](https://medium.com/the-new-control-plane/upskilling-on-azure-b2c-custom-policies-adding-a-new-page-to-the-journey-1e66aeadbff3)which splits a login journey in two steps, but I can't find a way to go directly to the second step, as it uses csrf in order to validate the flow started from Azure AD B2C.

Questions:

1-Is it possible to mark email as readonly when passing a value from login_hint querystring parameter?

2-In case question #1 it's not possible, is it possible to set the focus to the password field?

3-using the custom Custom CIAM User Journeys, can I go directly to the second assuming I already know the email?

**Comment by JasSuri** [comment]
You can use JavaScript to change which textbox is in focus on page load.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/javascript-and-page-layout?pivots=b2c-custom-policy

You can resolve query string parameters, and perform some logic on them to drive the custom policy journey where you want, eg skipping directly to some other orchestration step.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/claim-resolver-overview
