### ISSUE TITLE
Rename userinfo claim

### ISSUE THREAD

**Issue by jabbera** [azure-ad-b2c/samples#357]
Hi!

I feel very incompetent after trying to accomplish this simple task. All I'd like to do is rename the output claim from signInNames.emailAddress to email. Does anyone have an example or anything that they can point me to. I'll be forever in your debt and would purchase you a reasonably priced beverage or meal if we ever met IRL.

https://github.com/azure-ad-b2c/samples/blob/7397a61fd13073d82202bbe6e3e3f80030256ec8/policies/user-info-endpoint/policy/UserInfo_TrustFrameworkExtensions.xml#L39

**Comment by JasSuri** [comment]
Try

**Comment by jabbera** [comment]
Thanks. That didn't work but I ended up giving up on the custom flow and modifying the vendor app to deal with b2c out of the box.
