### ISSUE TITLE
Localization for otp verification error

### ISSUE THREAD

**Issue by maheshbthapa** [azure-ad-b2c/samples#358]
I am implementing [TOTP](https://github.com/azure-ad-b2c/samples/tree/master/policies/totp) with custom policy. I am having an issue with localization for `claimVerificationServerError`. Initially this text div tag is empty
`<div id="claimVerificationServerError" class="error pageLevel" style="display: none;" aria-hidden="true"></div>`

When I enter incorrect otp code I get error `Wrong code entered, please try again.`
`<div id="claimVerificationServerError" class="error pageLevel" style="display: block;" aria-hidden="false" role="alert" aria-live="polite" tabindex="1">Wrong code entered, please try again.</div>`

I wanted to localize this text but I cannot seem to find the correct one. I tried with both ErrorMessage as `claimVerificationServerError` and UxElement as `error_claimVerificationServerError`.

**Comment by kamilzzz** [comment]
Unfortunately, this is undocumented but you can localize this message using following `LocalizedString` definition:

```
<LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfIncorrectOTPCodeEntered">Custom message 'UserMessageIfIncorrectOTPCodeEntered'</LocalizedString>
```

You can find missing strings in the Application Insights traces if you have enabled Application Insights for your RelyingParty definition via JourneyInsights.

Part of the trace which let me find this localization StringId:
```
{
    "Key": "Exception",
    "Value": {
        "Kind": "Handled",
        "HResult": "80131500",
        "Message": "ErrorCodes: UserMessageIfIncorrectOTPCodeEntered",
        "Data": {
            "IsPolicySpecificError": false
        }
    }
}
```

**Comment by maheshbthapa** [comment]
Thank you for the solution help.

**Comment by SilverioMiranda** [comment]
The ErrorCode UserMessageIfIncorrectOTPCodeEntered was added to the documentation in this PR: https://github.com/MicrosoftDocs/azure-docs/pull/123185.


https://learn.microsoft.com/en-us/azure/active-directory-b2c/localization-string-ids#microsoft-entra-multifactor-authentication-error-messages


![image](https://github.com/azure-ad-b2c/samples/assets/1939153/61c02019-4735-48d8-94fa-95b560643cf5)
