### ISSUE TITLE
Policy doesnt allow cancel MFA during signin as per flow diagram

### ISSUE THREAD

**Issue by vikastiwari99** [azure-ad-b2c/samples#359]
I tried sample policy and after signin it's mandatory for user to select MFA, where as in the flow it has mentioned cancel button but it doesnt appear on MFA selection screen. I think its good to have cancel button if user wants to set up MFA later.

**Comment by JasSuri** [comment]
Which sample?

**Comment by vikastiwari99** [comment]
Here it is : https://github.com/azure-ad-b2c/samples/tree/master/policies/mfa-email-or-phone

**Comment by JasSuri** [comment]
You can add another enumeration in the radiobox for "set up later", and then write to an attribute this status so it can be managed later on, eg using profile edit policy.
