### ISSUE TITLE
Azure b2c custom policy, LinkedIn Identity Provider, unable to get email address

### ISSUE THREAD

**Issue by lemenhir** [azure-ad-b2c/samples#361]
I want to add LinkedIn as an identity provider to my azure b2c tenant.

I have already added Microsoft and Google as id providers.

However, when I added LinkedIn, it was impossible to retrieve an email address and put it in the azure b2c token.
Here is my custom policy base file: TrustFrameworkBase.xml

    `<ClaimsProvider>
      <Domain>linkedin.com</Domain>
      <DisplayName>LinkedIn</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="LinkedIn-OAuth2">
          <DisplayName>LinkedIn</DisplayName>
          <Protocol Name="OAuth2" />
          <Metadata>
            <Item Key="ProviderName">linkedin</Item>
            <Item Key="authorization_endpoint">https://www.linkedin.com/oauth/v2/authorization</Item>
            <Item Key="AccessTokenEndpoint">https://www.linkedin.com/oauth/v2/accessToken</Item>
            <Item Key="ClaimsEndpoint">https://api.linkedin.com/v2/me</Item>
            <Item Key="scope">r_emailaddress r_liteprofile</Item>
            <Item Key="HttpBinding">POST</Item>
            <Item Key="external_user_identity_claim_id">id</Item>
            <Item Key="BearerTokenTransmissionMethod">AuthorizationHeader</Item>
            <Item Key="ResolveJsonPathsInJsonTokens">true</Item>
            <Item Key="UsePolicyInRedirectUri">false</Item>
            <Item Key="client_id">MyLinkedInClientId</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="client_secret" StorageReferenceId="B2C_1A_LinkedInSecret" />
          </CryptographicKeys>
          <InputClaims />
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="issuerUserId" PartnerClaimType="id" />
            <OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="firstName.localized" />
            <OutputClaim ClaimTypeReferenceId="surname" PartnerClaimType="lastName.localized" />
            <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="emailAddress" />
            <OutputClaim ClaimTypeReferenceId="identityProvider" DefaultValue="linkedin.com" AlwaysUseDefaultValue="true" />
            <OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="socialIdpAuthentication" AlwaysUseDefaultValue="true" />
          </OutputClaims>
          <OutputClaimsTransformations>
            <OutputClaimsTransformation ReferenceId="ExtractGivenNameFromLinkedInResponse" />
            <OutputClaimsTransformation ReferenceId="ExtractSurNameFromLinkedInResponse" />
            <OutputClaimsTransformation ReferenceId="CreateRandomUPNUserName" />
            <OutputClaimsTransformation ReferenceId="CreateUserPrincipalName" />
            <OutputClaimsTransformation ReferenceId="CreateAlternativeSecurityId" />
            <OutputClaimsTransformation ReferenceId="CreateSubjectClaimFromAlternativeSecurityId" />
          </OutputClaimsTransformations>
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-SocialLogin" />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>`

As we can see, the ClaimsEndPoint is `https://api.linkedin.com/v2/me`
But, this end point does not give access to the email address.
Here is the documentation detailing it:
[Sign-in with LinkedIn](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin)

We see that to get the email address, we need to call another end point: `https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))`

I tried changing the ClaimsEndPoint to this but when uploading the custom policy, I got an error:

> The policy being uploaded is not correctly formatted: '=' is an unexpected token.

I don't see what I could do to get the email address as a claim in the azure b2c token.
Can you please help?

**Comment by lemenhir** [comment]
The error that I get when I set "https://api.linkedin.com/v2/emailAddress?q=members&amp;projection=(elements*(handle~))" as the claimsendpoint (I replaced & with &amp; in the xml):

`server_error: AADB2C90037: An error occurred while processing the request. Please contact administrator of the site you are trying to access. Correlation ID: 31821fd6-791a-4083-b785-5d91890abe13 Timestamp: 2022-02-24 16:28:38Z`

**Comment by JasSuri** [comment]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-linkedin?pivots=b2c-custom-policy#obtain-an-email-address
