### ISSUE TITLE
StringSplit fails for empty string with 'Unable to validate the information provided.' error

### ISSUE THREAD

**Issue by kamilzzz** [azure-ad-b2c/samples#363]
During SignIn flow we show user a list of checkboxes with terms of use he has to accept to sign in to specific application. The terms of use might be different per application (some of them may also overlap) so we didn't define them in XML but we are calling custom REST API via technical profile to get required consents. Then we're presenting user a self asserted page with checkboxes generated by javascript code. User checkbox selection is stored in a hidden input where we keep ids of selected checkboxes separated by comma. This value is then used as an OutputClaim for our self asserted page.

I would like to send ids of selected checkboxes to REST API for validation as array of string instead of one string with ids separated by comma. I tried to use `StringSplit` input claim transformation on our ValidationTechnicalProfile assigned to self asserted page but I'm getting 'Unable to validate the information provided.' when claim value is empty. When claim value is not empty everything works fine.

Some parts of our custom policy XML definition:

Claims definitions:
```
<ClaimType Id="grantedConsents">
    <DisplayName>Granted consents</DisplayName>
    <DataType>string</DataType>
    <UserInputType>TextBox</UserInputType>
</ClaimType>

<ClaimType Id="grantedConsentsCollection">
    <DisplayName>Granted consents collection</DisplayName>
    <DataType>stringCollection</DataType>
</ClaimType>
```

Claims transformation:
```
<ClaimsTransformation Id="ConvertGrantedConsentsToStringCollection" TransformationMethod="StringSplit">
    <InputClaims>
        <InputClaim ClaimTypeReferenceId="grantedConsents" TransformationClaimType="inputClaim" />
    </InputClaims>
    <InputParameters>
        <InputParameter DataType="string" Id="delimiter" Value="," />
    </InputParameters>
    <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="grantedConsentsCollection" TransformationClaimType="outputClaim" />
    </OutputClaims>
</ClaimsTransformation>
```

Self asserted technical profile - here the input claim `consents` is a JSON with reequired consents/terms-of-use the user has to accept. We use this value to generate checkboxes using JS. This input is hidden using JS.
As I describe earlier, `grantedConsents` here is a hidden input where we store user selection in form of `consent-a,consent-b`. In case no consent was selected this value is empty.
```
<TechnicalProfile Id="SelfAsserted-GrantConsents">
    <DisplayName>Get required consents</DisplayName>
    <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
    <Metadata>
        <Item Key="ContentDefinitionReferenceId">api.selfasserted.grantconsents</Item>
    </Metadata>
    <InputClaims>
        <InputClaim ClaimTypeReferenceId="consents" />
    </InputClaims>
    <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="consents" />
        <OutputClaim ClaimTypeReferenceId="grantedConsents" />
    </OutputClaims>
    <ValidationTechnicalProfiles>
        <ValidationTechnicalProfile ReferenceId="REST-VerifyGrantedConsents" />
    </ValidationTechnicalProfiles>
</TechnicalProfile>
```

Validation technical profile for self asserted page:
```
<TechnicalProfile Id="REST-VerifyGrantedConsents">
    <DisplayName>Verify granted consents</DisplayName>
    <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
    <Metadata>
        <Item Key="ServiceUrl">https://{hostname}/api/consents/verify</Item>
        <Item Key="AuthenticationType">None</Item>
        <Item Key="AllowInsecureAuthInProduction">true</Item>
        <Item Key="SendClaimsIn">Body</Item>
    </Metadata>
    <InputClaimsTransformations>
        <InputClaimsTransformation ReferenceId="ConvertGrantedConsentsToStringCollection" />
    </InputClaimsTransformations>
    <InputClaims>
        <InputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="userId" />
        <InputClaim ClaimTypeReferenceId="applicationId" DefaultValue="{OIDC:ClientId}" />
        <InputClaim ClaimTypeReferenceId="grantedConsentsCollection" PartnerClaimType="grantedConsents" />
    </InputClaims>
    <OutputClaims />
    <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
</TechnicalProfile>
```

On the self asserted page I'm getting 'Unable to validate the information provided.' error when I try to continue without selecting any checkbox - looks like `StringSplit` transformation fails on empty input. I would like to get an empty array in such case.

Any ideas?

**Comment by JasSuri** [comment]
Claimstransforms tend to fail when you operate on null values. Your only solution is to provide some non-null default value.

**Comment by kamilzzz** [comment]
Only reasonable default here would be an empty string. But wouldn't then I get an array with one element which is empty string?
I see no option to specify that I would like to remove empty entries during claim transformation.

**Comment by JasSuri** [comment]
Foe example, when no checkbox is selected, have your javascript enter "null" into the hidden text box. This way, you know that when no selection is made, the array contains "null". The claimtransform no longer operates on a null value.

**Comment by JasSuri** [comment]
Continue on stackoverflow for design advice.

**Comment by dkezri** [comment]
I have same issue  with  a user attribute of type string and having  ClaimsTransformation  splitString .   When defualtValue=""  then the result is  [""] .    In case of  defaultvalue is not set, then it ends in exception when running the b2c userflow.
