### ISSUE TITLE
Is there any method to get MAC address of the user's system using custom policies?

### ISSUE THREAD

**Issue by 1993Saurabh** [azure-ad-b2c/samples#37]
Hi,

I want to uniquely identify the user's machine other than IP addresses and want to store it into the claims as well. Is there any method to get MAC address of the user's machine using the custom policies flow or is there any other way to uniquely identify the user's machine. The reason behind why I don't want to go with the IP address is that this approach cannot uniquely identify the user's machine if all the machines are on the same network let's say on an organisational network. In that case it will give me the public IP address which I don't want because public IP address will be same for all the machines inside that network.

**Comment by JasSuri** [comment]
You can use any publicly available JavaScript to scrape device details, like user agent, that the browser will share. That can be inserted into a hidden field that B2C renders and submitted as part of the page. B2C itself does not return any information that uniquely identifies a device, usually that level of identification requires device enrollment.
