### ISSUE TITLE
Apple Signup/Sign in B2C not returning Name and email.

### ISSUE THREAD

**Issue by devtpsingh** [azure-ad-b2c/samples#370]
We are using B2C userflow for Sign In with APPLE, After successfully authentication APPLE dose not return Name and Email, please suggest. 

Thanks

**Comment by JasSuri** [comment]
Follow this:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-apple-id?pivots=b2c-custom-policy#configure-apple-as-an-identity-provider-1

Apple only return name and email the first time the user logs into the app. For follow up's, post on stackoverflow, as this is not an issue with any sample in this repo.
