### ISSUE TITLE
Cannot re-login after session expired with Email MFA

### ISSUE THREAD

**Issue by MinhTraHong** [azure-ad-b2c/samples#371]
I'm using Azure B2C login on email with MFA, so user need to input email, password and verify OTP code via email. I found my users cannot re-login when their session is expired. I followed this sample: https://github.com/azure-ad-b2c/samples/tree/master/policies/signin-email-verification

This sample is using ReadOnly Email in verification display control. On my understanding, I think user don't need to input email & password when their session expired, they only verify email again with OTP code, but i confused email field is ReadOnly, my users cannot input their email because it's read-only and the email & password field is disappear to user input.

```
<ClaimsSchema>
    <ClaimType Id="readOnlyEmail">
        <DisplayName>Email Address</DisplayName>
        <DataType>string</DataType>
        <UserHelpText />
        <UserInputType>Readonly</UserInputType>
    </ClaimType>
</ClaimsSchema>

```
So, I need to clear the login session when user enter login page, i deleted all cookies and the login show me username & password, verification code. but I cannot delete these cookies by Javascript.

**Comment by JasSuri** [comment]
Since first page is skipped (where user enters email), it’s going to next screen. This means session is valid, but second screen is not part of the session. 

The issue isn’t because session is expired, it will happen when Refresh token is expired but SSO session (cookie) is valid.

To fix this, persist readOnlyEmail into SM-AAD. Reference SM-AAD as session management technical profile in EmailVerifyOnSignIn technical profile.

**Comment by MinhTraHong** [comment]
I persisted it in my SM-AAD.

`
<TechnicalProfile Id="SelfAsserted-LocalAccountSignin-Email">
  <DisplayName>Local Account Signin</DisplayName>
  <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
   ....
   <UseTechnicalProfileForSessionManagement ReferenceId="SM-AAD" />
</TechnicalProfile>
`

`
<TechnicalProfile Id="SM-AAD">
  <DisplayName>Session Mananagement Provider</DisplayName>
  <Protocol Name="Proprietary" Handler="Web.TPEngine.SSO.DefaultSSOSessionProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
  <PersistedClaims>
    <PersistedClaim ClaimTypeReferenceId="objectId" />
    <PersistedClaim ClaimTypeReferenceId="signInName" />
    <PersistedClaim ClaimTypeReferenceId="authenticationSource" />
    <PersistedClaim ClaimTypeReferenceId="identityProvider" />
    <PersistedClaim ClaimTypeReferenceId="newUser" />
    <PersistedClaim ClaimTypeReferenceId="executed-SelfAsserted-Input" />
  </PersistedClaims>
  <OutputClaims>
    <OutputClaim ClaimTypeReferenceId="objectIdFromSession" DefaultValue="true" />
  </OutputClaims>
</TechnicalProfile>
`

@JasSuri . Could you take a look my technical profile

**Comment by JasSuri** [comment]
I made the fix here:
https://github.com/azure-ad-b2c/samples/commit/b306f4f1250fcb9bac2861bd67fda6e5590e8b61

**Comment by MinhTraHong** [comment]
@JasSuri , thank you, it works like charm.
i don't need to input email, password or Email OTP verification.
