### ISSUE TITLE
MFA Page for SMS Code: button is not set as default submit

### ISSUE THREAD

**Issue by deyanp** [azure-ad-b2c/samples#372]
The MFA page for SMS code does not allow me to enter the code and directly press Enter on the keyboard:

![image](https://user-images.githubusercontent.com/25847560/157692806-ddb8a3ff-9f46-463c-a1f7-9206f24b9b1b.png)

The same is working fine for the TOTP (code from Microsoft/Google Authetnicator) page:

![image](https://user-images.githubusercontent.com/25847560/157693073-0b239835-8692-46b5-be93-300674adc5fd.png)

Page Layout Versions used:

For SMS: 1.2.5 (urn:com:microsoft:aad:b2c:elements:contract:multifactor:1.2.5)

For TOTP: 2.1.7 (urn:com:microsoft:aad:b2c:elements:contract:selfasserted:2.1.7)

Thanks in advance!

**Comment by deyanp** [comment]
Note, in case of the SMS form there seems to be no form, so probably that is why it does not work. In case of TOTP there is a form, and the button has type=submit and form=attributeVerification, etc....

How can we make the button **default** (pressing Enter on keyboard triggers it) on the SMS page?

**Comment by JasSuri** [comment]
I suspect this is a bug in the page contract, and nothing specific with the samples in the repo. If so, best to raise a support ticket.

**Comment by deyanp** [comment]
Thanks, support request 2203140050000338 created, let's see ...
