### ISSUE TITLE
Email is not included in token claims

### ISSUE THREAD

**Issue by dmosyan** [azure-ad-b2c/samples#373]
We are using B2C login quite long, however, we are no longer getting email address/addresses in token, even if it's configured from Application Claims.

![image](https://user-images.githubusercontent.com/33767811/158142164-9e6a6672-0f71-486d-8273-982d4756fa6c.png)

Identity provider is "Local Accounts" with "Email" configuration. After adding the "Authentication method" -> "Email" for the user, we are getting email address in the token.

![image](https://user-images.githubusercontent.com/33767811/158142653-aa566f41-3181-4bfe-9c9e-18808c775fc7.png)

Is that the correct way to do that? The problem with this approach is that Administrator within that B2C service adds new users, and that configuration is not available from the B2C instance directly.

**Comment by JasSuri** [comment]
This is not a bug in any of the policy samples in this repo. Please raise a support ticket, or stackoverflow thread.
