### ISSUE TITLE
Is there a way to "redirect" users to SignUp directly in existing SignInOrSignIn standard userjourney?

### ISSUE THREAD

**Issue by carecircleORG** [azure-ad-b2c/samples#375]
I would like to create a URL that would redirect to SignUp directly rather than users having to go to SignIn form and then clicking Sign Up Now link. Is this possible in the context of the standard SignInOrSignUp userjourney?

**Comment by eskaufel** [comment]
Would this not just be a link to the signup flow?

**Comment by carecircleORG** [comment]
> Would this not just be a link to the signup flow?

if I do that, I get a "bad request" error...

**Comment by JasSuri** [comment]
You should post this on stackoverflow for design advice.

1. Send a custom query parameter in the authors request
2. Use a claimtransform technical profile in step 1 of the journey to resolve the query param 
3. Add precondition to skip the sign in step (would be step 2 now), and therefore user ends up at step 3: sign up.
