### ISSUE TITLE
Custom policy for disabling MFA per user

### ISSUE THREAD

**Issue by kamilzzz** [azure-ad-b2c/samples#379]
Based on https://github.com/azure-ad-b2c/samples/tree/master/policies/totp I have implemented a custom policy to allow users to enable MFA on their accounts (it's their choice so they are not forced to setup MFA on signup/first signin).
The way it works in my case is that user is redirected to dedicated policy which enables MFA on his account.

I would like to implement a policy to also allow a user to disable MFA for his account. From what I can see, TOTP sample makes decision whether MFA is required or not based on `numberOfAvailbleDevices` claim. 
Would it be enough to delete this claim or set it to `0` to consider such user as not having MFA enabled? Is manipulating this claim value even possible? It's read using `AzureMfaProtocolProvider` TechnicalProfile but I cannot find any operation allowing me to unenroll user.
Aren't there any other claims which should be removed? For example shared secret generated during enrolling user?

Btw. Is it possible to read `numberOfAvailableDevices` attribute using either Azure Portal user list (couldn't find it anywhere) ot MS Graph API?

**Comment by JasSuri** [comment]
This logic is ok to use.
