### ISSUE TITLE
change-sign-in-name questions

### ISSUE THREAD

**Issue by woodman231** [azure-ad-b2c/samples#380]
Hello,

This example works great.

My team commonly uses the gmail infinite mailbox trick during development. I had user testuser+changeme@gmail.com as a registered user in my tenant, while going through the change-sign-in-name policy I was told that testuser+changed@gmail.com was an invalid address and it wouldn't even email me to update to a different infinite mailbox. I was able to change it if I just updated it to testuser@gmail.com.

First Question:
Since it is allowing the infinite mailbox address to be added during registration, how can I make it a valid value while going through this sample?

Second Question:
If the user completes this flow then I need to take some additional action in my application database. How can I get an API connector to send a payload after this sample is complete?

Thanks,
Sean W.

**Comment by JasSuri** [comment]
Update the `restriction` of your newEmail claim in the claim schema section with an appropriate regex to support these formats. Likely it’s different for your email claim vs newEmail claim.

**Comment by JasSuri** [comment]
Add a step in your user journey to call a rest api. 

https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-api-connector?pivots=b2c-custom-policy
