### ISSUE TITLE
"The username or password provided in the request are invalid" on Password Change policy

### ISSUE THREAD

**Issue by cansozbir** [azure-ad-b2c/samples#381]
Hi, 
I'm trying to implement a password change custom policy for Azure AD B2C.

I've used [this](https://github.com/azure-ad-b2c/samples/blob/master/policies/change-password/policy/PasswordChange.xml)[](https://i.stack.imgur.com/AEyZi.png) file as a base, changed the tenantid, and uploaded it to Azure.

When I try a demo from the Azure portal, it asks me to log in, then asks for an old password and a new password to change it. And it works perfectly fine. I can change my password there.

Then I've implemented a button, that redirects to the password change URL.

```
private redirectPasswordChange(appConfigService: AppConfigService): void {
  const passwordChangeUrl = `${appConfigService.config.AD_AUTHORITY_CHANGE}?client_id=${appConfigService.config.AD_CLIENT_ID}
    &nonce=defaultNonce
    &redirect_uri=${appConfigService.config.BASE_URL}
    &scope=openid
    &response_type=id_token`;
  if (isPlatformBrowser(PLATFORM_ID)) {
    window.location.href = passwordChangeUrl;
  } else {
    this.window.location.href = passwordChangeUrl;
  }
}
```
I've removed prompt=login from the URL because the button that is going to redirect to the password change URL is on the "My profile" section on our website. So users are already logged in, and I don't want them to log in again.

Then I tested it on our website, when I click to button, it redirects me to the password change page, it asks for my old password, new password, and confirmation of it, which is perfect for me. But the problem is, it doesn't accept my old password, it says "The username or password provided in the request are invalid".
![image](https://user-images.githubusercontent.com/32648255/159812431-d33cee3d-a85d-4e76-83e1-3f56ef9ed8f4.png)

And also, when I try a test from the Azure portal for the password change, the sign-in page looks different(I mean the theming) than the one we're using to sign in to our website.

We do have a sign-in user flow, and the rest are custom policies, so we do combine user flows and custom policies. Can this be the issue? I believe the ProxyIdentityExperienceFramework has been configured correctly on TrusFrameworkExtensions.xml. Should we do something about it for the password change policy?

Also, when I put prompt=login to the URL back, it does ask for my login credentials first, but it doesn't let me log in.
![image](https://user-images.githubusercontent.com/32648255/159822527-b6cafac4-ca6d-4448-9802-12e801541405.png)

Here are the custom policies we have, and there is B2C_1_signin **user flow** is enabled in addition to them.

TrustFrameworkBase.xml: https://pastebin.com/RXXhcwpN
TrustFrameworkExtensions.xml: https://pastebin.com/UUfVNaJ7
PasswordChange.xml : https://pastebin.com/sPjZjNYT
PasswordReset.xml : https://pastebin.com/CxE3pMH3

I would appreciate it if someone can give some clue about the problem we have. Thanks for reading.

**Comment by JasSuri** [comment]
Closing as already discussed on SO.

**Comment by bschreder** [comment]
Little late, but  the SO link would be helpful.
