### ISSUE TITLE
Missing sample - Custom Policies with separate Sign-up and Sign-in flow

### ISSUE THREAD

**Issue by bgawale** [azure-ad-b2c/samples#382]
It would be great if sample for custom policies with separate sign-up and sign-in flow is also added to the repository.  Apparently it is the use case most people are looking for and there is no clear guidance / documentation to get it achieved. 

It is very easy to configure it in user flows, however when it comes to custom policies it is not that straight forward and hence a starter sample of separate sign-up and sign-in would definitely help a lot of folks.

**Comment by JasSuri** [comment]
It’s pretty simple.
1. Set sign up to disabled by setting [metadata item](https://docs.microsoft.com/en-us/azure/active-directory-b2c/self-asserted-technical-profile#metadata) setting.showSignUpLink to false in `SelfAsserted-LocalAccountSignin-Email` technical profile. 

2. Rename the `signUpSignIn` journey id to `SignIn`.

3. Copy `SignIn` journey, give it a new Id: `SignUp`. Remove step 1. In the resulting first step, remove the precondition around objectId.

4. Make a copy of SignUpSignIn.xml. Rename to SignIn.xml and SignUp.xml. In the relying party section, update the DefaultUserJourney ids to match your new user journey ids, `SignIn` and `SignUp` in each file. 

5. Update the policyId to be unique in SignIn.xml and SignUp.xml.

I’ll look at adding a complete sample.

**Comment by bgawale** [comment]
Thanks for the response, will give it a try.
