### ISSUE TITLE
username-or-email sample - Invalid username or password error

### ISSUE THREAD

**Issue by epuio** [azure-ad-b2c/samples#384]
I'm using the username-or-email sample and getting an "Invalid username or password" error after signing up for an account and then attempting to login with that account. I've attempted it several times to ensure I'm entering the credentials correctly.

Here are the steps I performed to use the username-or-email sample:

1. Make a copy of the files in the username-or-email sample
2. Add the trust base and extension files from the starter kit (since they aren't included in the username-or-email sample)
3. Update all tenant ids in all files and add the proxy and identity ids to the trust extensions file
4. Added ApplicationObjectID and ClientID to AAD-Common in trust extensions file
5. Add Verified.strongAuthenticationPhoneNumber claim type to trust extensions file (since I get an error if I don't)
6. Upload all files to my identity framework in the correct order

I then signup for an account (including verifying the email address) and attempt to sign in. That is when I get the Invalid username or password error. I've verified in the portal that the user account is being created.

I'm not very familiar with how to troubleshoot issues like this in B2C and hoping someone can point me in the right direction.

Thanks.

**Comment by JasSuri** [comment]
Incorrect setup of starter pack. Delete your ief and proxyief app registration and use my tool to redeploy the starter pack https://aka.ms/iefsetup.

**Comment by epuio** [comment]
That worked! Thank you very much!!!
