### ISSUE TITLE
Fetch claims from userinfo endpoint and add to the token when access token being generated

### ISSUE THREAD

**Issue by codeiskool** [azure-ad-b2c/samples#386]
My OIDC provider does not return any claims in the id_token, it has a separate endpoint for claims called userInfo_endpoint where you send a GET request with Bearer authentication and the access_token go get user claims in json format.

While generating a token using B2C, can B2C fetch the claims from userinfo endpoint of the IDP and add them to the token being generated?

Wondering if it is currently possible? Should be I still writing an API to fetch these details via API?

I see someone already asked this question and it is a old one. I'm wondering if the answer provided here in this URL still valid?

https://stackoverflow.com/questions/46970059/how-to-get-claims-from-openid-connect-provider-in-azure-ad-b2c/67413698#67413698

**Comment by senthilkumardhanapal2** [comment]
Yes it is possible. you may need to add step in user journey to call rest api ( define technicalprofile) and get all the claims from userinfo response.

**Comment by codeiskool** [comment]
Can the userinfo endpoint be invoked with bearer token?
Wondering is there any sample for this? In my case b2c invokes idp userinfo. How to pass idp the access token it understands?

**Comment by JasSuri** [comment]
Use the Oauth2 provider
https://docs.microsoft.com/en-us/azure/active-directory-b2c/oauth2-technical-profile

Continue on stackoverflow if you have more questions.
