### ISSUE TITLE
Page layout versions

### ISSUE THREAD

**Issue by kamilzzz** [azure-ad-b2c/samples#387]
I think documentation needs update - https://docs.microsoft.com/en-us/azure/active-directory-b2c/page-layout.

For example, it specifies 2.1.8 as latest page version for self-asserted page and 2.1.5 for unifiedssp.
However, when uploading IEF policy via Azure Portal, when I've specified wrong version I got an error message saying that I can use newer version, 2.1.9, 2.1.10. 2.1.11 and 2.1.12 for selfasserted and up to 2.1.8 for unifiedssp.

Are these new page version in preview or is it safe to use them?

I've tried 2.1.10 for selfasserted and it's working fine for me. 
If I remember correctly I had been receiving 400 Bad Requests errors with 2.1.12 when I tried to register local account (selfasserted page).

**Comment by kamilzzz** [comment]
What I've also noticed is that unifiedssp 2.1.5 is not rendering "heading" element anywhere, while docs show we can override text of this UxElement (StringId = heading) - https://docs.microsoft.com/en-us/azure/active-directory-b2c/localization-string-ids#sign-up-or-sign-in-page-elements

Unifiedssp 2.1.6 (not documented) correctly renders `h1` element at the top of the `api` div with value of `StringId="heading"` from LocalizedStrings.

**Comment by JasSuri** [comment]
At the doc link there is a feedback button that can be used to raise a doc issue.
