### ISSUE TITLE
obtain client_id/azp during refresh_token call to aadb2c identityexperienceframework

### ISSUE THREAD

**Issue by senthilkumardhanapal2** [azure-ad-b2c/samples#388]
I have a requirement to make rest API call during refresh_token in aadb2c userjourney. i am looking for help to obtain client_id or azp to give as input to rest API call. is it poissble to obtain clientId(OIDC:ClientId) during /token endpoint ?

**Comment by JasSuri** [comment]
This is not a bug with any specific policy in this repo. Better to raise this on stackoverflow.
