### ISSUE TITLE
Sign in with Apple out of Beta?

### ISSUE THREAD

**Issue by atobrandon** [azure-ad-b2c/samples#39]
We've been waiting to implement Sign in with Apple through AADB2C until after it is out of beta.  The sample related to this still has a disclaimer saying that it is in beta.  However, I've been checking up on it periodically and I finally found this post that says it's now GA: [Post GA Revisit of Sign in with Apple](https://contos.io/post-ga-revisit-of-sign-in-with-apple-for-azure-ad-b2c-e045d3055b1).    Is it now safe to use the sample code in production?  If so, you might want to review the sample to ensure it's up-to-date and remove the beta disclaimer.

**Comment by JasSuri** [comment]
Technically we do not preview/GA specific providers for Custom Policies. We only GA the feature being used, which is an OIDC Technical Profile. OIDC technical profiles are GA. 
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-developer-notes

The disclaimer on our samples is not the equivalent of Azure Documentation preview disclaimers. In this case, if Apple change something, you cannot rely on the sample here to have accommodated for that.

Only for User Flows do we GA specific providers.

**Comment by atobrandon** [comment]
OK, thanks for the information.  Do you know if there are any plans to add Apple as an External IDP User Flow as you've done with Amazon, Facebook, Google, LinkedIn, Twitter, etc?  If so, what's the timeline for it to be added?  Is there any resource that shows it on a roadmap that I can follow?
