### ISSUE TITLE
Bug while implimentin force-password-reset-first-logon

### ISSUE THREAD

**Issue by dips365** [azure-ad-b2c/samples#391]
I am trying to impliment reset password on first login.
I tried it with custom attribute called "extension_mustResetPassword".

I am trying to upload xml file to create custom attribute which is defined in staep 1.
I am getting below error.

Validation failed: 1 validation error(s) found in policy "B2C_1A_FORCEPASSWORDRESET_SIGNUP_SIGNIN" of tenant "test.onmicrosoft.com".A required Metadata item with key "ApplicationObjectId" was not found in the TechnicalProfile with id "AAD-UserRemoveMustResetPasswordUsingObjectId" in policy "B2C_1A_ForcePasswordReset_signup_signin" of tenant "test.onmicrosoft.com".A required Metadata item with key "ApplicationObjectId" was not found in the TechnicalProfile with id "AAD-UserRemoveMustResetPasswordUsingObjectId" in policy "B2C_1A_ForcePasswordReset_signup_signin" of tenant "b2cjudodev.onmicrosoft.com".

Can anyone help me out ?

**Comment by Tvde1** [comment]
Is this an issue with any of the example policies?

**Comment by JasSuri** [comment]
You must follow the pre requisites: 
https://github.com/azure-ad-b2c/samples#prerequisites

Specifically you haven’t setup support for extension attributes:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes?pivots=b2c-custom-policy#modify-your-custom-policy
