### ISSUE TITLE
Authenticator code timeout for AzureMFA in custom policy

### ISSUE THREAD

**Issue by maheshbthapa** [azure-ad-b2c/samples#392]
Hi!

I am using AzureMFA with TOTP (https://github.com/azure-ad-b2c/samples/tree/master/policies/totp) which is working fine. I am using google authenticator app which is set to referesh every 30s. But the code once generated is usable for 5 mins in the MFA flow in custom policy. How can I update custom policy so that the code is only acceptable within 60s of its generation?
Any Solution for this?

**Comment by JasSuri** [comment]
I do not see a way to do this with what's released, please raise a support ticket as this seems like a product issue.
