### ISSUE TITLE
Social account signup - self asserted (data collection) step fails with exception after refreshing page

### ISSUE THREAD

**Issue by kamilzzz** [azure-ad-b2c/samples#398]
I've noticed this in my custom policies and confirmed by using following sample available in this GitHub repo - https://github.com/azure-ad-b2c/samples/tree/master/policies/force-unique-email-across-social-identities

After user logs in with Facebook account and we do not get back e-mail address from Facebook, we show a page where user has to provide his e-mail address. When he refreshes page, he is redirected to RP application with exception message.

Repro:

1. Upload custom policies from this sample - https://github.com/azure-ad-b2c/samples/tree/master/policies/force-unique-email-across-social-identities
**Warning**: There is an issue in SignUpSignIn.xml definition as it references `B2C_1A_ForceUniqueEmail_TrustFrameworkExtensions` as base policy while Extensions.xml has Id of `B2C_1A_TrustFrameworkExtensions`.
2. Sign in using Facebook with account which doesn't have an e-mail address configured in Facebook (for example, I've created my Facebook account using phone number and not e-mail address).
3. Selfasserted page collecting e-mail address should be rendered:
![image](https://user-images.githubusercontent.com/32141632/163025846-3a9cf24a-7ed6-4938-9f06-d6dd2cc0bdf6.png)
4. Refresh page
5. Exception is returned to the RP application:
![image](https://user-images.githubusercontent.com/32141632/163025959-b7a2984f-50f8-4edd-bc82-da306d84eed6.png)

**Comment by JasSuri** [comment]
There is nothing in the custom policy sample which controls this behaviour. This is how the service behaves in this case. You can raise a Microsoft support ticket if you have an issue with this.
