### ISSUE TITLE
Auto account linking sample - "[...] due to not being able to add a Local Account to a Federated-only account"

### ISSUE THREAD

**Issue by kamilzzz** [azure-ad-b2c/samples#399]
Sample policy: https://github.com/azure-ad-b2c/samples/tree/master/policies/auto-account-linking#scenario-4

In Scenario 4 of auto account linking there is following statement:
> All social sign ups result in Local Account with random password. This is due to not being able to add a Local Account to a Federated-only account.

Why isn't it possible to add a Local Account to a Federated-only account similarly like we can add a Social Account to a Local-only account?

Is it something that isn't supported by Azure AD B2C? 
Wouldn't it work if I just try to set signInNames.emailAddress and password on existing Federated-only identity?

**Comment by JasSuri** [comment]
It simply is unsupprted. You will get an error trying to add a local identity to a social account.
