### ISSUE TITLE
IdentityExperienceFramework and ProxyIdentityExperienceFramework disambiguation

### ISSUE THREAD

**Issue by RaphaelSilv** [azure-ad-b2c/samples#400]
Hi, 
I noticed that the **Web** redirect URI set up by the [automated deploy](https://b2ciefsetupapp.azurewebsites.net/)  defaults to something like:`https://login.microsoftonline.com/your-tenant-name.onmicrosoft.com` while the ms docs on how to [manually set up this app](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy) orientates `https://your-tenant-name.b2clogin.com/your-tenant-name.onmicrosoft.com` -  where your-tenant-name is your Azure AD B2C tenant domain name.

Are they interchangeable?

Also, the ms docs about the configuration of ProxyIdentityExperienceFramework recommends
> 5. For Redirect URI, enter myapp://auth. 
I didn't get it.

While the automated deployment set the redirect URI as `https://login.microsoftonline.com/your-tenant-name.onmicrosoft.com`.

Could you please clarify?

**Comment by JasSuri** [comment]
login-noninteractive technical profile models an ROPC authentication to the AAD endpoint of your AAD B2C tenant. As per this article: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc

The ProxyIEF app needs to be a Native App, such that you do not need a client_secret to perform the ROPC grant.
The redirectURIs are not even used in the ROPC call.

The correct parameters are used to create a Native App Reg (proxyIEF app), and Web App app reg (IEF App reg), the rest is irrelevant placeholders.
