### ISSUE TITLE
Disclosure of Security Issues?

### ISSUE THREAD

**Issue by jnovak-praetorian** [azure-ad-b2c/samples#404]
Does this project have a policy or process for reporting security issues? I have two items I would like to disclose responsibly and am looking for a point of contact for this project. I _could_ open them up as individual Issues on this project, but that would make the details public before a fix is put in place.

GitHub recommends a `SECURITY.md` file at the root of the project:
https://docs.github.com/en/code-security/repository-security-advisories/about-coordinated-disclosure-of-security-vulnerabilities
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#about-security-policies

**Comment by JasSuri** [comment]
You can raise a MS support ticket. Pass my name: Jas Suri, and I’ll look into it.

**Comment by jnovak-praetorian** [comment]
@JasSuri - do you mean to the MSRC (https://www.microsoft.com/en-us/msrc?rtc=1)?

**Comment by JasSuri** [comment]
I mean, through the azure portal, troubleshooting menu and raise a ticket.
