### ISSUE TITLE
custom policy with default UI blocked by Content Security Policy

### ISSUE THREAD

**Issue by huqianghui** [azure-ad-b2c/samples#407]
I am using AAD B2C with custom policies on Azure China cloud, I uploaded the policies onto IEF, when I tried to run it. I met the CSP error as below.
<img width="1440" alt="Screen Shot 2022-05-16 at 10 50 21 AM" src="https://user-images.githubusercontent.com/7360524/168511838-467a350d-6cd5-48d0-9d62-83ec2662ac7e.png">

And I tested the URL of my B2C custom policy in the website https://csper.io/evaluations/6280e53d8c0edf740896e810. There are CSP issues shown in the result.
<img width="1428" alt="Screen Shot 2022-05-16 at 10 53 50 AM" src="https://user-images.githubusercontent.com/7360524/168512126-365090b9-ede3-4926-9ef7-1fba35bdbe40.png">

Is there anyway to fix it or I need to customize the UI to add the http header setting about CSP?

**Comment by JasSuri** [comment]
Does this happen with User Flows? Or even custom policy starter pack? If so, raise a MS support ticket, as it wouldn’t be an issue with any sample policy here, but rather a service issue.

**Comment by huqianghui** [comment]
Thanks JasSuri. I aggreed with you I should raise a MS support ticket.
Because I used custom policy starter pack and the policy of  the lik (https://github.com/azure-ad-b2c/samples/blob/master/policies/mfa-email-or-phone/policy/SignUpOrSignin_PhoneOrEmailMFA.xml) to build my custom policy. I just want to check whether anybody here else also meets the same problem or any suggestion about it.

**Comment by huqianghui** [comment]
Add the below config, then the js error disappears.
<RelyingParty>
    <DefaultUserJourney ReferenceId="SignUpOrSignInMFAOption" />
    <UserJourneyBehaviors>
      <ScriptExecution>Allow</ScriptExecution>
    </UserJourneyBehaviors>
<RelyingParty>
