### ISSUE TITLE
SignUp_SignIn_PhoneOrEmailMFA login failed (Invalid username or password.) but I can sign in successfully by built-in user flow

### ISSUE THREAD

**Issue by huqianghui** [azure-ad-b2c/samples#411]
I used custom policy starter pack and the policy of the link (https://github.com/azure-ad-b2c/samples/blob/master/policies/mfa-email-or-phone/policy/SignUpOrSignin_PhoneOrEmailMFA.xml) to build my custom policy. 

When I sign in with the custom policy always with the error "Invalid username or password." but I can sign successfully by the built-in user flow.

<img width="1440" alt="Screen Shot 2022-05-20 at 11 03 23 AM" src="https://user-images.githubusercontent.com/7360524/169442322-8a2d413e-493b-48bb-ab4b-a4edf76a4f50.png">

In the application insight , I also could see the self-asserted error.
 {
                  "Key": "Exception",
                  "Value": {
                    "Kind": "Handled",
                    "HResult": "80131500",
                    "Message": "Invalid username or password.",
                    "Data": {
                      "IsPolicySpecificError": false
                    }
                  }
                }

Is there anybody could provide me the entire config files including TrustFrameworkBase.xml and so on.
Or any advise about this issue?

the attachments are the config file and application insight log.

[attachment.zip](https://github.com/azure-ad-b2c/samples/files/8735624/attachment.zip)

**Comment by JasSuri** [comment]
Delete your ProxyIEF and IEF App registrations.

Then use the [IEF Setup tool](https://aka.ms/iefsetup) to deploy the starter pack properly.

**Comment by huqianghui** [comment]
@JasSuri ,thanks for your response.
Because my tenant is in azure china cloud. 
So Is there any way to deploy to domain of partner.onmschina.cn?

**Comment by JasSuri** [comment]
My tool will not work for Chinese cloud. You need to manually follow the docs: https://aka.ms/ief

Your issue is related to ProxyIEF, IEF App reg creation, and/or incorrect Ids used in login-noninteractive technical profile in TrustframeworkExtension file.

**Comment by huqianghui** [comment]
hi @JasSuri ,thanks your suggestion. But I followed the docs and tested the simplest case LocalAccounts, the same error still apears.

**Comment by JasSuri** [comment]
This is issue is **always** due to misconfiguration of ProxyIEF, IEF App reg creation, and/or incorrect Ids used in login-noninteractive technical profile in TrustframeworkExtension file. You can raise a MS Support ticket if you need more help.

**Comment by huqianghui** [comment]
Thanks, @JasSuri , you are correct, It is misconfiguration. When I changed to the below configuration, it worked
'''xml
            <Item Key="ProviderName">https://sts.chinacloudapi.cn/</Item>
            <Item Key="METADATA">https://login.chinacloudapi.cn/YourTenantName.partner.onmschina.cn/.well-known/openid-configuration</Item>
            <Item Key="authorization_endpoint">https://login.chinacloudapi.cn/YourTenantName.partner.onmschina.cn/oauth2/token</Item>
'''
