### ISSUE TITLE
Cannot upload custom policy file.                                    

### ISSUE THREAD

**Issue by Andriy-Liulka** [azure-ad-b2c/samples#414]

**Comment by JasSuri** [comment]
Try the quick deploy link
https://b2ciefsetupapp.azurewebsites.net/Home/Experimental?sampleFolderName=password-reset-not-last-password

**Comment by JasSuri** [comment]
You can’t inherit from a user flow (base policy). You need to deploy custom policy starter pack, read the pre requisites in the main repo readme.

**Comment by JasSuri** [comment]
Not a bug. You can post on stackoverflow for config help.
