### ISSUE TITLE
AADB2C: An exception has occurred. at sign in after adding <SingleSignOn Scope="Suppressed" /> to RP

### ISSUE THREAD

**Issue by voloszad** [azure-ad-b2c/samples#419]
Hi, I'm stuck with the following exception and cannot figure out what could be the issue.

I've begun to build up our policies from scratch, started with the [Azure Samples, starterpack for local account](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/main/LocalAccounts), then added the [username-signup-or-signin](https://github.com/azure-ad-b2c/samples/tree/master/policies/username-signup-or-signin) policies (in both cases everything but, the profile and password reset RP policies).

So far I disabled the sign up and forgot password links and changed the localization a bit and added ClaimsSchemas for our custom attributes (in the starterpack TrustFrameworkExtensions file). Inheritance seems working fine, using the username policy to sing in works as expected.

Next I wanted to disable SSO, I need the users to re-authenticate if browser/tab is closed. Based on [Configure session behavior in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy), I've added the suggested tags to the username RP file:

```
    <UserJourneyBehaviors>
      <SingleSignOn Scope="Suppressed" />
      <SessionExpiryType>Absolute</SessionExpiryType>
      <SessionExpiryInSeconds>86400</SessionExpiryInSeconds>
      <JourneyInsights TelemetryEngine="ApplicationInsights" InstrumentationKey="{Settings:ApplicationInsightsInstrumentationKey}" DeveloperMode="{Settings:ApplicationInsightsDeveloperMode}" ClientEnabled="{Settings:ApplicationInsigthClientEnabled}" ServerEnabled="true" TelemetryVersion="1.0.0" />
    </UserJourneyBehaviors>
```

After this, I cannot sign in any more. I get the 'Sorry, but we're having trouble signing you in.' error screen. In the app insights with transaction search I see the exception in the last trace:

```
 {
    "Kind": "FatalException",
    "Content": {
      "Time": "1:44 PM",
      "Exception": {
        "Kind": "Handled",
        "HResult": "80004003",
        "Message": "Value cannot be null.\r\nParameter name: source",
        "Data": {}
      }
    }
  }
```

I don't see any parameter with null value, nor have any idea that is the parameter source. For that given correlation id, there is two System.Exceptions, but without helpful information and one Dependency transaction which I don't think is right.
Apparently there is a POST command which results in 404, but I think this is the result of previous failure.

```
POST /mytenat.onmicrosoft.com/B2C_1A_SignUpOrSignIn_Username/client/perftrace?tx=a0b35e8b...c35aa99c3f91&p=null
```

If I change the SingleSignOn Scope to Tenant, then everything works as before.

The application is a React app, with MSAL, the authentication details are stored in the sessionStorage, but I tested this with the jwt.ms endpoint too with the same results.

**Comment by JasSuri** [comment]
Share the correlationId.

**Comment by voloszad** [comment]
Hi @JasSuri, 

For example: 

98829001-39a8-4a7e-9cb1-2be83c9b8850

Thanks!

**Comment by voloszad** [comment]
@JasSuri Thanks, it did the trick!
