### ISSUE TITLE
Custom email verification - DisplayControls policy failure

### ISSUE THREAD

**Issue by dwhiteddsoft** [azure-ad-b2c/samples#42]
Nothing fancy. Simply changed needed fields and applied templates to blank B2C directory with no users. Account creation comes back with the error message:
"A user with the specified ID already exists. Please choose a different one."
When I go check the directory I see that even though the error was thrown, it was indeed created there. I try to then log in with the user name and password I put in registration screens and receive:
"Invalid username or password."
I am not sure what is happening as I have done zero customizations. I thought the example on Github would work out of the box :-(

**Comment by JasSuri** [comment]
This sounds like a misconfiguration of the starter pack, have you tested that the starter pack can do a sign up and sign in successfully first?
After that, the files should chain to your existing TrustframeworkExtensions without needing much modification at all.

**Comment by goekhany** [comment]
I have the same error like @dwhiteddsoft. I have tested the starter pack and everything worked fine. but when i do the steps in https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-email#add-the-claims-transformation then i get the same error in signin :"A user with the specified ID already exists. Please choose a different one."

**Comment by JasSuri** [comment]
Ok, sounds like maybe the user is being created twice. 
In this [step](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-email#make-a-reference-to-the-displaycontrol), did you make sure to replace the existing technical profile? Likely you have it in another file (Base), and therefore its creating the user twice.
If you dont want to modify the base file, then add this technical profile with a new Id, and replace the reference in the UserJourney orchestration step.

**Comment by JasSuri** [comment]
Closing since i updated sample for 'plug and play'-ness.
