### ISSUE TITLE
How to remove Facebook from delete-my-account

### ISSUE THREAD

**Issue by unboeing** [azure-ad-b2c/samples#424]
Hi, 

I'm trying to implement the delete-my-account custom policy from the repo, but without the Facebook sign in button.  The Readme.md at https://github.com/azure-ad-b2c/samples/tree/master/policies/delete-my-account states that this sample policy is based on SocialAndLocalAccounts starter pack and I was able to remove the Facebook references from those files and successfully upload them to our tenant's IEF. However, when I am trying to upload the code from delete-my-account I encounter the following error:

Validation failed: 2 validation error(s) found in policy "B2C_1A_DELETE_MY_ACCOUNT" of tenant "***.onmicrosoft.com".ClaimsExchange with id "FacebookExchange" is referenced in UserJourney with id "DeleteAccount" in policy "B2C_1A_Delete_My_Account" of tenant "***.onmicrosoft.com", but it was not found.ClaimsExchange with id "FacebookExchange" is referenced in UserJourney with id "DeleteAccount" in policy "B2C_1A_Delete_My_Account" of tenant "***.onmicrosoft.com", but it was not found.

Removing the orchestration steps that reference Facebook from the policy results in even more validation errors, such as 

Validation failed: 3 validation error(s) found in policy "B2C_1A_DELETE_MY_ACCOUNT" of tenant "***.onmicrosoft.com".Claim type "alternativeSecurityId" is the input claim of technical profile "AAD-UserReadUsingAlternativeSecurityId-NoError" in step "1" of user journey "DeleteAccount" but it is not an output claim in any of the previous steps.Claim type "email" is the output claim of the relying party's technical profile, but it is not an output claim in any of the steps of user journey "DeleteAccount".Claim type "identityProvider" is the output claim of the relying party's technical profile, but it is not an output claim in any of the steps of user journey "DeleteAccount".

I am new to this and I don't know how to properly edit this custom policy in order to enable our users to delete their account. Any help is greatly appreciated, thank you in advance.

**Comment by JasSuri** [comment]
Delete line 196 and 213. Delete step 3.

**Comment by unboeing** [comment]
Thank you, that worked great. One more question, if you don't mind: the B2C_1A_Delete_My_Account" policy user journey starts by asking the user to sign in before it allows them to delete their account and the type of the email address input is 'text'; is there a way to make that input type 'email' (so that it forces an email type keyboard on a mobile device)? Thank you in advance.

**Comment by JasSuri** [comment]
Set the `UserInputType` of the Claim in the `ClaimsSchema` section to `EmailBox`.
