### ISSUE TITLE
Client Credentials Flow

### ISSUE THREAD

**Issue by rpep** [azure-ad-b2c/samples#425]
Hi there,

I've been looking at the B2C documentation, and my understanding was that Client Credentials Flow was not supported in B2C itself - only by treating the B2C tenant as a normal AD tenant and hitting the endpoint at 

`https://login.microsoftonline.com/<yourtenantname>.onmicrosoft.com/.well-known/openid-configuration`

rather than

`https://<yourtenant>.b2clogin.com/(http://b2clogin.com/)<yourtenant>/<yourcustompolicy>/.well-known/openid-configuration`

However, I noticed that a client credentials flow custom policy was recently added in the repository. Is this actually usable at the moment, or is it pre-release? For us as a company, Client Credentials Flow is really important because we need to augment the tokens dynamically, and it's quite a blocker for us in adopting B2C right now. If it is pre-release, is there any ETA on when this feature might be released?

Best wishes,

Dr Ryan Pepper
Onyx Insight

**Comment by JasSuri** [comment]
It’s coming soon.

**Comment by sven5** [comment]
@JasSuri  Is it already available? And how do we obtain a token?

**Comment by sven5** [comment]
Ok, it doesn't seem to work already.
What I've tried:
URL: `https://xxx.b2clogin.com/xxx.onmicrosoft.com/B2C_1A_ClientCredentialsFlow/oauth2/v2.0/token`
with setting all parameters in body I still get an error:
```
{
    "error": "invalid_grant",
    "error_description": "AADB2C90085: The service has encountered an internal error. Please reauthenticate and try again.\r\nCorrelation ID: a1f68dd3-4417-427b-a523-2067120ea5d8\r\nTimestamp: 2022-06-14 12:19:41Z\r\n"
}
```

**Comment by JasSuri** [comment]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-custom-policy

**Comment by sven5** [comment]
I can confirm this is already working. I've mixed up some IDs during my first tests.
However, I'm trying to find out how to add an extension property's value to the token.

**Comment by jordanvector** [comment]
I also cannot get this to work following the example linked above https://docs.microsoft.com/en-us/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-custom-policy , getting only this error in logs

Exception Message:An attempt was made to resolve a protocol handler for unsupported protocol "None" in technical profile with id 

Any idea what I am doing wrong?

**Comment by danielmackay** [comment]
> I can confirm this is already working. I've mixed up some IDs during my first tests. However, I'm trying to find out how to add an extension property's value to the token.

@sven5 - how did you get this to work?  We are having the same problem.

**Comment by sven5** [comment]
@danielmackay What exactly doesn't work for you?
