### ISSUE TITLE
Verify Code button doesn't work if code inserted using keyboard paste

### ISSUE THREAD

**Issue by GitAnubhav1** [azure-ad-b2c/samples#427]
I am using Azure IEF Custom Policy which allows login via phone number for my Mobile application. Everything works fine except one.
The issue I am facing is that after user enters the mobile number and perform send code, "Verify Code" button only works if user manually enters the code or paste it in the enter code text box.
However in mobile the otp code comes on top of the keyboard, when I paste it from there, the verify code button doesn't work.
I have to delete the last number and re-enter it to make it work.
Could you please suggest a fix for this. It is very important for my project release.

**Comment by JasSuri** [comment]
Did you use the latest page contract version?

https://docs.microsoft.com/en-us/azure/active-directory-b2c/page-layout#self-asserted-page-selfasserted

**Comment by GitAnubhav1** [comment]
Thanks...It worked.
