### ISSUE TITLE
Parsed and Prompted Home Realm Discovery?

### ISSUE THREAD

**Issue by alex-mason-jdas** [azure-ad-b2c/samples#43]
I took the default home realm discovery policy and ran with it which is using domain_hint to select IdPs. This works pretty well for a case of serving many customers that have different domains (or lists of IdPs). I am wondering though if it possible to extend that paradigm to prompt for a domain if the domain_hint is not passed? I have tried a couple times with self-asserted claim but don't seem to be able to get it working together. Ideally, the same logic of matching to a knownDomain could be used whether domain_hint passed or prompted.

**Comment by JasSuri** [comment]
You can combine these two samples:
[HRD via Domain_Hint](https://github.com/azure-ad-b2c/samples/tree/master/policies/default-home-realm-discovery)
[HRD by collecting and parsing an email domain](https://github.com/azure-ad-b2c/samples/tree/master/policies/home-realm-discovery-modern)

**Comment by alex-mason-jdas** [comment]
I wonder if I might share my policy to see what am doing wrong as I feel like the logic I have is almost there. I have a parsed domain hint exchange followed by a prompted domain hint exchange preconditioned by the output of the first exchange. I have seen a couple different outcomes neither of which works exactly. One of the outcomes seems to end in some sort of infinite loop. My goal is to use the same matching lookup in both from a known list of domains.

**Comment by alex-mason-jdas** [comment]
So, I closed this issue earlier since I did successfully implement parsed and then prompted HRD. It seems to work fine for interactive logins. I now am wrestling with silent token flow and MSAL.js in particular. @JasSuri When you consider these HRD schemes based on domain_hint etc. do you not think it is necessary to pass both login_hint and domain_hint in order to navigate the orchestration steps? I seem to be able to get silent access token call working only when I intercept a failing silent call and append both domain_hint and login_hint

**Comment by JasSuri** [comment]
I'll look into this and confirm.

**Comment by JasSuri** [comment]
Closing this issue, as it was determined there was an orchestration step without any session management. There is no need to pass login_hint or domain_hint in this sample for silent token calls.
