### ISSUE TITLE
"strongAuthenticationPhoneNumber" was not found

### ISSUE THREAD

**Issue by TechMinder** [azure-ad-b2c/samples#432]
Hi,

Policy sample: **pwd-reset-via-email-or-phone**

I see the following error logged into AppInsights. It may be an obvious misconfiguration or issue. I copied all the policies and followed the instruction.

**Exception Message:A Claim of ClaimType with id "strongAuthenticationPhoneNumber" was not found, which is required by the ClaimsTransformationImpl of Type "Microsoft.Cpim.Data.Transformations.ClaimCopyTransformation" for TransformationMethod "CopyClaim" referenced by the ClaimsTransformation with id "CopyPhoneToReadOnly" in policy "B2C_1A_TrustFrameworkExtensions_EmailOrPhone" of tenant "domain.onmicrosoft.com"., Exception Type:PolicyException, CorrelationID:e8860c63-0964-4086-b4e1-bb5ed068d1b0**

**Comment by JasSuri** [comment]
Can you describe more about your sign up and sign in, and where the issue occurs specfically?
Did you sign up the account with a MFA phone number?

**Comment by TechMinder** [comment]
No, I didn't signup using the MFA phone number. I created accounts using B2C Graph API "https://graph.microsoft.com/v1.0/users".

I want users to add the phone number using the password reset approach if it's not there. We have many accounts that don't have an email address and phone number. The current login only requires login with a username. And we want to migrate the existing accounts to B2C.

I am using the following sample. When I test the policy [PasswordReset_EmailOrPhone.xml](https://github.com/azure-ad-b2c/samples/blob/master/policies/pwd-reset-via-email-or-phone/policy/PasswordReset_EmailOrPhone.xml). It throws the exception.

https://github.com/azure-ad-b2c/samples/tree/master/policies/pwd-reset-via-email-or-phone

**Comment by JasSuri** [comment]
The policy assumes the user is already proofed up for MFA. Your error is because it’s operating on null value since you don’t have the attribute set when you sign up/provisioned the user.

You’d need to adjust it for your scenario. 

Since this isn’t a bug with the policy, I’ll close this issue - you can get design help on stackoverflow with [azure-ad-b2c] tag.
