### ISSUE TITLE
Sign user out after account deletion

### ISSUE THREAD

**Issue by unboeing** [azure-ad-b2c/samples#434]
Hello again. After a user successfully deletes their B2C account using the custom policy from this repo, is there a way to trigger the mobile app to sign out the user? I already have a method that does the signing out, but don't know how to let the app know that a user has indeed deleted their account and thus the user is still signed into the app and can use its account-based features.

**Comment by JasSuri** [comment]
When your app launches the delete user policy, pass in an encoded state parameter with the MSAL library (or other lib). 

When the user completes the journey, the state param is returned to the app. Now use that as an indicator to call logout().

**Comment by JasSuri** [comment]
The user remains logged in at other locations until the access token and refresh token expires.
