### ISSUE TITLE
How to extend Token expiry 

### ISSUE THREAD

**Issue by GitAnubhav1** [azure-ad-b2c/samples#435]
Hi,

For my Mobile app, I am using A B2C IEF Custom Policy which allows login via Phone Number (OTP). The token expiry is default to 24 hrs.
Could you please let me know a way so that I can increase the token expiry time to 30-60 days in the custom policy.
I will highly grateful for your response regarding this.

Thanks,
Anubhav

**Comment by JasSuri** [comment]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens?pivots=b2c-custom-policy

**Comment by GitAnubhav1** [comment]
Hi Jas,

Thanks a ton for your response. I already tried everything mentioned in the link you mentioned but still I am facing the issue of token getting expired in 24 hrs. I am attaching the xml's with the post, If possible could you check and let me know what I am doing wrong here. I will be grateful for your response on this.

Thanks,
Anubhav[
[identityxmls.zip](https://github.com/azure-ad-b2c/samples/files/9011245/identityxmls.zip)
]
