### ISSUE TITLE
Password Reset Only does not contain a send claims step

### ISSUE THREAD

**Issue by zlannin** [azure-ad-b2c/samples#44]
Following the instructions https://github.com/azure-ad-b2c/samples/tree/master/policies/password-reset-only I get an error uploading `TrustFrameworkExtensions.xml`
`Validation failed: 1 validation error(s) found in policy "B2C_1A_TRUSTFRAMEWORKEXTENSIONS" of tenant "tenantname.onmicrosoft.com".User journey 'PasswordReset' does not contain a send claims step.`

**Comment by JasSuri** [comment]
@WhippsP can you review this?

**Comment by lasyan3** [comment]
Adding this last OrchestrationStep works for me:
`<OrchestrationStep Order="4" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />`

**Comment by JasSuri** [comment]
Added fix as mentioned above.
