### ISSUE TITLE
Auto Account Link - Twitter AuthorizationError

### ISSUE THREAD

**Issue by RaphaelSilv** [azure-ad-b2c/samples#443]
Hello, I am setting up Twitter as a social login option following this [doc reference](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-twitter?pivots=b2c-custom-policy) on auto-account-link policies. It's been quite some time since I've finished the policy side but keep getting consistently the authorization error below:

**correlationId**: 1bb357d5-ecdc-437f-97cb-9958ac5940f3

```JSON
{
    "Key": "OAuth1RequestInfo",
    "Value": {
        "TechnicalProfileId": "Twitter-OAuth1-SignIn",
        "AccessTokenEndpoint": "https://api.twitter.com/oauth/access_token",
        "AuthorizationEndpoint": "https://api.twitter.com/oauth/authenticate",
        "CallbackUri": "https://<tenant-name>.b2clogin.com/<tenant-name>.onmicrosoft.com/b2c_1a_accountlink_susi/oauth1/authresp",
        "ClientId": "aDNZQ1dZTlJEZjFGUXBzb0ZfY1U6MTpjaQ"
    }
},
{
    "Key": "AuthorizationError",
    "Value": "The call to https://api.twitter.com/oauth/request_token for a request token of aDNZQ1dZTlJEZjFGUXBzb0ZfY1U6MTpjaQ returned an error Unauthorized"
}
```

Things I've tried:
- Reset client secret and app Id;
- Make sure there is no typo while pasting secret on policy keys;
- Enabled Oauth1 and Oauth2 on the Twitter side
  - The docs say Oauth2 should be enabled but on policy call back there is a reference to oauth1.
- Make sure the callback URL is set correctly. 
- Set Single Page App as the app type (assuming this is correct for my use case)
- 
![image](https://user-images.githubusercontent.com/42193694/180796273-d084d2b7-a905-4fc7-8ad1-5cc9066f779c.png)

@JasSuri in a similar issue (#138) you've stated:
> Usually this error is because of a bad secret or **you haven’t given the right permissions at Twitter**.

What does this last part mean? I set up a test tenant using your starter pack but stuck on the same problem. Is there any config on the manifest file we should be aware of while setting up Twitter?

**Comment by cyrilmatthew26** [comment]
I've had the same issue before. What helped me was to apply for elevated access to the twitter API which is also in the free tier. It gives extra permissions to fetch the data from twitter and also gives the added advantage of having 3 separate applications for up to 3 environments. 
https://developer.twitter.com/en/portal/products/elevated

**Comment by RaphaelSilv** [comment]
Thanks for the input @cyrilmatthew26! I've applied to it, let's wait.

**Comment by JasSuri** [comment]
Let us know if it solves the issue, and we can update the docs.

**Comment by RaphaelSilv** [comment]
That was pretty much the issue guys, after I got elevated access I had to create a new app and it all worked fine. Thanks, @cyrilmatthew26!
 
@JasSuri if you are going to update the documentation, I suggest renaming `your-user-flow-Id` to `your-user-user-journey-Id` as well as the first appears oddly misleading to me.

Please let me know if I should open an issue elsewhere.

**Comment by kengaderdus** [comment]
Related to https://github.com/MicrosoftDocs/azure-docs/issues/96952
