### ISSUE TITLE
Language parameter not returned in claims

### ISSUE THREAD

**Issue by cyrilmatthew26** [azure-ad-b2c/samples#444]
The requirement is get the language parameter in the request from the application which is then stored in an extension attribute in Azure AD. It works fine for a normal SignUpSignIn user journey.

Issue:
When adding it to different social claims providers such as twitter or linkedIn, the response is not as expected.

Line added in output claims of the technical profile in the claimsprovider.
< OutputClaim ClaimTypeReferenceId="extension_Locale" PartnerClaimType="locale" DefaultValue="{Culture:LanguageName}" />

The decoded token contains the value "Culture:LanguageName" instead of the actual language codes, for example "en" or "es" or "ja".

![image](https://user-images.githubusercontent.com/50162188/180867806-3520be98-d823-42e6-a1bf-772b868536bd.png)

**Comment by cyrilmatthew26** [comment]
Here's the LinkedIn profile,

<ClaimsProvider>
			<Domain>linkedin.com</Domain>
			<DisplayName>LinkedIn</DisplayName>
			<TechnicalProfiles>
				<TechnicalProfile Id="LinkedIn-OAuth2">
				  <DisplayName>LinkedIn</DisplayName>
			  	<Protocol Name="OAuth2" />
		  		<Metadata>
			  		<Item Key="ProviderName">linkedin</Item>
				  	<Item Key="authorization_endpoint">https://www.linkedin.com/oauth/v2/authorization</Item>
  					<Item Key="AccessTokenEndpoint">https://www.linkedin.com/oauth/v2/accessToken</Item>
	  				<Item Key="ClaimsEndpoint">https://api.linkedin.com/v2/me</Item>
		  			<Item Key="scope">r_emailaddress r_liteprofile</Item>
			  		<Item Key="HttpBinding">POST</Item>
				  	<Item Key="external_user_identity_claim_id">id</Item>
					  <Item Key="BearerTokenTransmissionMethod">AuthorizationHeader</Item>
	  				<Item Key="ResolveJsonPathsInJsonTokens">true</Item>
		  			<Item Key="UsePolicyInRedirectUri">false</Item>
			  		<Item Key="client_id">{Settings:AADLinkedInClientId}</Item>
            <Item Key="ClaimTypeOnWhichToEnable">identityProvider</Item>
            <Item Key="ClaimValueOnWhichToEnable">linkedin.com</Item>
				  </Metadata>
	  			<CryptographicKeys>
            <Key Id="client_secret" StorageReferenceId="{Settings:AADLinkedInSecretName}"/>
			  	</CryptographicKeys>
				  <InputClaims />
				  <OutputClaims>
	  				<OutputClaim ClaimTypeReferenceId="issuerUserId" PartnerClaimType="id" />
            <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="email" />
			  		<OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="firstName.localized" />
				  	<OutputClaim ClaimTypeReferenceId="surname" PartnerClaimType="lastName.localized" />
	  				<OutputClaim ClaimTypeReferenceId="identityProvider" DefaultValue="linkedin.com" AlwaysUseDefaultValue="true" />
		  			<OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="socialIdpAuthentication" AlwaysUseDefaultValue="true" />
            <OutputClaim ClaimTypeReferenceId="extension_Locale" PartnerClaimType="locale" DefaultValue="{Culture:LanguageName}" />
            <OutputClaim ClaimTypeReferenceId="identityProviderAccessToken" PartnerClaimType="{oauth2:access_token}" />
	  			</OutputClaims>
		  		<OutputClaimsTransformations>
			  		<OutputClaimsTransformation ReferenceId="ExtractGivenNameFromLinkedInResponse" />
				  	<OutputClaimsTransformation ReferenceId="ExtractSurNameFromLinkedInResponse" />
					<OutputClaimsTransformation ReferenceId="CreateRandomUPNUserName" />
	  				<OutputClaimsTransformation ReferenceId="CreateUserPrincipalName" />
                                        <OutputClaimsTransformation ReferenceId="CreateUserIdentity" />
					  <OutputClaimsTransformation ReferenceId="AppendUserIdentity" />
            <OutputClaimsTransformation ReferenceId="CreateDisplayNameFromFirstNameAndLastName" />
	  			</OutputClaimsTransformations>
		  		<UseTechnicalProfileForSessionManagement ReferenceId="SM-SocialLogin" />
			  </TechnicalProfile>
			</TechnicalProfiles>
		</ClaimsProvider>


And also the write User technical profile below:
<TechnicalProfile Id="AAD-UserWriteUsingSocialId">
          <Metadata>
            <Item Key="api-version">1.6</Item>
            <Item Key="Operation">Write</Item>
            <Item Key="RaiseErrorIfClaimsPrincipalAlreadyExists">true</Item>
            <Item Key="UserMessageIfClaimsPrincipalAlreadyExists">You are already registered, please press the back button and sign in instead.</Item>
          </Metadata>
          <IncludeInSso>false</IncludeInSso>
          <InputClaimsTransformations>
            <InputClaimsTransformation ReferenceId="CreateOtherMailsFromEmail" />
            <InputClaimsTransformation ReferenceId="CreateRandomPassword" />
          </InputClaimsTransformations>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="userIdentities" PartnerClaimType="userIdentities" Required="true" />
          </InputClaims>
          <PersistedClaims>
            
            <PersistedClaim ClaimTypeReferenceId="userIdentities" />
            <PersistedClaim ClaimTypeReferenceId="email" PartnerClaimType="signInNames.emailAddress"/>
            <PersistedClaim ClaimTypeReferenceId="newPassword" PartnerClaimType="password"/>
            <PersistedClaim ClaimTypeReferenceId="passwordPolicies" DefaultValue="DisablePasswordExpiration, DisableStrongPassword" />
            <PersistedClaim ClaimTypeReferenceId="userPrincipalName" />
            <PersistedClaim ClaimTypeReferenceId="mailNickName" DefaultValue="unknown" />
            <PersistedClaim ClaimTypeReferenceId="displayName" DefaultValue="unknown" />  
            
            <PersistedClaim ClaimTypeReferenceId="otherMails" />
            <PersistedClaim ClaimTypeReferenceId="givenName" />
            <PersistedClaim ClaimTypeReferenceId="surname" />
            <PersistedClaim ClaimTypeReferenceId="extension_Locale" AlwaysUseDefaultValue="true" DefaultValue="{Culture:LanguageName}" />
          </PersistedClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="objectId" />
            <OutputClaim ClaimTypeReferenceId="userIdentities"/>
            <OutputClaim ClaimTypeReferenceId="newUser" PartnerClaimType="newClaimsPrincipalCreated" />
            
            <OutputClaim ClaimTypeReferenceId="otherMails" />
          </OutputClaims>
          <IncludeTechnicalProfile ReferenceId="AAD-Common" />
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-AAD" />
        </TechnicalProfile>

**Comment by cyrilmatthew26** [comment]
Just found this doc where it states that google and facebook don't support ui_locales resolving. 
https://docs.microsoft.com/en-au/azure/active-directory-b2c/language-customization?pivots=b2c-custom-policy#social-identity-provider-translations

Is it true then for LinkedIn, Twitter, Apple or even with federating with another Azure AD tenant?

**Comment by JasSuri** [comment]
Are you passing ui_locales query param in the auths request?

**Comment by JasSuri** [comment]
> Just found this doc where it states that google and facebook don't support ui_locales resolving. https://docs.microsoft.com/en-au/azure/active-directory-b2c/language-customization?pivots=b2c-custom-policy#social-identity-provider-translations
> 
> Is it true then for LinkedIn, Twitter, Apple as well?

We can pass it to them, but doesn’t mean they’ll listen. Maybe they use a different query param name (which we can accommodate) or don’t support a param at all.
