### ISSUE TITLE
force-unique-email-across-social-identities and force unique when creating local account

### ISSUE THREAD

**Issue by fugaku** [azure-ad-b2c/samples#445]
When using the force-unique-email-across-social-identities policy, the flows are 
- signup with local account 
- login with a social identity with same email as above and will get the error message of email exists

But can we also have the error message when doing the local account signup after doing the social identity login
- login with a social identity, this will create a new user in B2C
- signup with local account, but using the same email address as above, this should show error message too ?

**Comment by eskaufel** [comment]
There will be no error message, but the user can log in using a password reset.
