### ISSUE TITLE
What is api-version=1.6 metadata?

### ISSUE THREAD

**Issue by mrochon** [azure-ad-b2c/samples#449]
The policy uses this as metadata in some AAD TechnicalProfiles. I do not see it documented anywhere. What is its purpose?

**Comment by JasSuri** [comment]
Required for the ability to read and update the alternativeSecurityId. We use it in the account linking samples.

**Comment by mrochon** [comment]
But AAD-UserWrite/ReadUsingAlternativeSecurityId in starter packs do it without this metadata key.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by JasSuri** [comment]
They do not update the attribute, just read or write. Without this flag, you will find that appending new id's will drop the old id's.
