### ISSUE TITLE
You are already registered, please press the back button and sign in instead

### ISSUE THREAD

**Issue by enterprisebug** [azure-ad-b2c/samples#452]
I created a signup/signin policy, to add a custom claim (`{Settings:CustomClaimTenantId}`) to AAD.

The user is created in AAD with my custom claim but a error message is displayed to the user `You are already registered, please press the back button and sign in instead`.

![eyzu4](https://user-images.githubusercontent.com/1539741/183382181-8430a5c3-5658-4381-ae85-75e98df23d2a.png)

### Question
What am I missing? After the user is created in AAD i am assuming that he "automatically" gets signed-in?

### SignUpOrSignin.xml

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <TrustFrameworkPolicy
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06"
      PolicySchemaVersion="0.3.0.0"
      TenantId="{Settings:Tenant}"
      PolicyId="B2C_1A_signup_signin"
      PublicPolicyUri="http://{Settings:Tenant}/B2C_1A_signup_signin"
      DeploymentMode="Development"
      UserJourneyRecorderEndpoint="urn:journeyrecorder:applicationinsights">

      <BasePolicy>
        <TenantId>{Settings:Tenant}</TenantId>
        <PolicyId>B2C_1A_TrustFrameworkExtensions</PolicyId>
      </BasePolicy>

      <RelyingParty>
        <DefaultUserJourney ReferenceId="CustomSignUpSignIn" />
        <UserJourneyBehaviors>
          <JourneyInsights TelemetryEngine="ApplicationInsights" InstrumentationKey="{Settings:ApplicationInsightsInstrumentationKey}" DeveloperMode="{Settings:DeveloperMode}" ClientEnabled="false" ServerEnabled="true" TelemetryVersion="1.0.0" />
        </UserJourneyBehaviors>
        <TechnicalProfile Id="PolicyProfile">
          <DisplayName>PolicyProfile</DisplayName>
          <Protocol Name="OpenIdConnect" />
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="displayName" />
            <OutputClaim ClaimTypeReferenceId="givenName" />
            <OutputClaim ClaimTypeReferenceId="surname" />
            <OutputClaim ClaimTypeReferenceId="email" />
            <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub"/>
            <OutputClaim ClaimTypeReferenceId="identityProvider" />
            <OutputClaim ClaimTypeReferenceId="tenantId" AlwaysUseDefaultValue="true" DefaultValue="{Policy:TenantObjectId}" />
            <OutputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />
          </OutputClaims>
          <SubjectNamingInfo ClaimType="sub" />
        </TechnicalProfile>
      </RelyingParty>
    </TrustFrameworkPolicy>

### TrustFrameworkExtensions.xml

    <?xml version="1.0" encoding="utf-8" ?>
    <TrustFrameworkPolicy 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06" 
      PolicySchemaVersion="0.3.0.0" 
      TenantId="{Settings:Tenant}" 
      PolicyId="B2C_1A_TrustFrameworkExtensions" 
      PublicPolicyUri="http://{Settings:Tenant}/B2C_1A_TrustFrameworkExtensions">
      
      <BasePolicy>
        <TenantId>{Settings:Tenant}</TenantId>
        <PolicyId>B2C_1A_TrustFrameworkLocalization</PolicyId>
      </BasePolicy>
    <BuildingBlocks>
        <ClaimsSchema>
          <ClaimType Id="{Settings:CustomClaimTenantId}">
            <DisplayName>Tenant Id</DisplayName>
            <DataType>string</DataType>
            <UserHelpText>Your Tenant Id.</UserHelpText>
            <UserInputType>TextBox</UserInputType>
            <Restriction>
              <Pattern RegularExpression="^[a-z]+$" HelpText="Please enter only lowercase characters with no spaces."/>
            </Restriction>
          </ClaimType>
        </ClaimsSchema>

      </BuildingBlocks>

      <ClaimsProviders>

        <ClaimsProvider>
          <Domain>google.com</Domain>
          <DisplayName>Google</DisplayName>
          <TechnicalProfiles>
            <TechnicalProfile Id="Google-OAuth2">
              <DisplayName>Google</DisplayName>
              <Protocol Name="OAuth2" />
              <Metadata>
                <Item Key="ProviderName">google</Item>
                <Item Key="authorization_endpoint">https://accounts.google.com/o/oauth2/auth</Item>
                <Item Key="AccessTokenEndpoint">https://accounts.google.com/o/oauth2/token</Item>
                <Item Key="ClaimsEndpoint">https://www.googleapis.com/oauth2/v1/userinfo</Item>
                <Item Key="scope">email profile</Item>
                <Item Key="HttpBinding">POST</Item>
                <Item Key="UsePolicyInRedirectUri">false</Item>
                <Item Key="client_id">{Settings:GoogleClientId}</Item>
              </Metadata>
              <CryptographicKeys>
                <Key Id="client_secret" StorageReferenceId="B2C_1A_GoogleSecret" />
              </CryptographicKeys>
              <OutputClaims>
                <OutputClaim ClaimTypeReferenceId="issuerUserId" PartnerClaimType="id" />
                <OutputClaim ClaimTypeReferenceId="email" PartnerClaimType="email" />
                <OutputClaim ClaimTypeReferenceId="givenName" PartnerClaimType="given_name" />
                <OutputClaim ClaimTypeReferenceId="surname" PartnerClaimType="family_name" />
                <OutputClaim ClaimTypeReferenceId="displayName" PartnerClaimType="name" />
                <OutputClaim ClaimTypeReferenceId="identityProvider" DefaultValue="google.com" />
                <OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="socialIdpAuthentication" />
              </OutputClaims>
              <OutputClaimsTransformations>
                <OutputClaimsTransformation ReferenceId="CreateRandomUPNUserName" />
                <OutputClaimsTransformation ReferenceId="CreateUserPrincipalName" />
                <OutputClaimsTransformation ReferenceId="CreateAlternativeSecurityId" />
                <OutputClaimsTransformation ReferenceId="CreateSubjectClaimFromAlternativeSecurityId" />
              </OutputClaimsTransformations>
              <UseTechnicalProfileForSessionManagement ReferenceId="SM-SocialLogin" />
            </TechnicalProfile>
          </TechnicalProfiles>
        </ClaimsProvider>

        <ClaimsProvider>
          <DisplayName>Local Account SignIn</DisplayName>
          <TechnicalProfiles>
            <TechnicalProfile Id="login-NonInteractive">
              <Metadata>
                <Item Key="client_id">ProxyIdentityExperienceFrameworkAppId</Item>
                <Item Key="IdTokenAudience">IdentityExperienceFrameworkAppId</Item>
              </Metadata>
              <InputClaims>
                <InputClaim ClaimTypeReferenceId="client_id" DefaultValue="ProxyIdentityExperienceFrameworkAppId" />
                <InputClaim ClaimTypeReferenceId="resource_id" PartnerClaimType="resource" DefaultValue="IdentityExperienceFrameworkAppId" />
              </InputClaims>
            </TechnicalProfile>
          </TechnicalProfiles>
        </ClaimsProvider>

        <ClaimsProvider>
          <DisplayName>Azure Active Directory</DisplayName>
          <TechnicalProfiles>
            <TechnicalProfile Id="AAD-Common">
              <Metadata>
                <Item Key="ClientId">{Settings:B2CExtensionsAppClientId}</Item>
                <Item Key="ApplicationObjectId">{Settings:B2CExtensionsAppObjectId}</Item>
              </Metadata>
            </TechnicalProfile>
            
            <TechnicalProfile Id="AAD-UserWriteUsingLogonEmail">
              <PersistedClaims>
                <PersistedClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}"/>
              </PersistedClaims>
            </TechnicalProfile>
            
            <TechnicalProfile Id="AAD-UserWriteUsingAlternativeSecurityId">
              <PersistedClaims>
                <PersistedClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}"/>
              </PersistedClaims>
            </TechnicalProfile>
            
            <TechnicalProfile Id="AAD-UserWriteProfileUsingObjectId">
              <PersistedClaims>
                <PersistedClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}"/>
              </PersistedClaims>
            </TechnicalProfile>
            
            <TechnicalProfile Id="AAD-UserReadUsingEmailAddress">
              <OutputClaims>
                <OutputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />
              </OutputClaims>
            </TechnicalProfile>
            
            <TechnicalProfile Id="AAD-UserReadUsingObjectId">
              <OutputClaims>
                <OutputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />
              </OutputClaims>
            </TechnicalProfile>
            
            <TechnicalProfile Id="AAD-UserReadUsingAlternativeSecurityId">
              <OutputClaims>
                <OutputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />
              </OutputClaims>
            </TechnicalProfile>

            <TechnicalProfile Id="AAD-UserReadUsingEmailAddress-NoError">
              <Metadata>
                <Item Key="Operation">Read</Item>
                <Item Key="RaiseErrorIfClaimsPrincipalDoesNotExist">false</Item>
                <Item Key="UserMessageIfClaimsPrincipalDoesNotExist">An account could not be found for the provided user ID.</Item>
              </Metadata>
              <IncludeInSso>false</IncludeInSso>
              <InputClaims>
                <InputClaim ClaimTypeReferenceId="email" PartnerClaimType="signInNames.emailAddress" Required="true" />
              </InputClaims>
              <OutputClaims>
                
                <OutputClaim ClaimTypeReferenceId="objectId" />
                <OutputClaim ClaimTypeReferenceId="authenticationSource" DefaultValue="localAccountAuthentication" />
                
                <OutputClaim ClaimTypeReferenceId="userPrincipalName" />
                <OutputClaim ClaimTypeReferenceId="displayName" />
                <OutputClaim ClaimTypeReferenceId="givenName" />
                <OutputClaim ClaimTypeReferenceId="surname" />
                <OutputClaim ClaimTypeReferenceId="accountEnabled" />
                <OutputClaim ClaimTypeReferenceId="otherMails" />
                <OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" />
              </OutputClaims>
              <IncludeTechnicalProfile ReferenceId="AAD-Common" />
            </TechnicalProfile>
          </TechnicalProfiles>
        </ClaimsProvider>

        <ClaimsProvider>
          <DisplayName>REST APIs</DisplayName>
          <TechnicalProfiles>
            <TechnicalProfile Id="REST-ValidateTenantId">
              <DisplayName>Validate TenantId against Azure Function web hook</DisplayName>
              <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
              <Metadata>
                
                <Item Key="ServiceUrl">{Settings:AzureFunctionBaseUrl}/api/TenantIdValidation</Item>
                <Item Key="SendClaimsIn">Body</Item>
                <Item Key="AuthenticationType">Basic</Item>
              </Metadata>
              <CryptographicKeys>
                <Key Id="BasicAuthenticationUsername" StorageReferenceId="B2C_1A_AzureFunctionRestApiUsername" />
                <Key Id="BasicAuthenticationPassword" StorageReferenceId="B2C_1A_AzureFunctionRestApiPassword" />
              </CryptographicKeys>
              <InputClaims>
                
                <InputClaim ClaimTypeReferenceId="objectId" />
                <InputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />
              </InputClaims>
              <OutputClaims>
                <OutputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" Required="true" />
              </OutputClaims>
              <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
            </TechnicalProfile>
          </TechnicalProfiles>
        </ClaimsProvider>

        <ClaimsProvider>
          <DisplayName>Self Asserted</DisplayName>
          <TechnicalProfiles>

            <TechnicalProfile Id="SelfAsserted-Social">
              <DisplayName>User ID signup</DisplayName>
              <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
              <Metadata>
                <Item Key="ContentDefinitionReferenceId">api.socialccountsignup</Item>
              </Metadata>
              <CryptographicKeys>
                <Key Id="issuer_secret" StorageReferenceId="B2C_1A_TokenSigningKeyContainer" />
              </CryptographicKeys>
              <InputClaims>
                
                <InputClaim ClaimTypeReferenceId="displayName" />
                <InputClaim ClaimTypeReferenceId="givenName" />
                <InputClaim ClaimTypeReferenceId="surname" />
                <InputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />
              </InputClaims>
              <DisplayClaims>
                
                <DisplayClaim ClaimTypeReferenceId="displayName" />
                <DisplayClaim ClaimTypeReferenceId="givenName" />
                <DisplayClaim ClaimTypeReferenceId="surname" />
                <DisplayClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" Required="true" />
              </DisplayClaims>
              <OutputClaims>
                
                <OutputClaim ClaimTypeReferenceId="objectId" />
                <OutputClaim ClaimTypeReferenceId="newUser" />
                <OutputClaim ClaimTypeReferenceId="executed-SelfAsserted-Input" DefaultValue="true" />
                <OutputClaim ClaimTypeReferenceId="{Settings:CustomClaimTenantId}" />

                
                <OutputClaim ClaimTypeReferenceId="displayName" />
                <OutputClaim ClaimTypeReferenceId="givenName" />
                <OutputClaim ClaimTypeReferenceId="surname" />
              </OutputClaims>
              <ValidationTechnicalProfiles>
                <ValidationTechnicalProfile ReferenceId="REST-ValidateTenantId" />
                <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
              </ValidationTechnicalProfiles>
              <UseTechnicalProfileForSessionManagement ReferenceId="SM-SocialSignup" />
            </TechnicalProfile>

            <TechnicalProfile Id="SelfAsserted-ProfileUpdate">
              <DisplayName>User ID signup</DisplayName>
              <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.SelfAssertedAttributeProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
              <Metadata>
                <Item Key="ContentDefinitionReferenceId">api.selfasserted.profileupdate</Item>
              </Metadata>
              <IncludeInSso>false</IncludeInSso>
              <InputClaims>
                <InputClaim ClaimTypeReferenceId="alternativeSecurityId" />
                <InputClaim ClaimTypeReferenceId="userPrincipalName" />

                
                <InputClaim ClaimTypeReferenceId="givenName" />
                <InputClaim ClaimTypeReferenceId="surname" />
              </InputClaims>
              <OutputClaims>
                
                <OutputClaim ClaimTypeReferenceId="executed-SelfAsserted-Input" DefaultValue="true" />

                
                <OutputClaim ClaimTypeReferenceId="givenName" />
                <OutputClaim ClaimTypeReferenceId="surname" />
              </OutputClaims>
              <ValidationTechnicalProfiles>
                <ValidationTechnicalProfile ReferenceId="AAD-UserWriteProfileUsingObjectId" />
              </ValidationTechnicalProfiles>
            </TechnicalProfile>
          </TechnicalProfiles>
        </ClaimsProvider>

      </ClaimsProviders>

      <UserJourneys>
        <UserJourney Id="CustomSignUpSignIn">
          <OrchestrationSteps>

            <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin">
              <ClaimsProviderSelections>
                <ClaimsProviderSelection TargetClaimsExchangeId="GoogleExchange" />
                <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
              </ClaimsProviderSelections>
              <ClaimsExchanges>
                <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
              </ClaimsExchanges>
            </OrchestrationStep>

            
            <OrchestrationStep Order="2" Type="ClaimsExchange">
              <Preconditions>
                <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
                  <Value>objectId</Value>
                  <Action>SkipThisOrchestrationStep</Action>
                </Precondition>
              </Preconditions>
              <ClaimsExchanges>
                <ClaimsExchange Id="GoogleExchange" TechnicalProfileReferenceId="Google-OAuth2" />
                <ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmail" />
              </ClaimsExchanges>
            </OrchestrationStep>

            
            <OrchestrationStep Order="3" Type="ClaimsExchange">
              <Preconditions>
                <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
                  <Value>authenticationSource</Value>
                  <Value>localAccountAuthentication</Value>
                  <Action>SkipThisOrchestrationStep</Action>
                </Precondition>
              </Preconditions>
              <ClaimsExchanges>
                <ClaimsExchange Id="AADUserReadUsingAlternativeSecurityId" TechnicalProfileReferenceId="AAD-UserReadUsingAlternativeSecurityId-NoError" />
              </ClaimsExchanges>
            </OrchestrationStep>

            
            <OrchestrationStep Order="4" Type="ClaimsExchange">
              <Preconditions>
                <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
                  <Value>objectId</Value>
                  <Action>SkipThisOrchestrationStep</Action>
                </Precondition>
              </Preconditions>
              <ClaimsExchanges>
                <ClaimsExchange Id="SelfAsserted-Social" TechnicalProfileReferenceId="SelfAsserted-Social" />
              </ClaimsExchanges>
            </OrchestrationStep>

            
            <OrchestrationStep Order="5" Type="ClaimsExchange">
              <Preconditions>
                <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
                  <Value>authenticationSource</Value>
                  <Value>socialIdpAuthentication</Value>
                  <Action>SkipThisOrchestrationStep</Action>
                </Precondition>
              </Preconditions>
              <ClaimsExchanges>
                <ClaimsExchange Id="AADUserReadWithObjectId" TechnicalProfileReferenceId="AAD-UserReadUsingObjectId" />
              </ClaimsExchanges>
            </OrchestrationStep>
            
            <OrchestrationStep Order="6" Type="ClaimsExchange">
              <Preconditions>
                <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
                  <Value>objectId</Value>
                  <Action>SkipThisOrchestrationStep</Action>
                </Precondition>
              </Preconditions>
              <ClaimsExchanges>
                <ClaimsExchange Id="AADUserWrite" TechnicalProfileReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
              </ClaimsExchanges>
            </OrchestrationStep>

            <OrchestrationStep Order="7" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />

          </OrchestrationSteps>
          <ClientDefinition ReferenceId="DefaultWeb" />
        </UserJourney>
      </UserJourneys>

    </TrustFrameworkPolicy>

**Comment by JasSuri** [comment]
Best to troubleshoot on stackoverflow. This is not an issue with any sample here. Your issue is likely that you call a technical profile which is defined in multiple files, and it ends up calling your “AAD Write” technical profile twice, because it’s referenced in more than one instance of this technical profile.

**Comment by enterprisebug** [comment]
@JasSuri thanks for the hint. I will investigate this on my policy and post an update here. Makes absolutely sense what you wrote.

**Comment by enterprisebug** [comment]
It looks like i did not correctly understand the inheritance model. Specifically how the files get merged.

Example:

`Base.xml`

    <ValidationTechnicalProfiles>
        <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
    </ValidationTechnicalProfiles>

`Extension.xml`

    <ValidationTechnicalProfiles>
        <ValidationTechnicalProfile ReferenceId="REST-ValidateTenantId" />
        <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
    </ValidationTechnicalProfiles>

My assumption after both files get merged:

    <ValidationTechnicalProfiles>
        <ValidationTechnicalProfile ReferenceId="REST-ValidateTenantId" />
        <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
    </ValidationTechnicalProfiles>

But it looks like the merge is performed like this:

    <ValidationTechnicalProfiles>
        <ValidationTechnicalProfile ReferenceId="REST-ValidateTenantId" />
        <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
        <ValidationTechnicalProfile ReferenceId="AAD-UserWriteUsingAlternativeSecurityId" />
    </ValidationTechnicalProfiles>

Of course that explains why `AAD write` is performed twice.

@JasSuri

**Comment by JasSuri** [comment]
Exactly right, remove the VTP in one instance of your TPs, and problem is solved.

**Comment by AntonyF-Andreani** [comment]
I know this issue is closed, but it provided a solution for a similar case I encountered. Perhaps this could be included in the documentation regarding the merge behavior, as it happened to me as well.

Thanks for posting it and share the solution @enterprisebug @JasSuri !!!!
