### ISSUE TITLE
Linking forgot password flow using TOTP

### ISSUE THREAD

**Issue by pd-sgdev1** [azure-ad-b2c/samples#454]
Hi,

How do you make forgot password link work from this example? There is a PasswordReset_TOTP policy but I can't figure out how to trigger this flow from the sign-in page.

https://github.com/azure-ad-b2c/samples/tree/master/policies/totp

Thanks

**Comment by JasSuri** [comment]
It’s configured for legacy password reset flow.

Change to the new flow: https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended
