### ISSUE TITLE
Empty policy with custom email verification with displayControl without givenName/surName

### ISSUE THREAD

**Issue by skamoda** [azure-ad-b2c/samples#46]
Hello,
I followed this [tutorial](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-email-verifcation-displaycontrol) with Microsoft B2C documentation. In my policies I didn't use claims firstName (`givenName`) and lastName (`surName`). I only used `displayName`. After uploading this policy to my b2c tenant and running policy I've got empty html page. 

I tried to troubleshoot sign up policy with application insights but no errors showed. Weird is that after adding at least one of these claims policy "renders" correctly.

**Comment by JasSuri** [comment]
What does the browser Console log show? Can you share your "Run Now" policy link?
When you say you didn't use those claims, can you provide a snippet to show what your technical profile looks like?

**Comment by skamoda** [comment]
Hello, Console log shows nothing but I figured out that we hide some controls at the beginning (with html). I think this issue can be closed because after changing our custom html page, controls from b2c policy were shown. Sorry for taking your time
