### ISSUE TITLE
KMSI (keep me signed in) - api.selfasserted

### ISSUE THREAD

**Issue by Casper-Olsen** [azure-ad-b2c/samples#462]
Hi

Back in 2020 the following answer was provided, with regards to using KMSI in the api.selfasserted ContentDefinition.
<https://stackoverflow.com/a/63791443/2887684>
**"Unfortunately right now, KMSI only works against the combined signup/signin flow, which ties you to username/password UI."**

Is this still the case, or is it possible to use KMSI with api.selfasserted now?
I haven't been able to make it work and it seems like a major limitation for api.selfasserted.

**Comment by JasSuri** [comment]
Still the case. Keep questions on SO, and bugs with a sample on here.

**Comment by Casper-Olsen** [comment]
> Still the case. Keep questions on SO, and bugs with a sample on here.

My bad, I'll use SO in the future.
And thank you for the answer :)
