### ISSUE TITLE
how to configure resource in OpenIdConnect federation

### ISSUE THREAD

**Issue by lnavarette** [azure-ad-b2c/samples#463]
i'm working on setting up federation to adfs, i've followed a few of the examples here and they've helped a lot. 

hoping someone might be able to help me in configuring the technical profile to send the resource parameter when making the request to the authorize api. 

i have something that looks like this:
https://github.com/azure-ad-b2c/samples/blob/a0f51828656dde37373d8bf02b461a0206bed1a2/policies/global-architecture-model/policies/global%20funnel%20tenant/B2C_1A_FederatedIdPs.xml#L100-L112

I want to add configuration such that the call to authorize might look like `.../oauth2/authorize?resource=myresource&...`

**Comment by JasSuri** [comment]
Additional query params can be sent through InputClaims.

https://learn.microsoft.com/en-us/azure/active-directory-b2c/openid-connect-technical-profile#input-claims
