### ISSUE TITLE
Custom Policy not updating Caching issue

### ISSUE THREAD

**Issue by akhileshnirapure** [azure-ad-b2c/samples#467]
Hi,

I'm using sample policies and tailoring to our needs. The problem is when updating custom policy and uploading via Azure IEF UI the policy changes are not reflecting for ~5-10mins. The tenant has no other policies. It's causing headache when troubleshooting, even the appinsight response doesn't give enough clue what's breaking.

This behaviour is not seen on other b2c tenant with custom policies.

I'm sure I'm not the only one who has experienced this. Please recommend way forward it's anyways quite difficult to troubleshoot and with caching you are left with hit-n-trial.

Please help.

**Comment by JasSuri** [comment]
This is not a bug with any sample here. Please open a MS Support ticket.
