### ISSUE TITLE
Forget password not working with this custom policy

### ISSUE THREAD

**Issue by gnnsekhar** [azure-ad-b2c/samples#468]
I am using this sample home realm discovery custom policy and it works well. Only issue is with this policy if i use forgot password link i am getting the below exception.
"AADB2C90037: An error occurred while processing the request. Please contact administrator of the site you are trying to access."

To troubleshoot further i configured application insights in the custom policy and verified the logs and it logs the exception as below
"The claim type "alternativeSecurityId", designated as the identifier claim type, could not be found in the claims collection for the claims principal in tenant id".

Any inputs on this will be greatly appreciated. Thanks

**Comment by JasSuri** [comment]
Link to sample?
CorrelationId?
