### ISSUE TITLE
Azure AD B2C Custom Policy with external identity provider Error AADB2C90289

### ISSUE THREAD

**Issue by anandp2304** [azure-ad-b2c/samples#469]
I have successfully configured an external identity provider using Azure AD B2C Custom policy. The authorize endpoint is passed correct acr_values too. As I launch the authorize endpoint, I am taken to the login screen from identity provider. As soon as I enter my credentials and hit 'Login',I expect the authentication response to be redirected to my B2C /auth/resp URL (https://<>.b2clogin.com/<>.onmicrosoft.com/oauth2/authresp), configured with the identity provider. However, I end up getting an exception as below - AADB2C90289: We encountered an error connecting to the identity provider. Please try again later. Correlation ID: ef54294f-2a9d-4e18-bc03-511bcc713cde Timestamp: 2022-10-10 04:04:09Z

AADB2C90289: We encountered an error connecting to the identity provider. Please try again later. Correlation ID: 42dc0316-16d5-4f5b-9552-6cc4d2f3e233 Timestamp: 2022-10-10 09:38:51Z

I have also tried verifying the client_id and client_secret being used and that seems to be fine. Moreover, logs on the identity provider side mention that the request was successful.

Awaiting quick responses, as this blocks my application completely.

**Comment by JasSuri** [comment]
This isn’t a bug with any sample here, rather a config issue. You can get troubleshooting help via stackoverflow or open a MS Support ticket.
