### ISSUE TITLE
Is it posible to get the URL from "Register now!"

### ISSUE THREAD

**Issue by WSGomes11** [azure-ad-b2c/samples#47]
Hi!
Every time we arrive at Sigin page, the "Register now" generates a new URL with a token (that expires). I want to move the "Register Now" outside of Sign In page, we want to put the option to Sign Up on App front end,  where the user can click for sign in or for sign up. Is it possible?

**Comment by JasSuri** [comment]
It is possible by splitting the journey into two. One journey for Sign In and another for Sign Up. Or one journey that does combined sign in and up, and one that does sign up only. Just remove the first step of the journey.

**Comment by WSGomes11** [comment]
Interesting! Thank you!
