### ISSUE TITLE
There appears to be an error in the documentation regarding sign-in with conditional access for Azure AD B2C.

### ISSUE THREAD

**Issue by shmiki-microsoft** [azure-ad-b2c/samples#481]
The following statement states that SocialAndLocalAccounts is the base policy.

https://github.com/azure-ad-b2c/samples/tree/master/policies/conditional-access
This sample policy uses the starter-pack [B2C_1A_TrustFrameworkExtensions](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/SocialAndLocalAccounts/TrustFrameworkExtensions.xml) as a base policy.

However, when I upload it, I get an error that "PhoneFactor-InputOrVerify" is missing.

Validation failed: 1 validation error(s) found in policy "B2C_1A_DEMO_TRUSTFRAMEWORKEXTENSIONS_CONDITIONALACCESS" of tenant "b2cshmiki.onmicrosoft.com".The following error occurred in orchestration step 1 in user journey "MFA-ExtraUserVerification" in policy "B2C_1A_Demo_TrustFrameworkExtensions_ConditionalAccess" of tenant "x.onmicrosoft.com": Policy "B2C_1A_Demo_TrustFrameworkExtensions_ConditionalAccess" of tenant "x.onmicrosoft.com" makes a reference to TechnicalProfile with id "PhoneFactor-InputOrVerify" but neither the policy nor any of its base policies contain such an element.The following error occurred in orchestration step 1 in user journey "MFA-ExtraUserVerification" in policy "B2C_1A_Demo_TrustFrameworkExtensions_ConditionalAccess" of tenant "x.onmicrosoft.com": Policy "B2C_1A_Demo_TrustFrameworkExtensions_ConditionalAccess" of tenant "x.onmicrosoft.com" makes a reference to TechnicalProfile with id "PhoneFactor-InputOrVerify" but neither the policy nor any of its base policies contain such an element.

So I changed the base policy to SocialAndLocalAccountsWithMfa and that resolved the error.
https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/main/SocialAndLocalAccountsWithMfa

I would suggest the following modification.
https://github.com/azure-ad-b2c/samples/tree/master/policies/conditional-access
This sample policy uses the starter-pack [B2C_1A_TrustFrameworkExtensions](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/SocialAndLocalAccountsWithMfa/TrustFrameworkExtensions.xml) as a base policy.

**Comment by JasSuri** [comment]
Ive updated the sample to point to social+local+mfa starter pack
