### ISSUE TITLE
Issue at Setup

### ISSUE THREAD

**Issue by SilviuMihai** [azure-ad-b2c/samples#487]
Hello,

I am using the following sample of code from Microsoft Identity Platform [2-call-api-b2c](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c), but with the [custom policy](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy) starter pack from custom policy.
For the custom policy starter pack I used Local Accounts.
This was recommended from [B2CIEF Setup](https://b2ciefsetupapp.azurewebsites.net/).
Also when I am trying to use [change-sign-in-name](https://b2ciefsetupapp.azurewebsites.net/Home/Experimental?sampleFolderName=change-sign-in-name), same issue I am encountering.

So for what I encountered I add the b2c domain name, and than redirects me to sign in with my email address and than I will encounter the issue bellow.
I am receiving the following error by using the Begin Setup that was recommended and I cannot understand where it is the issue:
This b2ciefsetupapp.azurewebsites.net page can’t be found
No webpage was found for the web address: https://b2ciefsetupapp.azurewebsites.net/Error?msg=QUFEU1RTNTAwMjAyOiBVc2VyIGFjY291bnQgJ3tFbWFpbEhpZGRlbn0nIGZyb20gZXh0ZXJuYWwgaWRlbnRpdHkgcHJvdmlkZXIgJ2xpdmUuY29tJyBpcyBub3Qgc3VwcG9ydGVkIGZvciBBUEkgdmVyc2lvbiAnMi4wJy4gTWljcm9zb2Z0IGFjY291bnQgcGFzcy10aHJ1IHVzZXJzIGFuZCBndWVzdHMgYXJlIG5vdCBzdXBwb3J0ZWQgYnkgdGhlIHRlbmFudC1pbmRlcGVuZGVudCBlbmRwb2ludC4NClRyYWNlIElEOiAyYjc3MmUyNC1hYzViLTQwMGMtOTEwZi03OTczZGZhMjI0MDINCkNvcnJlbGF0aW9uIElEOiAxODg4YzVhYi01MWJkLTRkOGYtYmJmNy1jYzg2MjNhMzczMGUNClRpbWVzdGFtcDogMjAyMi0xMS0yOSAwODo0NDo0NFo
HTTP ERROR 404

What to check ? Where I could possibly set something wrong ?
Information Question: Could I use User Flow with a custom policy like [change-sign-in-name](https://b2ciefsetupapp.azurewebsites.net/Home/Experimental?sampleFolderName=change-sign-in-name)
And is a must to add the custom starter pack ?

**Comment by JasSuri** [comment]
I did manage to quick deploy the `change-signin-name` sample to my tenant. Can you try using a user account that is a cloud account from the tenant (@your-tenant.onmicrosoft.com)?

**Comment by JasSuri** [comment]
Try the following:
1. Go to the zzure portal, and select your B2C directory
2. Create a new user, user@tenantname.onmicrosoft.com
3. Make the new user a Global Admin
4. Try the setup tool again, when asked to login, use your newly created account user@tenantname.onmicrosoft.com

**Comment by SilviuMihai** [comment]
Yes, thank you @JasSuri, now I am seeing the xml files in the Identity Experience Framework and I can manipulate the data of the b2c tenant using the user that was created in the b2c tenant and set it as a Global Administrator. I don't understand very clearly, why it must be a user that implements the policies, but if this is how it works, ok.
I think they should rephrase that Usage part on the [B2CIEF SETUP PAGE](https://b2ciefsetupapp.azurewebsites.net/)

Now I'm struggling to see how to test it and to add it to my spa page....

**Comment by SilviuMihai** [comment]
Hello @JasSuri, just how you manage to explain it, to me, it was good. You manage to break it, into pieces, so it was much easier to understand. Thank you.
