### ISSUE TITLE
Embedded-password-reset flow does not return 'name', 'given_name' and 'family_name' during sign-In

### ISSUE THREAD

**Issue by nikhilrpatil-dev** [azure-ad-b2c/samples#489]
I'm using embedded-password-reset flow for SignIn-Signup along with password reset. The sign up does return proper token having 'name', 'given_name' and 'family_name'. But we I go for sign-in, it removes these 3 properties from the token. This is the token I get after sign-in:
![image](https://user-images.githubusercontent.com/43953906/207222939-ca8d6357-341b-438f-9b23-adaa10192e0c.png)

Here I've done some changes in the redefined flow to remove 'Social account' from the flow. From the file [TrustFrameworkExtensions_SSPR.xml](https://github.com/azure-ad-b2c/samples/blob/master/policies/embedded-password-reset/policy/TrustFrameworkExtensions_SSPR.xml) I've removed OrchestrationStep Order="4", OrchestrationStep Order="5", OrchestrationStep Order="6" and OrchestrationStep Order="7". The total steps are now trimmed down to 4 steps (First 3 original OrchestrationSteps and OrchestrationStep 8 'SendClaims' renamed as Step 4). 

This works perfectly fine for Sign-In, Sign-Up and password-reset; but only Sign-Up returns proper token with all properties in it.

**Comment by JasSuri** [comment]
You have to make sure the claims you want to be issued in the token are obtained during the journey (eg by reading the user profile), and then those claim names are issued in the relying party section. Without both of these things, the claims wont get issued into the token.

**Comment by nrpatil1993** [comment]
@JasSuri 
Thanks, that solved the issue. I added this missing UserJourney
`<OrchestrationStep Order="4" Type="ClaimsExchange">
        <ClaimsExchanges>
          <ClaimsExchange Id="AADUserReadWithObjectId" TechnicalProfileReferenceId="AAD-UserReadUsingObjectId" />
        </ClaimsExchanges>
      </OrchestrationStep>`
