### ISSUE TITLE
Custom policy, SignUpInvitation.xml, throwing `Object reference not set to an instance of an object` error

### ISSUE THREAD

**Issue by ryancole** [azure-ad-b2c/samples#49]
Greetings,

I'm trying to get the sample project, from this repo at the following URL, to work ...

https://github.com/azure-ad-b2c/samples/tree/master/policies/invite

The sample project includes a custom B2C policy, `SignUpInvitation.xml`, and a web project. It's my basic understanding that the included custom policy essentially requires a signed token in order to access the policy. The sample basically uses this as an "invitation" step to restrict access to the sign up policy. This is what I am after and so I do believe this sample is pointing me in the right direction. I'm just trying to get it to work, now.

My issue is that, after configuring what I believe to be all the required settings, I am getting an error from within the B2C policy - I think. So, I'll first walk through the steps of how I produce the error ...

## producing the error

I run the provided web project and put in my email and then click invite. I receive the invitation email, which contains the link to the custom B2C policy - `SignUpInvitation.xml`. I click the link and am taken to the policy, but am given a page that says that an exception has occurred - "AADB2C: An exception has occurred."

Unable to find any additional debug info, we added our Application Insights configuration to the custom policy so that it logs output to App Insights. Now, within AI, I can see that the policy is producing the following error ...

```
  {
    ""Kind"": ""Action"",
    ""Content"": ""Web.TPEngine.StateMachineHandlers.GetRelyingPartyInputClaimsHandler""
  },
  {
    ""Kind"": ""FatalException"",
    ""Content"": {
      ""Time"": ""7:05 PM"",
      ""Exception"": {
        ""Kind"": ""Handled"",
        ""HResult"": ""80004003"",
        ""Message"": ""Object reference not set to an instance of an object."",
        ""Data"": {}
      }
    }
  }
```

So, there is a clear error, but still the message is a bit vague. **And this is where I'm stuck.** I'm unsure how to further debug this and pinpoint what is causing the reference error.

## things I looked into

I have spent several days debugging this, and so through that course of debugging I've looked at basically every little bit of info that I could find regarding this. I'm just not well versed in the B2C policy XML scripts, and that seems to be a very deep and technical topic. It's a topic I am interested in learning, but just need some help on how to debug the scripts, etc.

One thing I did notice is that the `Action` in the above error mentions that it's getting the input claims. So, it looks to me like perhaps there is an issue in the policy, or my configuration, in getting the claims. So, I went up the "stack trace", in App Insights, for the above message and found the following action and result ...

```
  {
    ""Kind"": ""Predicate"",
    ""Content"": ""Web.TPEngine.StateMachineHandlers.InitiatingMessageValidationHandler""
  },
  {
    ""Kind"": ""HandlerResult"",
    ""Content"": {
      ""Result"": false,
      ""RecorderRecord"": {
        ""Values"": [
          {
            ""Key"": ""Validation"",
            ""Value"": {
              ""Values"": [
                {
                  ""Key"": ""SubmittedBy"",
                  ""Value"": ""Application""
                },
                {
                  ""Key"": ""ProtocolProviderType"",
                  ""Value"": ""OpenIdConnectProtocolProvider""
                }
              ]
            }
          }
        ]
      },
      ""Statebag"": {
        ""MSG(e4c7c6a9-8023-4cf7-9a34-c920e8325284)"": {
          ""c"": ""2020-03-20T19:05:48.1325292Z"",
          ""k"": ""MSG(e4c7c6a9-8023-4cf7-9a34-c920e8325284)"",
          ""v"": ""{\""TenantId\"":\""wibradixdev.onmicrosoft.com\"",\""PolicyId\"":\""B2C_1A_signup_invitation\"",\""RedirectUri\"":\""https://jwt.ms/\"",\""AdditionalParameters\"":{\""TEST\"":\""TEST\"",\""p\"":\""B2C_1A_signup_invitation\""},\""Nonce\"":\""0eefd73e94224dc69d8766dd219180e6\"",\""ClientId\"":\""30639331-3c2c-4ade-8c36-814dfe007170\"",\""ResponseType\"":\""id_token\"",\""ResponseRedirector\"":{\""URI\"":\""https://jwt.ms\"",\""D\"":false,\""WF\"":true},\""Scope\"":\""openid\"",\""AppModelVersion\"":1,\""ScopedProviders\"":[]}"",
          ""p"": true,
          ""t"": ""OAuth2""
        },
        ""CMESSAGE"": {
          ""c"": ""2020-03-20T19:05:48.1325292Z"",
          ""k"": ""CMESSAGE"",
          ""v"": ""e4c7c6a9-8023-4cf7-9a34-c920e8325284"",
          ""p"": true
        },
        ""IMESSAGE"": {
          ""c"": ""2020-03-20T19:05:48.1325292Z"",
          ""k"": ""IMESSAGE"",
          ""v"": ""e4c7c6a9-8023-4cf7-9a34-c920e8325284"",
          ""p"": true
        },
        ""ComplexItems"": ""_MachineEventQ, TCTX, ORCH_IDX, REPRM, IC""
      },
      ""PredicateResult"": ""True""
    }
  }
```

This action seems to be doing some type of validation, but I noticed that the result returns `false`, which usually means some sort of failure? I'm unsure in this case.

## how do I proceed ?

Can you please help me out or point me in the right direction on how to figure this out? I deployed the sample web project to Azure, and you can access that [here](https://wibauthtest.azurewebsites.net) if you'd like to see what I'm seeing. If you have access to App Insights, you might be able to access my logs using the below information. The error in question occurred on `3/24/2020, 3:45:28.039 PM`, with ikey and itemid `5d95a95b-6887-4798-a984-98a0a9d32d53` `8a3a3e80-6de6-11ea-a0a3-ab73ec95556d`.

App Insights Subscription Id: 265b7109-497d-42bc-8a20-fa6399a96a9c
App Insights Instrumentation Key: 5d95a95b-6887-4798-a984-98a0a9d32d53

Also, I attached the error message output here just in case you cannot see them in App Insights.

[error_message.txt](https://github.com/azure-ad-b2c/samples/files/4376403/error_message.txt)

Thank you!

**Comment by JasSuri** [comment]
We are looking into this with your support ticket.

**Comment by ryancole** [comment]
@JasSuri Apologies. I now know what you were referring to regarding technical profile. Here is the technical profile section from the policy XML, with our included config adustments ...

```xml
    <ClaimsProvider>
      <DisplayName>My ID Token Hint ClaimsProvider</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="IdTokenHint_ExtractClaims">
          <DisplayName> My ID Token Hint TechnicalProfile</DisplayName>
          <Protocol Name="None" />
          <Metadata>
          
            <!--Sample action required: replace with your endpoint location -->
            <Item Key="METADATA">https://wibradixdev.b2clogin.com/wibradixdev.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_signup_invitation</Item>

 

            <!-- <Item Key="IdTokenAudience">your_optional_audience_override</Item> -->
            <!-- <Item Key="issuer">your_optional_token_issuer_override</Item> -->
          </Metadata>
          <OutputClaims>
            <!--Sample: Read the email cliam from the id_token_hint-->
            <OutputClaim ClaimTypeReferenceId="email" />  
          </OutputClaims>
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
  </ClaimsProviders>
```

We tried setting that metadata URL to both our deployed ASP project (from the sample project, and I linked to it in the original issue post) and the value that's currently pasted here which is the discovery link from the B2C endpoint.

**Comment by JasSuri** [comment]
The discovery endpoint for this technical profile should be your id token hint service, not the Azure AD B2C Policy well-known OIDC config.

**Comment by ryancole** [comment]
That endpoint should be here: https://wibauthtest.azurewebsites.net/.well-known/openid-configuration

I'll reconfigure B2C policy to use that endpoint.

**Comment by ryancole** [comment]
@JasSuri Thank you so much. That indeed was where the issue was. I could swear I tried that last week and it did not work, but I must have done it incorrectly. I just changed the metadata URL back to the well-known URL of the provided ASP project and it's all working as intended now. Thank you again.

**Comment by Brandon-Benedict** [comment]
Hi I am also running into errors with this project even after I have published my endpoint: https://aadb2cinvite20200409031258.azurewebsites.net/.well-known/openid-configuration

I am getting "An error occurred while processing your request."
Request ID: 8000012e-0000-f200-b63f-84710c7967bb

Been trying to figure out the issues for a couple days with no luck. Can you help?

**Comment by ryancole** [comment]
@Brandon-Benedict I recommend hooking your policy up to application insights. In AI, you will see a full error stack trace, basically. It's mostly impossible to debug without doing that, as far as I can tell.

**Comment by JasSuri** [comment]
@Brandon-Benedict your actual endpoint is misconfigured here (web app), so connecting the B2C policy to App Insights won’t help. I suggest opening a stackoverflow thread as there isn’t an issue with the sample itself.

**Comment by ivarsst** [comment]
> Hi I am also running into errors with this project even after I have published my endpoint: https://aadb2cinvite20200409031258.azurewebsites.net/.well-known/openid-configuration
> 
> I am getting "An error occurred while processing your request."
> Request ID: 8000012e-0000-f200-b63f-84710c7967bb
> 
> Been trying to figure out the issues for a couple days with no luck. Can you help?


Hi! Your endpoint is configured to use Release configuration, as it says:
> Swapping to Development environment will display more detailed information about the error that occurred.


 Try to swap it to Development mode and you could see more detailed information about the error.
