### ISSUE TITLE
Read client application properties from B2C custom policy running in the same tenant

### ISSUE THREAD

**Issue by svirchenko** [azure-ad-b2c/samples#492]
Hi,

I'd like to read client application properties (for example, directory extensions on application objects) from B2C custom policy running in the same tenant.

On the screenshot you can find an example of a client application manifest with extension properties which are desired to be obtained in B2C custom policy.

![image](https://user-images.githubusercontent.com/113915129/208150599-954cb73f-85f0-466a-b9c6-3f712b186bcd.png)

According to the documentation Azure Active Directory B2C (Azure AD B2C) provides support for the Azure Active Directory user management in custom policy (https://learn.microsoft.com/en-us/azure/active-directory-b2c/active-directory-technical-profile).  There are some predefined technical profiles only  related to users (not for applications):

![image](https://user-images.githubusercontent.com/113915129/208877407-29237006-c3dc-408f-8968-38cabecbfe34.png)

Unfortunately, I did not find a way in official documentations to get application properties from custom policy. It'd be nice to hear any feedback whether it's possible or not. Thanks in advance

**Comment by JasSuri** [comment]
It’s not possible. You could call your own api to fetch it.
