### ISSUE TITLE
Invite link sample and replacing the certificate

### ISSUE THREAD

**Issue by timduncan-innowell** [azure-ad-b2c/samples#516]
We have used the https://github.com/azure-ad-b2c/samples/tree/master/policies/invite sample as the basis for sending out invitation links to our users and it has been working well for almost 2 years.

Having followed the demo closely in our implementation we used the 2 year expiry date of the self-signed certificate as shown in the readme:
```
$cert = New-SelfSignedCertificate -Type Custom -Subject "CN=MySelfSignedCertificate" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3") -KeyUsage DigitalSignature -KeyAlgorithm RSA -KeyLength 2048 -NotAfter (Get-Date).AddYears(2) -CertStoreLocation "Cert:\CurrentUser\My"
$cert.Thumbprint
```
Now that it is close to the 2 year expiry, we realise that the certificate needs to be replaced. We also just realised that all previous links sent out before the replacement will immediately become invalid and there doesn't seem to be a way to avoid it.

Is there any recommendation on the correct process to replace the certificate, ideally without invalidating all previous invites?

**Comment by JasSuri** [comment]
If you created the cert yourself, then you should be able to renew it without changing the public key. Depending on how you did that. This question is better on stackoverflow.
