### ISSUE TITLE
Avoid verification code emails when the user is not registered

### ISSUE THREAD

**Issue by rohitchouhan08** [azure-ad-b2c/samples#52]
Azure B2C is gives a false impression that the user is in the directory when they try to reset their password.

Following is steps in reset password:
1) User clicks the Reset Password link
2) B2C presents a page with “Email Address” field and says “Verification is necessary. Please click Send button.”
3) User enters his email address and clicks “Send Verification Code”
4) B2C sends the verification code this that email address (Even if no user is associated with that email address. This is where the user thinks he is registered with the system)
5) Now the user enters the verification code he received and click “Verify Code”
6) B2C validated the code and says “E-mail address verified. You can now continue” (This is the step where they become confident that they exist in the system)
7) Now when the users click “Continue” they get the error “An account could not be found for the provided user ID.” As given in the screenshot.

Confirming an email that is not associated with a user completely confuses them. 

i found  [this](https://github.com/azure-ad-b2c/samples/tree/master/policies/pwd-reset-email-exists) but not getting exactly how to use these policy along with [this](https://github.com/azure-ad-b2c/samples/tree/master/policies/passwordless-email) .

**Comment by JasSuri** [comment]
This used the old method for email verification. The new methods use displayControls giving more control. See this sample to only send the code to a user that exists. It doesn’t throw an error if the email doesn’t exist, to prevent fishing for accounts. But you can enable the error if you like.
https://github.com/azure-ad-b2c/samples/tree/master/policies/pwd-reset-email-exists

**Comment by rohitchouhan08** [comment]
@JasSuri i am not able to add this solution to my [current policy](https://github.com/azure-ad-b2c/samples/tree/master/policies/passwordless-email).

**Comment by JasSuri** [comment]
Since this is not an issue, you might better seek assistance on StackOverflow.
