### ISSUE TITLE
Can we specify multiple values for SendClaimsIn for REST API?

### ISSUE THREAD

**Issue by svirchenko** [azure-ad-b2c/samples#521]
Hi. I am implementing [REST API call from B2C custom policy](https://learn.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile) and faced some issues with **SendClaimsIn** attribute.

The REST API requires the following inputs:

1. Custom headers ([Header](https://learn.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile#metadata)) - _CustomHeader1/CustomHeader2_
2. URL parameters ([URL](https://learn.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile#metadata))  - _claim1/claim2_

```
GET /api/test/{claim1}/{claim1}
CustomHeader1 : Value1
CustomHeader2 : Value2

Response
{
   "prop1" : "value1",
   "prop2" : "value2"
}
```

Is it possible to specify headers and URL parameters at the same time for REST API?

Thanks in advance

**Comment by JasSuri** [comment]
It’s not possible.
