### ISSUE TITLE
sample "revoke-sso-sessions" cannot upload

### ISSUE THREAD

**Issue by shmiki-microsoft** [azure-ad-b2c/samples#524]
Target policy:
https://github.com/azure-ad-b2c/samples/tree/master/policies/revoke-sso-sessions

Error Message:
Validation failed: 1 validation error(s) found in policy "B2C_1A_TRUSTFRAMEWORKEXTENSIONS_REVOKE_SESSION" of tenant "x.onmicrosoft.com".Policy "B2C_1A_TRUSTFRAMEWORKEXTENSIONS_REVOKE_SESSION" of tenant "x.onmicrosoft.com" makes a reference to ClaimType with id "refreshTokensValidFromDateTime" but neither the policy nor any of its base policies contain such an element.Policy "B2C_1A_TrustFrameworkExtensions" of tenant "x.onmicrosoft.com" makes a reference to ClaimType with id "refreshTokensValidFromDateTime" but neither the policy nor any of its base policies contain such an element.

Same Issue:
https://github.com/azure-ad-b2c/samples/issues/515

Reason:
Conflicting refreshTokensValidFromDateTime definitions.
https://github.com/azure-ad-b2c/samples/blob/master/policies/revoke-sso-sessions/policy/TrustframeworkExtensions_RevokeSessions.xml#L29

https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/main/SocialAndLocalAccounts/TrustFrameworkBase.xml#L254

Suggestion:
I am wondering if I should rename the ID of the following claim.
https://github.com/azure-ad-b2c/samples/blob/master/policies/revoke-sso-sessions/policy/TrustframeworkExtensions_RevokeSessions.xml#L29

**Comment by alin-devnet** [comment]
Any update on this? It seems like I can't get the revoke sso session user journey to work with the latest starter pack base policy because of data type differences for refreshTokensValidFromDateTime (RedeemRefreshToken user journey expects this to be a string, whilst for the revoke sso session it's dateTime).

**Comment by JasSuri** [comment]
https://github.com/azure-ad-b2c/samples/pull/548
