### ISSUE TITLE
ClaimType "userId" missing Error on username-signup-or-signin

### ISSUE THREAD

**Issue by nacient** [azure-ad-b2c/samples#53]
Hi, following the instructions at [https://github.com/azure-ad-b2c/samples/tree/master/policies/username-signup-or-signin], I get an error when uploading the Username_TrustFrameworkExtensions.xml

_Validation failed: 1 validation error(s) found in policy "B2C_1A_USERNAME_TRUSTFRAMEWORKEXTENSIONS" of tenant "tenantname.onmicrosoft.com".Policy "B2C_1A_Username_TrustFrameworkExtensions" of tenant "tenantname.onmicrosoft.com" makes a reference to ClaimType with id "userId" but neither the policy nor any of its base policies contain such an element._

**Comment by JasSuri** [comment]
Thanks, ive updated instances of `userid` to `signInName`.
