### ISSUE TITLE
Azure ADB2C - Email MFA showing additional success page

### ISSUE THREAD

**Issue by apillai-incomm** [azure-ad-b2c/samples#537]
Am following the tutorial listed in below URL to enable EMAIL MFA

https://github.com/azure-ad-b2c/samples/tree/master/policies/signin-email-verification

Everything works correctly, except it shows an additional page on Verification success
<img width="686" alt="Screenshot 2023-05-05 at 10 37 59 PM" src="https://user-images.githubusercontent.com/30837658/236594490-6d9769ba-5688-495d-98da-3dabfacc5c4b.png">

This is an extra page that comes after I enter the Verification Code -> Click Verify -> click Continue and then again this page. Need to know how to disable this page. Any help is appreciated.

**Comment by JasSuri** [comment]
This is not an extra page, just an extra step within the same page. You can “disable” it by automating the clicks with JavaScript.

**Comment by guptah17** [comment]
@JasSuri Can you please elaborate on how exactly to automate the click on 'Continue' button with JavaScript? I tried making it work using custom html with JS code in place of selfAsserted.html, but the code is not able to identify 'Continue' button specifically for this step. A working sample code would be helpful.

Also is there an alternate way to achieve this using an Orchestration step? 

Thanks,
Himanshu
