### ISSUE TITLE
Invitation Sample - Can't upload self signed certificate to B2C policy key container

### ISSUE THREAD

**Issue by mehdiibrahim** [azure-ad-b2c/samples#54]
Hello, 

I followed the instructions to use a self signed certificate and created one using powershell. In B2C I then created a policy key container (type RSA, usage Signature). But when I upload the PFX from my self signed certificate, I get this error: "The key 'B2C_1A_CustomTokenSigningKeyContainer' has failed to be created. The uploaded key is badly formatted. Reason: 'The key container has a different use than the new added key'."  

Has anybody successfully followed the instructions for this sample? Any clues?

Thanks!

**Comment by JasSuri** [comment]
Can you add this flag to the command `-KeyUsageProperty Sign`
