### ISSUE TITLE
These examples are old and out of date

### ISSUE THREAD

**Issue by mwwhited** [azure-ad-b2c/samples#55]
These examples need updated.  You dont even support the framework versions many of them are written for such as the invite flow being setup for dotnet core 2.2.

The related notes are also all out of date which make trying to follow these examples very difficult.

**Comment by JasSuri** [comment]
The primary objective of this repo is to provide sample policies. We will consider updating, or removing all API samples and replacing with the interface/logical requirement instead. 

Is there an issue being faced running a .Net Core 2.2 sample to **demonstrate** the end to end functionality?

Are you referring to the “related notes” to the policy files or the .Net API samples?

**Comment by mwwhited** [comment]
So many of your APIs have moved around to different assemblies or just generally jacked up by things like the trying to kill off JSON.Net kick your guys are on that want attempt to understand and update these examples on our own is a pain in the rear. 

You are deprecating your own products and projects all the while not showing people have to use the current stuff with the new recommendations.

**Comment by JasSuri** [comment]
All of these samples work with **any** programming language you like. As long as your API can handle JSON it will work. Only for completeness we modeled them as an example alongisde the policies. For demonstration purposes all the .Net Core 2.2 APIs do compile, if not, feel free to open this issue back up with a specific example for us to look into.

**Comment by JasSuri** [comment]
We will document the JSON payloads and API interfaces into existing samples, and moving forwards with any new samples - appreciate this point. We will leave the old API samples in tact, since it still proves useful to just get up and running.
