### ISSUE TITLE
Encrypt/decrypt passwords in Azure B2C with external system

### ISSUE THREAD

**Issue by cyrilmatthew26** [azure-ad-b2c/samples#558]
After successfully completing a password reset in Azure B2C using custom policies, I need to update an external identity platform which also has the user, with the same password that the user has entered. We're using an self managed REST API which will send the email and newPassword in the request and update it in the other platform. 
Is there a way we can encrypt the password before sending it in the body in Azure B2C REST technical profile and then API can later decrypt it before updating the password in the other platform?

I was hoping to use the hashing mechanism available in B2C. But is it possible for the API to retrieve the password in plaintext with the hash it receives in the request provided that the API also has the salt and private key used in Azure B2C?
https://learn.microsoft.com/en-us/azure/active-directory-b2c/general-transformations#hash

Or is there a better solution to handle this?

**Comment by jasjeetsuri** [comment]
> Is there a way we can encrypt the password before sending it in the body in Azure B2C REST technical profile and then API can later decrypt it before updating the password in the other platform?

The identity experience framework does not have any native capability to encrypt claims, only hash. You could hash it and then always hash incoming passwords with the same algo to match.

https://learn.microsoft.com/en-us/azure/active-directory-b2c/general-transformations#hash

**Comment by cyrilmatthew26** [comment]
Can we take it one step further to get the password in plaintext from the incoming hash using our own API ?
