### ISSUE TITLE
AAD-UserReadXXX Still Using https://graph.windows.net

### ISSUE THREAD

**Issue by tripflex** [azure-ad-b2c/samples#567]
Microsoft has deprecated (and will be removing) https://graph.windows.net/ but for some reason, behind the scenes why is this being using this for custom policies.  

I believe my issue stems from the fact that you do not allow you to add permissions anymore to applications for “Azure Active Directory Graph” and force to use “Microsoft Graph”
 
When debugging the custom policy through application insights, I see that when the handling for `AAD-UserReadUsingAlternativeSecurityId` is used, you are still calling the “Azure Active Directory Graph”:

```
      "Statebag": {
        "PROT": {
          "c": "2023-08-23T21:51:56.8371587Z",
          "k": "PROT",
          "v": "AAD Request to https://graph.windows.net/xxx/users?api-version=1.6-integrationOnly&%24filter=alternativeSecurityIds%2fany(x%3ax%2ftype+eq+6+and+x%2fidentityProvider+eq+%27xxxx) using method GET as request body is malformed.\r\nResponse: \n{\"odata.metadata\":\https://graph.windows.net/xxx/$metadata#directoryObjects\,\"value\":[]}\r\n",
          "p": false
        }
      }
```

Why is this happening, and why has Microsoft not updated this to use "Microsoft Graph" calls.  The only applications i'm able to get to work correctly with this handling, are ones that had permissions set for "Azure Active Directory Graph" already ...................

**Comment by JasSuri** [comment]
Because MS graph api internally calls AAD Graph. This is an internal version of the underlying API being called by our platform. This is not an issue and is by design. It is not something that customers need to worry about.
