### ISSUE TITLE
Is there an example of progressive profiling?

### ISSUE THREAD

**Issue by danijam** [azure-ad-b2c/samples#57]
I'm struggling to find out how to Implement progressive profiling as demonstrated in this video: https://youtu.be/GmBKlXED9Ug?t=433

I want to collect additional input from the user on subsequent logins. I'm looking for where to start, documentation or examples. I've struggled so far to find anything

**Comment by JasSuri** [comment]
Progressive profiling sample:
https://github.com/azure-ad-b2c/samples/tree/master/policies/progressive-profile
