### ISSUE TITLE
ClientId and ApplicationObjectId is required for Technical Profile.

### ISSUE THREAD

**Issue by akkaneko-ms** [azure-ad-b2c/samples#570]
I confirmed SignUpOrSignin_PhoneOrEmailMFA.xml custom policy, It doen't work on my lab without ClientId and ApplicationObjectId in Metadata for some Technical Profile.
-AAD-UserWriteMFAMethod
-AAD-UserWritePhoneNumberUsingObjectId
-AAD-UserReadUsingObjectId
I added these attribute, then custom policy worked correctly.

          <Metadata>
            <Item Key="ClientId">APPLICATION_CLIENTID</Item>
            <Item Key="ApplicationObjectId">APPLICATION_OBJECTID</Item>
          </Metadata>

**Comment by JasSuri** [comment]
It’s required to support extension attributes. See the main readme.
