### ISSUE TITLE
Change button after verification

### ISSUE THREAD

**Issue by spottedmahn** [azure-ad-b2c/samples#581]
reference: [policies/pwd-reset-via-email-or-phone](https://github.com/azure-ad-b2c/samples/tree/master/policies/pwd-reset-via-email-or-phone)

Why is there a change button after the user performs the verification? 🤔

![image](https://github.com/azure-ad-b2c/samples/assets/14079228/0194062d-1062-4b15-953f-784c3fef17ff)

It would seem the change button would make sense here (after sending a code but I haven't entered it yet):

![image](https://github.com/azure-ad-b2c/samples/assets/14079228/169c5038-5da5-4f43-a411-0daeff49f4bb)

In that situation, I could see that:
1. I request a code
2. I don't receive my code
3. I decide I'll try the other option hence the need for the change button

**Working upload of referenced policies:**
- [Sign-in/up policy](https://spottedmahnb2c.b2clogin.com/spottedmahnb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_DEMO_SIGNUP_SIGNIN_PASSWORDRESET_EMAILORPHONE&client_id=d39bf8bf-dc0a-47c6-8c55-fb0aada53d23&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login)
- [Password reset policy](https://spottedmahnb2c.b2clogin.com/spottedmahnb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_DEMO_PASSWORDRESET_EMAILORPHONE&client_id=d39bf8bf-dc0a-47c6-8c55-fb0aada53d23&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login)

**Comment by JasSuri** [comment]
To verify a different phone number, if required. And that will replace the old number. This is default ui of a displayControl. And you can always hide these UI elements using CSS/JS if you don’t need the functionality.
