### ISSUE TITLE
getting Claim not verified: [Email Address] error

### ISSUE THREAD

**Issue by sergey-malue** [azure-ad-b2c/samples#591]
I have policy with multiple orchestration steps.
On verification email step when i click continue before sending email verification code or sent it but left verification code empty it shows me "Claim not verified: [Email Address]" error, but it aslo shows correct messages like 'Verification is necessary. Please click Send button.", "That code is incorrect. Please try again.", so i want to get rid of "Claim not verified: [Email Address]" but i did not find any ErrorMessage key which is resposible for it.
Please advise solution for this case.

**Comment by codeshinobi** [comment]
Hi @sergey-malue. How did you resolve this? I followed the following https://learn.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy and now I can get to the forgot password user journey. However, now I get this when I try to reset the password.
