### ISSUE TITLE
missing files on the example relying-party-rbac

### ISSUE THREAD

**Issue by glomaga** [azure-ad-b2c/samples#60]
The example is not complete.
The folder wwwroot is missing, the example is not working.
Please upload it.
![image](https://user-images.githubusercontent.com/27291517/80267836-c058fe80-8668-11ea-99af-16098329e40b.png)
![image](https://user-images.githubusercontent.com/27291517/80267839-cf3fb100-8668-11ea-8c74-c077d57c4d2b.png)

**Comment by JasSuri** [comment]
Sample builds and runs without this folder. It is only serves as an API, and doesnt need to present any HTML at runtime.
