### ISSUE TITLE
Example is not working link-local-account-with-federated-account

### ISSUE THREAD

**Issue by glomaga** [azure-ad-b2c/samples#61]
Hi, 
The example is not working. Please fix it.
- missing TechnicalProfile Id="Facebook-OAUTH" on the TrustFrameworkBase.xml.
- error on the line OutputClaim ClaimTypeReferenceId="newUser" DefaultValue="true" on the  TechnicalProfile Id="AAD-MergeAccount" on the the TrustFrameworkExtensions.xml

There is also not enough documentation of the steps and changes to be made in the files for the example to work. please document it further.

Thanks

**Comment by JasSuri** [comment]
This sample and account linkage sample will be revamped, standby.

**Comment by JasSuri** [comment]
Sample has been updated, please check it out.

**Comment by glomaga** [comment]
Thanks :)
