### ISSUE TITLE
Policy: pwd-reset-email-exists - How to Localize the "emailVerificationControl_error_message"

### ISSUE THREAD

**Issue by henriquebelotto** [azure-ad-b2c/samples#64]
Hello,

I'm using this example to write my own policy and everything is working fine.
In my custom policy I have French and English and was able to translate every message that is displayed to the user but this message "The verification has failed, please try again.", which is shown if the user enters an incorrect Verification Code (Id="emailVerificationControl_error_message")

![verification_message](https://user-images.githubusercontent.com/38217514/80820305-a2c5f080-8ba4-11ea-91df-637f1f542e18.png)

I was able to translate the other messages, but I couldn't find out how to translate this specific message. I followed this documentation (Localization string IDs)[https://docs.microsoft.com/en-ca/azure/active-directory-b2c/localization-string-ids] but still wasn't able to figure out how do to that.

Can you help me?

Thank you

**Comment by JasSuri** [comment]
I think we need to add this to our doc, let me know if that works.
```xml
<LocalizedResources Id="selfasserted.en">
    <LocalizedStrings>
        <LocalizedString ElementType="ErrorMessage" StringId="UserMessageIfVerificationFailedRetryAllowed">That code is incorrect. Please try again.                                
   </LocalizedString>
    </LocalizedStrings>
  </LocalizedResources>
```

Let me know if that works.

**Comment by henriquebelotto** [comment]
@JasSuri Hello!
Thank you very much!
It worked perfectly, although I added it to the api.localaccountpasswordreset session.

How did you find this stringId "UserMessageIfVerificationFailedRetryAllowed"?

Thank you

**Comment by JasSuri** [comment]
We work in this product team :) 
Will get it added to the docs.
