### ISSUE TITLE
Example on how to use AdditionalRequestQueryParameters on OAuth2 provider

### ISSUE THREAD

**Issue by 0Dmitry** [azure-ad-b2c/samples#640]
I am trying to use `AdditionalRequestQueryParameters` metadata item to force google to show account selection page instead of using the currently logged in account if there is only one to use. I tried this config (not working):

    <ClaimsProvider>
      <Domain>google.com</Domain>
      <DisplayName>Google</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="Google-OAuth2">
          <DisplayName>Google</DisplayName>
          <Protocol Name="OAuth2"/>
          <Metadata>
            <Item Key="ProviderName">google</Item>
            <Item Key="authorization_endpoint">https://accounts.google.com/o/oauth2/auth</Item>
            <Item Key="AccessTokenEndpoint">https://accounts.google.com/o/oauth2/token</Item>
            <Item Key="ClaimsEndpoint">https://www.googleapis.com/oauth2/v1/userinfo</Item>
            <Item Key="scope">email profile</Item>
            <Item Key="HttpBinding">POST</Item>
            <Item Key="UsePolicyInRedirectUri">false</Item>

            <Item Key="AdditionalRequestQueryParameters">prompt=select_account</Item>

            <Item Key="client_id"><client id>.apps.googleusercontent.com</Item>
          </Metadata>
          
I tried to find a sample usage of that metadata attribute. But it seems there isn't any in the entire GitHub..

Any ideas on how to make it work?

**Comment by jasjeetsuri** [comment]
You could solve this with inputclaim instead.

**Comment by 0Dmitry** [comment]
> You could solve this with inputclaim instead.

Yeah, I was able to pass this prompt param as an input claim like this:

```
<InputClaims>
  <InputClaim ClaimTypeReferenceId="prompt" PartnerClaimType="prompt" DefaultValue="select_account" AlwaysUseDefaultValue="true" />
</InputClaims>
```
