### ISSUE TITLE
Do not allow old passwords - How to?

### ISSUE THREAD

**Issue by henriquebelotto** [azure-ad-b2c/samples#65]
Hello,

I saw that there is one sample that ask for the current password and the new password, so they can check if the new and old (current) are the same. However, how can I block the user to enter his X old passwords, especially without asking for the "Current password"?

Thank you

**Comment by JasSuri** [comment]
AAD and AAD B2C do not maintain a password history. Currently therefore you can only prevent the last password from being used. We don’t recommend using external systems to maintain a password history.
