### ISSUE TITLE
Question about example "B2C IEF Custom Policy - A Sign In policy with Home Realm Discovery"

### ISSUE THREAD

**Issue by glomaga** [azure-ad-b2c/samples#66]
Hi

The flow for this example"home-realm-discovery-modern" :
1) One screen to enter the email:
![image](https://user-images.githubusercontent.com/27291517/81245565-e7092480-8fda-11ea-8ced-3b5aae3bf3b0.png)
2) IF the email domain is not on the list of known external providers, then is a  LocalAccount, we will prompt another screen:
![image](https://user-images.githubusercontent.com/27291517/81245608-01db9900-8fdb-11ea-8b76-0af88a6b5685.png)
3) IF the email domain is ON the list of known external providers, then call the other provider: 
![image](https://user-images.githubusercontent.com/27291517/81245771-7e6e7780-8fdb-11ea-956c-0496bdd24e15.png)

One Question:
**Is it possible to have only one screen for entering the information for the login (username, and password), and from that screen continues the flow either for the login for a local account (login-NonInteractive) or call the other Provider (like AAD or Microsoft)?**
Only one screen like this one:
![image](https://user-images.githubusercontent.com/27291517/81245851-b37aca00-8fdb-11ea-8fc4-0c83448271ca.png)

I tried to implement it,  these are the steps that I followed:

1) This step to get the email and the password from the user ( i am saving the password on plain text on other claim to be able to  use it as OutputClaim)
OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.localaccountsignin">
          ClaimsProviderSelections>
          ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange2" />
          ClaimsProviderSelections>
          ClaimsExchanges>
            ClaimsExchange Id="LocalAccountSigninEmailExchange2" TechnicalProfileReferenceId="SelfAsserted-Signin-Email" 
          </ClaimsExchanges>
        </OrchestrationStep>
2) to be able to pass the claimprividerSelection:
	OrchestrationStep Order="3" Type="ClaimsProviderSelection" ContentDefinitionReferenceId="api.idpselections">
          Preconditions>
            Precondition Type="ClaimEquals" ExecuteActionsIf="false">
              Value>isKnownCustomer</Value>
              Value>False</Value>
              Action>SkipThisOrchestrationStep</Action>
            Precondition>
          Preconditions>
          ClaimsProviderSelections>
            ClaimsProviderSelection TargetClaimsExchangeId="LocalAccountSigninEmailExchange" />
          ClaimsProviderSelections>
        OrchestrationStep>
3) Call login-NonInteractive directly from the OrchestrationStep, passing the password and the email.
     OrchestrationStep Order="4" Type="ClaimsExchange">
          Preconditions>
            Precondition Type="ClaimEquals" ExecuteActionsIf="false">
              Value>isKnownCustomer</Value>
              Value>False</Value>
              Action>SkipThisOrchestrationStep</Action>
            Precondition>
          Preconditions>
          ClaimsExchanges>
            ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="login-NonInteractive" />
          ClaimsExchanges>
        OrchestrationStep>
4)The other steps are exactly the same as the example for the External Provider.

The call for the External provider is working perfectly on my example BUT, if  I try to login with a local account, I have an error on step number 3 (login-NonInteractive)  :  
![image](https://user-images.githubusercontent.com/27291517/81246049-300da880-8fdc-11ea-97d8-c3d329ecac2e.png)

**Comment by JasSuri** [comment]
Wouldn't it be confusing for federated users, because they dont have a password with B2C? And then if they are redirected to the federated IdP, they then have to enter the password again?

**Comment by glomaga** [comment]
Thanks for your answer was very helpful, I found a way to do it from the technical profile on SelfAsserted-Signin-Email: 
 ValidationTechnicalProfile ReferenceId="login-NonInteractive">	
			Preconditions>
			Precondition Type="ClaimEquals" ExecuteActionsIf="true">
				Value>isKnownCustomer</Value>
				Value>True</Value>
				Action>SkipThisValidationTechnicalProfile</Action>
			  Precondition>
			Preconditions>
		  ValidationTechnicalProfile>	
About the enter the password twice para external provider, I am reviewing the possibility to control that on the UI with JS, if the domain for the email is = to the External Provider,  don't enable the password field, and sent to IEF dummy password to be able to continue the flow.
