### ISSUE TITLE
Assumes Windows as runtime OS

### ISSUE THREAD

**Issue by stewartadam** [azure-ad-b2c/samples#69]
Windows should either be a documented requirement for the relevant samples (e.g. invite), or appropriate shell commands for Unix-like OSs should be provided as well.

e.g. for the invite sample, the code casts the certificates in a way that assumes Windows environments: https://stackoverflow.com/a/56979823

The provided commands for generating a certificate are also Windows-based, and the code assumes a Windows credential store.

**Comment by stewartadam** [comment]
Is this out of scope or being fixed?

**Comment by JasSuri** [comment]
Out of scope, the purpose of this repo is to provide custom policy samples, all other supporting material is only provided as an additional benefit to get going.
