### ISSUE TITLE
Custom email verification for Password Reset

### ISSUE THREAD

**Issue by marcelmedina** [azure-ad-b2c/samples#7]
I have tried the sample https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-email-verifcation for reset password without success.

The SelfAsserted.html available fails to load the javascript, but that's a secondary problem that needs a separate issue.

The main issue is that the flow is not complete for PasswordReset. Below I have put the steps that I am trying to achieve with this solution, and where the problem sits:

**First step**
User provides email and click to send verification code, it reaches the API and sends the custom email successfully.

**Second step**
User grabs the code and put it on the B2C page. That gets validated successfully.
As soon as I hit the button to continue I get this error on screen: **Claim not verified: [Email Address]**
![image](https://user-images.githubusercontent.com/17131300/59894686-a1c91c00-9435-11e9-8de6-67904138f67a.png)

**Third step**
Provide new password and confirm new password.
This could not be validated.

**Fourth step**
Success message, and redirect to Login.
This could not be validated.

From what I can see within the schema, only the SignUp has Call to REST API verification, but not the PasswordReset.

Please can I get some guidance on that?

**Comment by WhippsP** [comment]
@marcelmedina  - I will look into this issue. In the meantime have a look at the new [DisplayControls sample](https://github.com/azure-ad-b2c/samples/tree/master/policies/custom-email-verifcation-displaycontrol)

**Comment by JasSuri** [comment]
Deprecating this sample in favor of this: https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-email
