### ISSUE TITLE
Getting error - Hash does not contain state when redirecting to SPA. INVITE SAMPLE

### ISSUE THREAD

**Issue by stephenstroud** [azure-ad-b2c/samples#71]
After successfully registering the user via the invite link the following error occurs when redirecting to SPA. 

```AuthError: Unexpected error in authentication.: Hash does not contain state.```

This occurs in Google Chrome and Firefox 

Further info [here](https://github.com/syncweek-react-aad/react-aad/issues/232)

**Comment by JasSuri** [comment]
Upgrade MSAL, there’s information here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/701.

Better to take the issue to MSAL Library repo.

**Comment by stephenstroud** [comment]
@JasSuri Thanks, I'll try this out.
