### ISSUE TITLE
Is this sample still current ?

### ISSUE THREAD

**Issue by Shaun901** [azure-ad-b2c/samples#73]
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple

I have gone through this sample a dozen times and I cannot get sign in to apple to work....... I'm now wondering if it is no longer current ? Nothing appears to have changed for 12 months

**Comment by rikishon** [comment]
I too have the same question . seems to always auth OK with Apple, however upon redirect back to B2C I see the AADB2C90289 error:

![image](https://user-images.githubusercontent.com/17129761/83463760-110f1300-a4c3-11ea-8ccd-d63b54e0eb41.png)


Not sure if it's an issue, but Apple places the state info in the body, vs the URL like Google does (which works well)?

**Comment by stevenxzhou** [comment]
Hi, May I ask if the above issues you encountered long existed or just pop up most recently?

**Comment by Shaun901** [comment]
I couldn't get it to work at all... I couldn't get it to the point of actually signing in using MSAL.net....just got javascript errors in the sign in pop up......gave up and am now going down what appears to be an endless rabbit hole that is Custom Policies..... which of course has meant that I pretty much have to start from scratch with everything, after 2 days doing little else I finally have the basic user flow working...I've not attempted sign in with apple yet......

**Comment by muak** [comment]
I have a problem too.
I confirmed appearing the Apple Sign-in page and can sign in.
But after that, the redirect is not working, it just displays a white blank page.
Is there any hint?
