### ISSUE TITLE
Article about features that are deprecated or recommended in policies? 

### ISSUE THREAD

**Issue by b3nt0** [azure-ad-b2c/samples#74]
I've noticed that the schema for B2C supports some things that aren't used in any of the samples. It looks like none of the examples use user journey's that contain sub-journeys or input validations instead of predicate validations. There are places where the docs and scenario examples seem to favor one thing over another and it would be good to document that so that people don't take dependencies on something that you plan to deprecate.

**Comment by JasSuri** [comment]
All of the above is not being deprecated, input validations are used sometimes since predicates are newer. Sub journeys are not documented yet, but to arrive more officially down the line. Usually this is not favoring, just convenience at the time of writing.
