### ISSUE TITLE
In theory, could the B2C-Token-Includes-AzureAD-BearerToken sample use Protocol Name="OpenIdConnect"

### ISSUE THREAD

**Issue by RedBlue1776** [azure-ad-b2c/samples#76]
Hi there, I noticed a difference in the setting below between the the AD implementation and the one in the Bearer token sample:

 <Protocol Name="OAuth"/>
 <Protocol Name="OpenIdConnect"/>

Would you help me understand where I could learn where one would be chosen over the other?

**Comment by JasSuri** [comment]
As this is not an issue with the sample, better to ask on stackoverflow. Reference the sample and the snippets that you are looking to compare.
