### ISSUE TITLE
Custom MFA TOTP Sample uses deprecated nuget package

### ISSUE THREAD

**Issue by CrazyTuna** [azure-ad-b2c/samples#78]
The custom MFA TOPT samples uses `OtpSharp.Core` nuget packages. 
I checked on the related github repo and there is a big disclaimer about using this library:
![image](https://user-images.githubusercontent.com/8588620/84086321-b5510680-aa3b-11ea-9771-0c9ec6beda44.png)

I think it would be good to reflect that at least in the documentation.
I ended up using [Otp.NET](https://github.com/kspearrin/Otp.NET).
I can create a PR if you're happy to update the sample.

**Comment by cljung** [comment]
Please create a PR and will update the sample. Thanks for noticing

**Comment by cljung** [comment]
Closing this issue. PR merged. Thanks!
