### ISSUE TITLE
Session management in /policies/embedded-password-reset/

### ISSUE THREAD

**Issue by n-mitic** [azure-ad-b2c/samples#79]
The policy files for embedded-password-reset allow that if the user closes tab after email verification (when we expect from him to enter new password), someone can later reopen tab and finish the password reset flow without email verification. (so this is some kind of security vulnerability)

I think that this is possible because of "x-ms-cpim-*" cookies, but I'm not sure how to change session management settings to resolve this.

Do you have some advice on how this can be changed, so the policy can behave the same as default B2C_1_Password reset user flow? (if someone later reopens the tab, he should need to verify email before being able to change the password)

**Comment by JasSuri** [comment]
We are investigating this.

**Comment by yoelhor** [comment]
Thank for bringing this to our attention. We have published new version of the policy, which contains an additional step the prevents the session issue. If you have any questions or need further information, please feel free to contact us.

**Comment by n-mitic** [comment]
Thank you
