### ISSUE TITLE
Azure AD B2C: Role-Based Access Control

### ISSUE THREAD

**Issue by glomaga** [azure-ad-b2c/samples#80]
Hi,
I have 2 Apps connected with Azure. 
One app is OpenIDConnect and the other app is SAML 2.0.

My configuration for Session behavior is Single sign-on configuration at the level of "Tenant".
When I log in to the first app I get the claim Groups correctly (I followed the example for role-Based Access Control to add the custom claim).

When trying to reach the second app I can access correctly without entering the password again ( the SSO works correctly because I have Tenant level config) BUT for the second app, I am not getting the claim for Groups. 

How can I get the Custom Claim Group when they are in the second application? Is the logic of IEF files not always called (specifically the api call)? Does it not matter if it is with the first application that I login or if I try to access the second application and the configuration SSO was executed to do not have to enter the credentials again?

**Comment by cljung** [comment]
Is the 2nd app the SAML app?
