### ISSUE TITLE
Progressive profiling

### ISSUE THREAD

**Issue by fedehermida** [azure-ad-b2c/samples#81]
Hi, 

I've been working with this sample: 
https://github.com/azure-ad-b2c/samples/tree/master/policies/progressive-profile

It seems it's missing the login-non-interactive technical profile. After adding this technical profile I tried to sign-in and got a generic warning stating that my ID or password is incorrect, which is not.

Is there any other sample regarding this?

Thanks

**Comment by cljung** [comment]
ProgressiveProfileTrustFrameworkExtensions.xml is using B2C_1A_TrustFrameworkExtensions as its BasePolicy, so thet login-NonInteractive config is expected to be done there. Can that be it?

**Comment by fedehermida** [comment]
Yes, after setting up the login-NonInteractive config inside the TrustFrameworkExtensions.xml the policies ended up working properly. Thanks!
