### ISSUE TITLE
Sample request for custom email verification

### ISSUE THREAD

**Issue by sven5** [azure-ad-b2c/samples#84]
Hi,

I request for a sample of a custom email registration policy issueing an email verification link instead of a numeric code. 
Our customer wants to have a verification link instead of a code.
Is this even possible with AD B2C?

Thanks
Sven

**Comment by JasSuri** [comment]
The sample here shows how to generate a custom link to "kickstart" a B2C journey.
https://github.com/azure-ad-b2c/samples/tree/master/policies/invite

Use that to send the user to a password reset journey, with custom email configured.
