### ISSUE TITLE
force-password-reset-after-90-days sample is not working as Expected

### ISSUE THREAD

**Issue by Webrusterkk** [azure-ad-b2c/samples#85]
Hello team,

When i tried to use the `force-password-reset-after-90-days` and test it, even though i changed password for the user.
it keeps on showing the `force-password-reset screen` again and again.

Can someone guide me where im doing wrong ?

**Comment by JasSuri** [comment]
How did you change the password?

**Comment by Webrusterkk** [comment]
Sorry .. We were giving wrong value in the configuration so it is keep on asking same value
