### ISSUE TITLE
TOU : show update message

### ISSUE THREAD

**Issue by Webrusterkk** [azure-ad-b2c/samples#86]
When TOU value is updated,

1. Already accepted user need to get something like "terms of use has been updated"
2. For new users it should be normal. "Accept TOU"

Is there a way to achieve this?

**Comment by JasSuri** [comment]
You can use a precondition such that I’m the case where the TOU doesn’t match the current version AND the user has not consented (attribute is null), show page X. And similar logic, where the TOU doesn’t match the current version AND the user has consented (Attribute not null), show page Y. 

I am closing this is it’s not an issue with the sample but more on how to enhance it. Better to ask this on stackoverflow.
