### ISSUE TITLE
SendGrid example XML got truncated

### ISSUE THREAD

**Issue by greglearns** [azure-ad-b2c/samples#87]
The XML is invalid and missing information in https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-email-verifcation-displaycontrol/policy/SendGrid/DisplayControl_TrustFrameworkExtensions.xml

Thank you! It's great being able to read through all of these examples!

**Comment by yoelhor** [comment]
Thanks for bringing this to our attention. The policy has been fixed.

**Comment by greglearns** [comment]
Follow on question: it isn't clear from the code nor from the writeup/documentation how one is supposed to use this. There are no Journey elements, so I believe it cannot be run. How does one use this? Thank you!

**Comment by JasSuri** [comment]
It uses the default user journey from the starter pack, and essentially hooks into an existing technical Profile.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-email-sendgrid#make-a-reference-to-the-displaycontrol

**Comment by greglearns** [comment]
Got it. So, for some signup.xml flow, I could change the inheritance in the
file from the default "trust framework extensions" file to instead point at
the new XML file that holds the new custom sendgrid XML. Correct?

**Comment by JasSuri** [comment]
Thats right.

**Comment by greglearns** [comment]
Thank you
