### ISSUE TITLE
Unable to connect to the metadata endpoint

### ISSUE THREAD

**Issue by Hardcorian** [azure-ad-b2c/samples#93]
Hello, I am working with the **SignInWithEmail** policy, configure the Azure B2C side with the steps in the Readme https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-email.

I am able to send and receive the e-mail with the token, the token is well formed, but I received the message showed in the screenshot.
![chrome_jvfpnVWaQS](https://user-images.githubusercontent.com/61288630/88534031-8a306f80-d007-11ea-9532-d069a7579214.png)

In the METADATA, I am using the openid-configuration of the application (NOT the custom policy), that is hosted locally, but externally reachable from a web browser.
If I insert he openid-configuraation of the policy, https://jwt.ms shows me a generic error.

Some idea that where is the problem? Thank you so much!

**Comment by JasSuri** [comment]
None of this is sensitive information. Share your id token hint technical profile.

**Comment by Hardcorian** [comment]
Hello, I completely forget that I opened this issue, sorry. I solved the problem using in the SignInWithEmail.xml policy the metadata of the custom policy, and works. This is the Technical Profile configuration of the file

![image](https://user-images.githubusercontent.com/61288630/89203809-78297080-d5b5-11ea-94a2-c474bbc64a31.png)

Thanks for the answer.
