### ISSUE TITLE
Implementing Terms Of Use policy

### ISSUE THREAD

**Issue by sven5** [azure-ad-b2c/samples#95]
Hi,

I successfully managed to implement the  terms of use policy.
However - sometimes the page to consent is displayed to the user even if he already consented. When this is happening there was no prompt for username/passwort. It seems that this is kind of auto-login through a cookie.

**Comment by JasSuri** [comment]
Can you link the exact sample being used

**Comment by sven5** [comment]
I implemented a mixture of the two features

- keep me signed in
- terms of use

I used several samples to accomplish the functionality of both. But perhaps there seems to be an issue in my settings.

**Comment by JasSuri** [comment]
Is is this one:
https://github.com/azure-ad-b2c/samples/tree/master/policies/terms-of-service

Or
https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-sign-up-versioned-tou

**Comment by JasSuri** [comment]
Reopen if you have an issue with the newer sample that fixed session management.
https://github.com/azure-ad-b2c/samples/blob/master/policies/sign-in-sign-up-versioned-tou
