### ISSUE TITLE
AADB2C90233: The provided id_token_hint parameter failed signature validation. Please provide another token and try again.

### ISSUE THREAD

**Issue by lizetpenamsft** [azure-ad-b2c/samples#96]
This issue is with the Invite set of policies and AzureADB2C.Invite MVC web application.
The sample app and policies are in https://github.com/azure-ad-b2c/samples/tree/master/policies/invite
I replaced the issuer in the HomeController.cs line 102 as specified on another issue reported before.
In my case I have the issuer as https://{b2ctenant}.b2clogin.com/{b2ctenant}.onmicrosoft.com/v2.0/ as indicated on the issue that is closed.
However, when I try the app using the B2C_1A_signup_invitation policy I always get error AADB2C90233:
 Could you please take a look and let me know what could possible cause this?

**Comment by JasSuri** [comment]
Set : HomeController.cs line 102 -> string value of "https://myissuer.com"
Make sure the issuer in the metadata endpoint of your app reflects this.
Make sure the `iss` claim in your id_token_hint reflects this.

You can also override the check here, make sure it matches what the `iss` claim in your id_token_hint is:
Set in technical profile `IdTokenHint_ExtractClaim`
```xml
<Item Key="issuer">https://myissuer.com</Item>
```
